label titleScreen: 
    hide sansImg
    hide undyneImg
    papyrus "WAIT"
    show papyrusImg surprised
    papyrus "WHAATT???"
    play sound "music/fx/lawAndOrder.wav"
    scene day1Alt title
    pause(3)
    papyrus "WHAT IS THIS?"
    gaster "I CAN JUMP YOU OVER THE END OF THE DAY IN WHICH I WILL EXPLAIN WHAT JUST HAPPENED"
    gaster "PLEASE SELECT THE IF YOU WANT THAT TO HAPPEN"
    menu:
        "Jump End of the Day":
            gaster "VERY WELL"
            jump endOfDay1
        "Continue Forward":
            gaster "I'LL WAIT TO TALK WITH YOU AT THE END OF THE DAY"
            gaster "GOOD LUCK"
            jump insideBuilding

label papyrusGasterConversation:
    papyrus "..."
    sans "ah?"
    sans "papyrus?"
    undyne "WHAT HAPPENING"
    undyne "Papyrus! react!"
    undyne "WE HAVE TO SAVE FRISK!"
    sans "papyrus..."
    gaster "YOUR FRIEND IS AT THE TOWER, THEY ARE TAKING THEM DOWN RIGHT NOW"
    gaster "IT'S THERE A GARAGE AT THE OTHER SIDE OF THE FORTRESS"
    gaster "GO" 
    gaster "SAVE THEM"
    gaster "I KNOW IS IMPORTANT FOR YOU"
    "*Papyrus jumps to the other side of the castle. Sans and Undyne are confused"
    undyne "Is he?"
    sans "i don't think so..."
    "*Papyrus comes back with Frisk. He leave them with Sans and Undyne. Then he runs away*"
    sans "papyrus?"
    undyne "Are you ok Frisk?"
    undyne "Let's go home"
    sans "i'll go to pick up papyrus"
    undyne "Sure"
    undyne "Tell him not been this cryptic next time"
    undyne "He's scaring me"
    "* Scene changes to the elevator. Where Papyrus has finally stopped running *"
    gaster "NOW YOU HAVE PLACES TO GO"
    papyrus "I'M... JUST..."
    gaster "I UNDERSTAND"
    gaster "WE CAN TALK ABOUT IF YOU LIKE"
    "* Papyrus and Gaster sit to watch the city lights *"
    papyrus "I SUPPOSE YOU ARE NOT GOING TO APOLOGIZE"
    gaster "I DO NOT FEEL SORRY, SO I WILL NOT"
    papyrus "THAT'S FINE"
    pause(1.0)
    gaster "WHAT I'M SORRY THOUGH IS THE FACT YOU HAD SEEN HOW MUCH A COWARD I AM THIS SOON"
    papyrus "UH?"
    papyrus "IT'S OK"
    papyrus "I MEAN"
    papyrus "IT'S NOT"
    papyrus "BUT I'M HAPPY YOU DID IT"
    papyrus "I DO APRECIATE HIM STILL ALIVE"
    papyrus "I JUST..."
    papyrus "I NEVER WANT TO CONSIDER ANYONE LIFE OBVIOUS"
    gaster "THAT JUST MAKE ME FEARFUL ABOUT ANYTHING YOU ARE GOING TO DO WHEN THE PROBLEM WITH..."
    gaster "ENDING THE LIFE OF THOSE PEOPLE ONCE EVERYONE DECIDES THE RELATIONSHIP WITH THE HUMANS IS SAFE"
    papyrus "YOU THINK SO"
    gaster "I INTELECTUALLY UNDERSTAND YOU KNOW THE RISKS OF EVERYTHING DANGEROUS YOU DO"
    gaster "BUT I CANNOT STOP FEAR SOMEDAY IS GOING TO AGAIN BACKFIRE LIKE..."
    gaster "THAT TIME AT THE EXIT OF SNOWDIN"
    papyrus "..."
    papyrus "I..."
    papyrus "I DON'T KNOW"
    papyrus "I WOULD LIKE TO SOMEONE ELSE TO TRUST ME AS YOU DO"
    papyrus "BUT I ALWAYS FEEL... SO DISPLACED AT TIMES..."
    gaster "AHH..."
    gaster "I KNOW THE FEELING..."
    gaster "PEOPLE WHO HAVE THEIR FEELINGS ON THEIR SLEEVE SEEM TO BE WEAKER, AND WE ARE AFRAID TO DAMAGE THEM, AND FEEL BAD"
    gaster "THEN WE SAY TO OURSELVES IS FOR THEIR OWN GOOD, AND THEN WE LIE TO THEM, BELIEVING THEY DOESN'T KNOW HOW TO HANDLE THEIR FEELINGS"
    gaster "LIKE A CHILD"
    gaster "BUT INSTEAD WE ARE TRYING TO PROTECT OURSELVES BECAUSE WE DON'T WANT TO FEEL BAD"
    gaster "I DON'T KNOW ABOUT EVERYBODY ELSE"
    gaster "BUT SANS SHOULD KNOW BETTER"
    papyrus "HE KNOWS HOW TO RAN AWAY"
    papyrus "FROM EVERYTHING"
    papyrus "I THINK HE'S JUST NOT READY TO CONFRONT WHAT HE HAS DONE"
    gaster "THIS IS MY FAULT"
    gaster "MAYBE I SHOULD STAY HERE AS PUNISHMENT FOR WHAT I HAVE DONE TO BOTH OF YOU"
    papyrus "DON'T SAY THAT!"
    papyrus "WE'RE GOING TO DECIDE THIS WHEN THE THREE ARE TOGETHER" 
    papyrus "SANS WILL FEEL WAY BETTER ABOUT EXPLAIN EVERYTHING HE LIED ABOUT"
    papyrus "AND YOU ARE GOING TO GET THE PUNISHMENT YOU DESERVE"
    papyrus "LIKE TALKING TO PEOPLE, AND MAKING FRIENDS!"
    gaster "AH... PAPYRUS MY BOY..."
    sans "papyrus?"
    papyrus "SANS! AHH... HI!"
    sans "are you ok?"
    papyrus "WHY YES! YES I AM"
    sans "what happened?"
    sans "you really are worrying everybody right now"
    papyrus "I DON'T KNOW"
    papyrus "I JUST FELT TERRIBLE ALL OF A SUDDEN AND..."
    papyrus "I GUESS I NEEDED A TIMEOUT"
    sans "oh.."
    sans "this is the first time is this sudden though"
    papyrus "I WILL TRY NEXT TIME NOT BEEN THIS ABRUPT"
    sans "i know you are always trying"
    sans "so..."
    sans "i guess you are ok now"
    sans "do you want to go back?"
    papyrus "YES!"
    papyrus "I WANT TO SEE IF FRISK IS FINE!"
    sans "i'm sure they are"
    sans "but showing them we care is never a bad idea"
    papyrus "GREAT! I LOVE THAT!"
    "* Next scene Papyrus and Gaster are together in the forest *"
    papyrus "I SLEPT FOR 2 DAYS!"
    papyrus "HOW THAT EVEN WORKS?"
    gaster "THAT KIND OF EMOTIONAL STRESS IS REALLY TIRESOME"
    papyrus "NOW SANS AND TORIEL ARE *REALLY* WORRIED ABOUT ME"
    papyrus "WE NEED TO GO BACK"
    gaster "NOW YOU WANNA RESET?"
    papyrus "THIS IS DIFFERENT"
    papyrus "THIS IS NOT IMPORTANT, IS JUST ANNOYING"
    gaster "WELL THEN"
    gaster "I'M GOING TO RESET"
    gaster "LET'S HOPE THE NEXT THING WE TRY IS GOING TO BE FRUITFUL"
    $ resets += 1
    jump day1
return

