label day4:
    toriel "Did you find anything about those human traffickers?"
    alphys "Everything we found is in the cloud, we just need to send them to the humans`s authorities"
    toriel "Good"
    alphys "What are we going to do with those monsters the kids are saying they brought them?"
    toriel "That`s complicated"
    toriel "We started this trying to avoid what Papyrus did affect our relationship with the humans"
    toriel "But now more monsters are involved"
    toriel "And we have no idea what those monsters want to do with those poor kids"
    if whoRescueMauricio:
        alphys "Papyrus said he found one of those monsters"
        alphys "They were all 'Humans are evil' and stuff"
        alphys "But doesn`t tell us too much"
        alphys "I mean, Undyne is not very keen of humans either"
        alphys "But at least she tries to give them a chance"
        toriel "I have this suspicion that they aren`t from our underground"
        alphys "What? There`s more than one cave?"
        toriel "Before the war, monsters were many more than now"
        toriel "But, when they trap us, they trap us all in one cave"
        toriel "At the beginning was the pain I focused on, but after years and years of been trapped"
        toriel "I started to wonder, since I was sure we were many more during the war"
        alphys "How all of us end up here?"
        toriel "I can be wrong and the deaths by the humans in the war were way more than I feel"
        toriel "But all the monsters loves Frisk"
        toriel "Right?"
        alphys "That a good question..."
    sans "hi"
    toriel "Oh, Sans!"
    toriel "Did you finish what I asked you?"
    alphys "You asked him something?"
    sans "she asked me to figure out if there some weird buildings in mount ameni"
    sans "i found something"
    sans "and i have to run away for my life"
    toriel "Oh Sans"
    sans "i`m ok. they just saw me"
    sans "they`re probably going to check for those kids they had in the cave"
    sans "i`m the worst spy you could find, been honest"
    toriel "What we`re going to do now?"
    sans "beats me"
    alphys "Yes..."
    alphys "They will be certainly angry if they find we already rescue those kids"
    toriel "One part of me wants to talk with those monsters and give them a chance"
    toriel "Another wants to roast them for make those poor kids suffer like that"
    alphys "OK, ok, I got it"
    sans "hehehehehehe..."
    toriel "Maybe we should just capture them and work on rehabilitation"
    toriel "We can`t have them still capturing kids just because"
    sans "it must be a reason"
    sans "i`m not saying that justify it"
    sans "i`m just saying that they must need so many kids for some sort of weird plan"
    alphys "And you think that because..."
    sans "just a hunch"
    toriel "Then we will just have to storm the place"
    toriel "It`s the quicker way to end with all this situation"
    toriel "I`ll call Asgore"

    if penAtAlphys:
        "Toriel goes out"
        alphys "Sans, I need to talk with you about something"
        sans "really?"
        alphys "Yes, it`s something important..."
        "Cut to Papyrus near to their house in Lower Snowdin"
        papyrus "I WONDER IF ALPHYS GOT ANYTHING DONE"
        papyrus "TODAY IT`S THE LAST DAY, I NEED THAT PROGRAM"
        sans "hello bro"
        papyrus "SANS! WHERE HAVE YOU BEEN?"
        sans "i was talking with alphys and she told me something very..."
        sans "interesting"
        papyrus "OH"
        papyrus "AHHHHHHHHH"
        sans "i know you are unable to do things quietly"
        sans "so i think is better to explain what`s going on"
        papyrus "I CAN`T"
        papyrus "I PROMISED I WILL NOT"
        alphys "It`s a complex machine"
        alphys "but your story about this being of determination, it`s even more intriguing"
        papyrus "IT`S NOT A BEING OF DETERMINATION"
        papyrus "IT`S A MONSTER WHICH BECAME DETERMINATION"
return