label day4:
    toriel "Did you find anything about those human traffickers?"
    alphys "Everything we found is in the cloud, we just need to send them to the humans`s authorities"
    toriel "Good"
    alphys "What are we going to do with those monsters the kids are saying they brought them?"
    toriel "That`s complicated"
    toriel "We started this trying to avoid what Papyrus did affect our relationship with the humans"
    toriel "But now more monsters are involved"
    toriel "And we have no idea what those monsters want to do with those poor kids"
    if whoRescueMauricio:
        alphys "Papyrus said he found one of those monsters"
        alphys "They were all 'Humans are evil' and stuff"
        alphys "But doesn`t tell us too much"
        alphys "I mean, Undyne is not very keen of humans either"
        alphys "But at least she tries to give them a chance"
        toriel "I have this suspicion that they aren`t from our underground"
        alphys "What? There`s more than one cave?"
        toriel "Before the war, monsters were many more than now"
        toriel "But, when they trap us, they trap us all in one cave"
        toriel "At the beginning was the pain I focused on, but after years and years of been trapped"
        toriel "I started to wonder, since I was sure we were many more during the war"
        alphys "How all of us end up here?"
        toriel "I can be wrong and the deaths by the humans in the war were way more than I feel"
        toriel "But all the monsters loves Frisk"
        toriel "Right?"
        alphys "That a good question..."
    sans "hi"
    toriel "Oh, Sans!"
    toriel "Did you finish what I asked you?"
    alphys "You asked him something?"
    sans "she asked me to figure out if there some weird buildings in mount ameni"
    sans "i found something"
    sans "and i had to run away for my life"
    toriel "Oh Sans"
    sans "i`m ok. they just saw me"
    sans "they`re probably going to check for those kids they had in the cave"
    sans "i`m the worst spy you could find, been honest"
    toriel "What we`re going to do now?"
    sans "beats me"
    alphys "Yes..."
    alphys "They will be certainly angry if they find we already rescue those kids"
    toriel "One part of me wants to talk with those monsters and give them a chance"
    toriel "Another wants to roast them for make those poor kids suffer like that"
    alphys "OK, ok, I got it"
    sans "hehehehehehe..."
    toriel "Maybe we should just capture them and work on rehabilitation"
    toriel "We can`t have them still capturing kids just because"
    sans "it must be a reason"
    sans "i`m not saying that justify it"
    sans "i`m just saying that they must need so many kids for some sort of weird plan"
    alphys "And you think that because..."
    sans "just a hunch"
    toriel "Then we will just have to storm the place"
    toriel "It`s the quicker way to end with all this situation"
    toriel "I`ll call Asgore"

    if penAtAlphys:
        "Toriel goes out"
        alphys "Sans, I need to talk with you about something"
        sans "really?"
        alphys "Yes, it`s something important..."
        "Cut to Papyrus near to their house at Lower Snowdin"
        papyrus "I WONDER IF ALPHYS GOT ANYTHING DONE"
        papyrus "TODAY IT`S THE LAST DAY, I NEED THAT PROGRAM"
        sans "hello bro"
        papyrus "SANS! WHERE HAVE YOU BEEN?"
        sans "i was talking with alphys and she told me something very..."
        sans "interesting"
        papyrus "OH"
        papyrus "AHHHHHHHHH"
        sans "i know you are unable to do things quietly"
        sans "so i think is better to explain what`s going on"
        papyrus "I CAN`T"
        papyrus "I PROMISED I WILL NOT"
        alphys "It`s a complex machine"
        alphys "but your story about this being of determination, it`s even more intriguing"
        papyrus "IT`S NOT A BEING OF DETERMINATION"
        papyrus "IT`S A MONSTER WHICH BECAME DETERMINATION"
        papyrus "BUT I´M NOT SUPPOSED TO TELL YOU THAT EITHER"
        papyrus "SO I WILL NOT CONTINUE"
        sans "come on bro"
        sans "don´t make this more difficult than it should be"
        papyrus "I PROMISED I WILL NOT, BUT YOU WILL KNOW EVERYTHING ONCE I FINISH WITH THIS"
        alphys "Do you?"
        alphys "Here! I have the pendrive with the program right here"
        alphys "But I will not give it to you until you explain yourself"
        papyrus "!?"
        papyrus "DR ALPHYS, PLEASE"
        papyrus "I REALLY PROMISED I WILL NOT SAY ANYTHING..."
        sans "..."
        sans "papyrus..."
        sans "you has been very suspicious lately"
        sans "are you"
        extend " traveling in time?"
        alphys "Hey!"
        alphys "What are you talking about?"
        gaster "THE ANSWER WILL BE YES,  MY DEAR SANS"
        sans "!?"
        alphys "But, who's...'"
        gaster "BUT THE HUMANS HAVE AN ESPECIFIC TERM FOR THIS KIND OF TRAVEL"
        gaster "THEY CALL IT 'GROUNDHOG DAY LOOP'"
        gaster "AFTER A MOVIE, I'LL BET"
        papyrus "!!!!!!!"
        papyrus "HOMEWORK GRABING ATTACK!!!"
        "And Papyrus grabs the pendrive from Alphys hands, like a dog"
        alphys "What?!"
        "Papyrus run away"
        alphys "Do you know who was that voice?"
        sans "yes"
        sans "but i can't tell you"
        alphys "Ok, what´s going on with you skeletons and your secrets?"
        sans "this is the main reason i don´t like to involve anyone else"
        "Sans goes away"
        alphys "But..."
        alphys "but..."
        alphys "I DESERVE AN EXPLANATION"
        "Cuts to Papyrus more in the forest"
        papyrus "HOW ARE YOU DOING THAT?"
        gaster "IT SEEMS, MY DEAR PAPYRUS, THAT I CAN PROJECT MY VOICE DURING THIS DAY TO THE REST OF THE WORLD"
        gaster "I SHOULD NOT DO THAT AGAIN, UNLESS THERE'S AN SPECIFIC NEED"
        papyrus "BUT I HAVE THE PENDRIVE"
        papyrus "THIS SHOULD RETURN YOUR BODY TO YOUR NATURAL STATE"
        gaster "ARE YOU SURE MY DEAR BOY?"
        papyrus "OF COURSE!"
        papyrus "DR ALPHYS IS THE SMARTEST MONSTER OF NEWER HOME"
        papyrus "I´M PRETTY SURE SHE COULD MADE IT WHILE WATCHING THE LAST EPISODE OF KISSY CUTIE MEW MEW"
        papyrus "AND HAVING ONE HAND TIED TO HER BACK"
        gaster "I DON'T KNOW WHAT ARE YOU TALKING ABOUT, BUT I TRUST YOU"
        gaster "MOVE POST HASTE! SO WE SHALL END THIS NIGHTMARE ONCE AND FOR ALL!"
        papyrus "YES SIR!"
        "Papyrus ran away. Sans appears just behind him"
        sans "that ham was definitely his"
        sans "but how?"
        sans "and why papyrus?"
        sans "argh!"
        $ pendrive = True
    
    if resets == 0:
        papyrus "I HAVE THIS TINGLING SENSATION THAT THEY WILL NOT ALLOW ME TO JOIN WHATEVER THEY WANT TO DO TODAY"
        papyrus "EVEN IF I WAS RIGHT YESTERDAY, THEY HAVE A POINT"
        papyrus "A REALLY SMALL POINT, BUT STILL"
        papyrus "..."
        papyrus "SOMETIMES I WONDER IF THEY HAVE MEETINGS WHICH I DON'T GET INVITED..."
        papyrus "OR THE INVITATION WAS LOST IN THE MAIL???"
        papyrus "I ALWAYS SEEM TO MISS SOME CRUCIAL INFORMATION OR SOMETHING"
        "woooooooooooooooo"
        papyrus "?!"
        papyrus "AHHHHHH????!!!!"
        papyrus "FROM WHERE THIS IS COMING FROM..."
        "The scene changes from the skelehouse to a mystery place with myst"
        "???" "{font=fonts/NewAster.ttf} MY... BO... CO... HE... CLO...{/font}"
        papyrus "A VOICE!"
        papyrus "DO YOU NEED HELP?!"
        papyrus "WHERE DO I GO?!"
        "???" "{font=fonts/NewAster.ttf} HE... THIS... YYYY {/font}"
        papyrus "THAT WAY?"
        papyrus "JUST WAIT MISTER! I'M COMING FOR YOU!"
        "* Walking sounds... Papyrus is getting closer *"
        papyrus "MISTER! CAN YOU TELL ME IF I'M CLOSE!?"
        "???" "{font=fonts/NewAster.ttf} THAT WAY MY... YES.. YOU ARE... CLOSER... {/font}"
        papyrus "GOOD TO KNOW!"
        papyrus "HELP ON THE WAY!"
        "* The mist become a lab with a computer and two giant tanks. Papyrus is really surprised *"
        papyrus "WOWIE..."
        papyrus "WHAT IS THIS?!"
        "???" "{font=fonts/NewAster.ttf}PAPYRUS! MY DEAR BOY! YOU MADE IT!"{/font}"
        papyrus "?!"
        "* The scene now points to Gaster, somewhat bigger, half melted, but still his eyes, mouth and cracks visible *"
        papyrus "AN ANALGAMATE?!"
        "???" "{font=fonts/NewAster.ttf} AH? NO NO MY DEAR PAPYRUS... {/font}"
        "???" "{font=fonts/NewAster.ttf} DON'T YOU REMEMBER ME? {/font}"
        "???" "{font=fonts/NewAster.ttf} I'M YOUR OLD FRIEND AND FORMER BOSS IN THE ROYAL LABORATORY {/font}"
        gaster "W.D. GASTER"
        "* Gaster's theme kicks in, pause for a 1.5 secs before doing anything*"
        "* stop music* "
        papyrus "WHO ARE YOU AGAIN?"
        gaster "YOU DEFINITELY DO NOT REMEMBER ME..."
        papyrus "SHOULD I?"
        gaster "YES, YES, YOU SHOULD"
        gaster "BEFORE I DISSAPEARED"
        gaster "I INYECTED ENOUGH DETERMINATION IN YOU AND SANS FOR BOTH TO SURVIVE WITH YOUR MEMORIES INTACT"
        gaster "IT SEEMS YOUR LEVELS WEREN'T HIGH ENOUGH"
        gaster "WHICH I FOUND HIGHLY SUSPICIOUS"
        papyrus "I DON'T FOLLOW"
        papyrus "CAN YOU START FROM WAAAAYYY BEFORE THAT"
        gaster "WELL, SINCE WE HAVE A PROBLEM WITH HACKING, I MUST START FROM THE BEGINNING THEN"
        gaster "EHEM!"
        "* Gaster's theme finally kicks in *"
        gaster "MY NAME IS W.D. GASTER"
        gaster "AND I WAS THE OLD ROYAL SCIENTIST BEFORE THE CURRENT ONE"
        gaster "BETWEEN MY ACCOMPLISHES ARE THE CORE AND THE DT EXTRACTOR"
        papyrus "THE CORE???!!"
        papyrus "DID YOU BUILD THE CORE?!!"
        gaster "I DESIGN IT"
        gaster "THE CONSTRUCTION DUTIES WENT TO DIFFERENT VERY TALENTED PEOPLE, MOST OF THEM FIRE ELEMENTALS"
        papyrus "WOWIE!"
        gaster "WHERE WAS I?"
        gaster "OF COURSE"
        gaster "BETWEEN MY DUTIES WAS TRYING TO FIND A WAY TO SHATTER THE BARRIER WHICH KEPT US UNDERGROUND"
        gaster "BUT MY STUDIES FOUND IT WAS IMPOSSIBLE UNLESS A MONSTER ABSORB ENOUGH HUMANS SOULS IN THE PROCESS"
        gaster "THAT WASN'T GOOD ENOUGH FOR THE QUEEN I'M AFRAID"
        gaster "SO I KEPT SEARCHING..."
        gaster "WE EVEN WENT BACK TO WAR..."
        gaster "BUT EVENTUALLY I COULD FIGURE OUT A WAY TO OBTAIN DETERMINATION FROM BEYOND THE REALITY, WHERE EVERYTHING IS SHROUDED IN DARKNESS"
        papyrus "BEYOND..."
        papyrus "REALITY?
        gaster "AT LEAST THAT WAS THE HYPOTESIS, SO WE TRIED OUT SEVERAL EXPERIMENTS"
        gaster "WE FORGOT THEM ALMOST IMMEDIATLY"
        gaster "UNTIL ONE OF MY ASSISTANTS DECIDED TO INJECT HIMSELF WITH DETERMINATION"
        papyrus "THEY... "
        papyrus "MELTED AWAY TOO?"
        gaster "NO"
        gaster "SORRY, BUT THIS WAS COMMON KNOWLEDGE IN THE OLD MONSTER SCIENTIFIC COMMUNITY"
        gaster "I GUESS WE BEEN SO SECRETIVE ABOUT IT WAS THE REASON FOR THAT TRAGEDY..."
        papyrus "YOU KNEW ABOUT THE MONSTER BODIES MELTING WHEN THEY HAVE TOO MANY DETERMINATION?"
        gaster "THE MONSTER SCIENTIFIC COMMUNITY KNEW THAT FOR CENTURIES"
        gaster "BUT WE NEVER WROTE IT DOWN, AS WAS CONSIDERED TABOO, AND WAS REDISCOVERED AGAIN AND AGAIN"
        gaster "I WROTE IT DOWN, ACTUALLY..."
        gaster "BUT... JUST REMEMBER THAT..."
        gaster "THANKS TO HIM WE WERE ABLE TO DISCOVER THAT, WITH ENOUGH DETERMINATION, WE COULD REMEMBER WHAT WE WERE DOING"
        gaster "EVENTUALLY I WANTED TO MAKE A BREAK THROUGH"
        gaster "TO FIGURE OUT WHICH WAS BEYOND THE PORTAL WE CREATED"
        gaster "MY ASSISTANTS WERE INYECTED WITH ENOUGH DETERMINATION TO REMEMBER ME, BUT NOT MELT"
        gaster "AND THEN I JUMPED INTO THE PORTAL"
        papyrus "WHAT HAPPENED?"
        papyrus "WHAT HAPPENED!?"
        gaster "I BECAME ONE WITH EVERYTHING"
        papyrus "WHAT?"
        gaster "I BECAME ONE WITH THE COMPLETE REALITY, WHICH HAS IT'S OWN BATTLE TO KEEP EXISTING"
        gaster "BUT"
        gaster "SOMEHOW I WAS ABLE TO SEE ONE SINGLE SPACE OF TIME, TRHU THE EYES OF A SINGLE LIVING BEING"
        gaster "A FALLEN HUMAN"
        papyrus "FRISK?"
        papyrus "YOU MEAN FRISK?!"

return
