label day4:
    toriel "Did you find anything about those human traffickers?"
    alphys "Everything we found is in the cloud, we just need to send them to the humans`s authorities"
    toriel "Good"
    alphys "What are we going to do with those monsters the kids are saying they brought them?"
    toriel "That`s complicated"
    toriel "We started this trying to avoid what Papyrus did affect our relationship with the humans"
    toriel "But now more monsters are involved"
    toriel "And we have no idea what those monsters want to do with those poor kids"
    if whoRescueMauricio:
        alphys "Papyrus said he found one of those monsters"
        alphys "They were all 'Humans are evil' and stuff"
        alphys "But doesn`t tell us too much"
        alphys "I mean, Undyne is not very keen of humans either"
        alphys "But at least she tries to give them a chance"
        toriel "I have this suspicion that they aren`t from our underground"
        alphys "What? There`s more than one cave?"
        toriel "Before the war, monsters were many more than now"
        toriel "But, when they trap us, they trap us all in one cave"
        toriel "At the beginning was the pain I focused on, but after years and years of been trapped"
        toriel "I started to wonder, since I was sure we were many more during the war"
        alphys "How all of us end up here?"
        toriel "I can be wrong and the deaths by the humans in the war were way more than I feel"
        toriel "But all the monsters loves Frisk"
        toriel "Right?"
        alphys "That a good question..."
    sans "hi"
    toriel "Oh, Sans!"
    toriel "Did you finish what I asked you?"
    alphys "You asked him something?"
    sans "she asked me to figure out if there some weird buildings in mount ameni"
    sans "i found something"
    sans "and i had to run away for my life"
    toriel "Oh Sans"
    sans "i`m ok. they just saw me"
    sans "they`re probably going to check for those kids they had in the cave"
    sans "i`m the worst spy you could find, been honest"
    toriel "What we`re going to do now?"
    sans "beats me"
    alphys "Yes..."
    alphys "They will be certainly angry if they find we already rescue those kids"
    toriel "One part of me wants to talk with those monsters and give them a chance"
    toriel "Another wants to roast them for make those poor kids suffer like that"
    alphys "OK, ok, I got it"
    sans "hehehehehehe..."
    toriel "Maybe we should just capture them and work on rehabilitation"
    toriel "We can`t have them still capturing kids just because"
    sans "it must be a reason"
    sans "i`m not saying that justify it"
    sans "i`m just saying that they must need so many kids for some sort of weird plan"
    alphys "And you think that because..."
    sans "just a hunch"
    toriel "Then we will just have to storm the place"
    toriel "It`s the quicker way to end with all this situation"
    toriel "I`ll call Asgore"

    if penAtAlphys:
        "Toriel goes out"
        alphys "Sans, I need to talk with you about something"
        sans "really?"
        alphys "Yes, it`s something important..."
        "Cut to Papyrus near to their house at Lower Snowdin"
        papyrus "I WONDER IF ALPHYS GOT ANYTHING DONE"
        papyrus "TODAY IT`S THE LAST DAY, I NEED THAT PROGRAM"
        sans "hello bro"
        papyrus "SANS! WHERE HAVE YOU BEEN?"
        sans "i was talking with alphys and she told me something very..."
        sans "interesting"
        papyrus "OH"
        papyrus "AHHHHHHHHH"
        sans "i know you are unable to do things quietly"
        sans "so i think is better to explain what`s going on"
        papyrus "I CAN`T"
        papyrus "I PROMISED I WILL NOT"
        alphys "It`s a complex machine"
        alphys "but your story about this being of determination, it`s even more intriguing"
        papyrus "IT`S NOT A BEING OF DETERMINATION"
        papyrus "IT`S A MONSTER WHICH BECAME DETERMINATION"
        papyrus "BUT I´M NOT SUPPOSED TO TELL YOU THAT EITHER"
        papyrus "SO I WILL NOT CONTINUE"
        sans "come on bro"
        sans "don´t make this more difficult than it should be"
        papyrus "I PROMISED I WILL NOT, BUT YOU WILL KNOW EVERYTHING ONCE I FINISH WITH THIS"
        alphys "Do you?"
        alphys "Here! I have the pendrive with the program right here"
        alphys "But I will not give it to you until you explain yourself"
        papyrus "!?"
        papyrus "DR ALPHYS, PLEASE"
        papyrus "I REALLY PROMISED I WILL NOT SAY ANYTHING..."
        sans "..."
        sans "papyrus..."
        sans "you has been very suspicious lately"
        sans "are you"
        extend " traveling in time?"
        alphys "Hey!"
        alphys "What are you talking about?"
        gaster "the answer will be yes, my dear sans"
        sans "!?"
        alphys "But, who's...'"
        gaster "but the humans have an especific term for this kind of travel"
        gaster "they call it 'groundhog day loop'"
        gaster "after a movie, i'll bet"
        papyrus "!!!!!!!"
        papyrus "HOMEWORK GRABING ATTACK!!!"
        "And Papyrus grabs the pendrive from Alphys hands, like a dog"
        alphys "What?!"
        "Papyrus run away"
        alphys "Do you know who was that voice?"
        sans "yes"
        sans "but i can't tell you"
        alphys "Ok, what´s going on with you skeletons and your secrets?"
        sans "this is the main reason i don´t like to involve anyone else"
        "Sans goes away"
        alphys "But..."
        alphys "but..."
        alphys "I DESERVE AN EXPLANATION"
        "Cuts to Papyrus more in the forest"
        papyrus "HOW ARE YOU DOING THAT?"
        gaster "it seems, my dear papyrus, that i can project my voice during this day to the rest of the world"
        gaster "i should not do that again, unless there's an specific need"
        papyrus "BUT I HAVE THE PENDRIVE"
        papyrus "THIS SHOULD RETURN YOUR BODY TO YOUR NATURAL STATE"
        gaster "are you sure my dear boy?"
        papyrus "OF COURSE!"
        papyrus "DR ALPHYS IS THE SMARTEST MONSTER OF NEWER HOME"
        papyrus "I´M PRETTY SURE SHE COULD MADE IT WHILE WATCHING THE LAST EPISODE OF KISSY CUTIE MEW MEW"
        papyrus "AND ONE HAND TIED TO HER BACK"
        gaster "i don't know what are you talking about, but i trust you"
        gaster "MOVE POST HASTE! SO WE SHALL END THIS NIGHTMARE ONCE AND FOR ALL!"
        papyrus "YES SIR!"
        "Papyrus ran away. Sans appears just behind him"
        sans "that ham was definitely his"
        sans "but how?"
        sans "and why papyrus?"
        sans "argh!"
        $ pendrive = True
    
    if resets == 0:



return