label finalLab:
    papyrus "Frisk! What are you doing? We're straying from the path!"
    papyrus "Undyne and the evil monsters are that way!"
    frisk "*Keeps running to that direction*"
    papyrus "FRISK! WAIT!"
    sans "what it's this place?"
    papyrus "SANS?!"
    sans "hey bro"
    papyrus "HAVE YOU SEEN FRISK?"
    sans "uhhh... no?"
    papyrus "SANS!"
    sans "sorry, i wasn't"
    frisk "..."
    papyrus "WOWIE..."
    sans "this is one kind of a machine"
    gaster "yes, it is indeed"
    sans "???"
    papyrus "WHO WAS?"
    gaster "that was me. I'm sorry for interrupt you, but it just called my attention that..."
    sans "you can speak to us"
    gaster "exactly"
    gaster "it's not something common, i may add"
    sans "Gaster??"
    gaster "oh... so YOU remember me"
    sans "How I'm going to forgot you MY OLD FRIEND"
    papyrus "YOU ARE A FRIEND OF SANS?"
    papyrus "THEN YOU ARE A FRIEND OF MINE AS WELL"
    frisk "*Points to themself and nods*"
    gaster "aren't you adorable?"
    papyrus "YOU ARE MAKING US BLUSH!"
    sans "wait, wait, this cannot be happening"
    gaster "why not?"
    sans "can you prove us you are gaster?"
    gaster "Mmm? well..."
    gaster "I, THE GREAT W.D. GASTER! ROYAL SCIENTIST AND..."
    gaster "and..."
    sans "last hope for our entire species..."
    gaster "yes, yes, right..."
    gaster "AND LAST HOPE FOR OUR ENTIRE SPECIES, WILL FIND A WAY TO THE SURFACE"
    gaster "TO FINALLY, SEE THE STARS AND THE FABLED SUN LIGHT!"
    papyrus "WOWIE! THAT WAS REALLY GOOD!"
    gaster "thanks you"
    frisk "*claps*"
    papyrus "I HOPE SOMEDAY I'LL BE ABLE TO MONOLOGUE THAT WELL"
    gaster "a good excercise i have found is just narrate what are you doing during the day"
    gaster "like"
    papyrus "I, THE GREAT PAPYRUS, AM OPENING THIS FRIDGE!"
    gaster "i see you already have the hang of this"
    sans "mmm..."
    sans "knock knock"
    gaster "ah..."
    papyrus "SANS"
    papyrus "PLEASE NO"
    gaster "who's there?"
    sans "etch"
    gaster "etch who?"
    sans "bless you"
    "....."
    papyrus "SANS!"
    gaster "you know those jokes are horrible!"
    sans "yes, but i love your face of pain when i tell one of those"
    sans "you are really gaster!"
    sans "oh god, i can't believe it"
    gaster "sadly, i'm just a hologram"
    frisk "..."
    papyrus "WHAT?!"
    sans "no way..."
    gaster "this machine was been used by this monsters as a way to extract souls and determination from humans"
    gaster "it also has an effect in the ui, and that's why this is a visual novel instead of an rpg"
    sans "but this is not canon"
    gaster "i know"
    papyrus "WHAT ARE YOU TWO TALKING ABOUT?"
    gaster "i have found with this machine i can communicate with people from my current position in the universe"
    frisk "?"
    gaster "but, sadly, there's no much it can be done"
    gaster "this machine will be destroyed by your good friend undyne in around 5 minutes"

menu:
    "*nudges Sans*":
        jump nudgeSans
    "Do nothing":
        jump DoNothing

label DoNothing:
    gaster "do you not want to hear my plea? i understand"
    papyrus "DO YOU HAVE SOMETHING TO SAY?"
    papyrus "ABOUT WHAT?!"
    "CRASH!"
    gaster "we're losing contact"
    gaster "i'm sorry, but i'm sending you back to the beginning"
    sans "are you reseting?"
    gaster "yes..."
    sans "don't do this to us!"
    gaster "i'm sorry sans, but what i have to say..."
    gaster "is..."
    gaster "too..."
    gaster "..."
    jump finalLab

label nudgeSans:
    frisk "*nudges Sans*"
    sans "no"
    frisk "*nudges harder*"
    sans "ok..."
    "*SHACK*"
    sans "time stopped. we can talk now."
    gaster "what about your good young brother?"
    sans "I don't want to involve Papyrus on this"
    gaster "i don't think is a very wise idea"
    sans "What do you know about Papyrus?"
    gaster "i know he has started to make edible sphagetti"
    frisk "!!??"
    gaster "but i also know by fact that it's only because someone who knows how to cook started to teach him"
    gaster "your friend undyne will be not so lucky"
    sans "That tell me nothing"
    gaster "my friend, you know your brother need to someday know the truth"
    sans "You know everybody needs to know the truth about you someday"
    sans "And anyway you decided that it will be better to everybody just forget about you"
    gaster "hipocritical, yes"
    gaster "but i didn't knew i could be saved at the time"
    sans "you mean..."
    gaster "yes, i mean it. but please unfreeze your brother. we need him."
    return
