label endingsFirstTry:
    papyrus "ARE THE WEKUFES GONE?"
    gaster "YES, THEY ARE"
    gaster "I CANNOT FIND ANY, MOST PROBABLY THEY ARE GONE"
    papyrus "IT'S TIME TO SET THIS ON!"
    "*Papyrus puts the pendrive in the Computer and fire it off*"
    papyrus "IT'S GOING TO TAKE A COUPLE OF MINUTES TO LOAD"
    papyrus "ARE YOU EXCITED?!"
    gaster "I CANNOT SHAKE THIS FEELING WE ARE FORGETING SOMETHING"
    papyrus "DO YOU WANT TO STOP THE PROCESS?"
    gaster "NO, NO"
    gaster "I MIGHT BE JUST PARANOID"
    papyrus "WHAT DO YOU THINK IS GOING TO HAPPEN WHEN YOU COME BACK?"
    papyrus "PEOPLE WILL REMEMBER YOU, LIKE YOU WERE NEVER GONE?"
    papyrus "I'LL REMEMBER EVERYTHING ABOUT SCIENCE?"
    gaster "I'LL BLOW UP IN MILLIONS OF SMALL PIECES AND I'LL COVER ALL THE BUILDINGS OF THE NEW MONSTERS KINGDOM IN A WHITE POWDER?"
    papyrus "GASTER!"
    gaster "IT'S BETWEEN THE REALM OF POSSIBILITY"
    papyrus "NOW I'M FINISHING DEALING WITH SANS'S LAZINESS, I'LL HAVE TO DEAL WITH YOUR NEGATIVENESS?"
    gaster "IS IT THAT A WORD?"
    gaster "..."
    gaster "WELL, I TOLD YOU, I'M A BIT PARANOID AT TIMES"
    papyrus "NYEH.."
    papyrus "I CANNOT WAIT FOR THAT!"
    gaster "MY DEAR PAPYRUS..."
    sans "this is the lab i told you about"
    papyrus "SANS?"
    gaster "LET'S ME SEE..."
    "* Scene changes to Sans and Frisk walking on the corridor of the Wekufes lab *"
    frisk "You sure they are here..."
    sans "i'm not sure if papyrus is with someone"
    sans "i just know papyrus came here"
    sans "and that i know that voice..."
    frisk "Someone you knew from before?"
    sans "a... friend..."
    frisk "Is it their name..."
    frisk "Gaster?"
    sans "how do you know that?"
    frisk "I found a monster"
    frisk "In greyscale"
    frisk "Who commented me about it"
    sans "oh..."
    frisk "I think it was a malfunction..."
    sans "on reality?"
    frisk "..."
    frisk "Yeah..."
    sans "well.."
    sans "we better found them"
    sans "papyrus has been very weird lately"
    frisk "Did you noticed?"
    sans "ehh..."
    sans "i thought it was just him been him"
    sans "he always does weird stuff..."
    frisk "I don't think so.."
    sans "wait..."
    sans "frisk..."
    "* Scene goes back to Gaster and Papyrus *"
    gaster "THEY ARE SANS AND THE FALLEN HUMAN"
    papyrus "THEIR NAME IS FRISK"
    papyrus "WAIT"
    papyrus "WHY AM I GETTING UPSET AT YOU CALLING FRISK FALLEN HUMAN?"
    papyrus "AND WHY DO YOU NOT CALL THEM BY THEIR NAME?"
    gaster "YOU ARE ALREADY GETTING SOME OF YOUR MEMORY BACK"
    gaster "IT'S NOT CONVENIENT FOR ME, BUT MEMORY IS MEMORY"
    papyrus "IT HAS FINISHED LOADING!"
    gaster "WE MUST DECIDE IF WE CONTINUE"
    gaster "DO WE?"
    jump endingMenuFirstTry

label endingMenuFirstTry: 
    menu:
        "Of Course!":
            $ firstTry = False
            jump startEndingGasterFirstTry
        "I have 2nd thoughts":
            jump resetOrEndingFirstTry

label startEndingGasterFirstTry:
    papyrus "OF COURSE!"
    papyrus "LET'S DO THIS!"
    gaster "smiles"
    papyrus "I PRESS ENTER!"
    gaster "AND NOW WE..."
    "fades to white"
    "shows Gaster back to normal, AKA, not half melting. He's as tall as papyrus, with a black suit and a white turtle neck"
    "he still has the cracks in his skull, cannot emote in one of his eyes and has missing the ring finger in both of his hands"
    gaster "IT WORKED"
    gaster "IT WORKED PAPYRUS!"
    gaster "..."
    gaster "PAPYRUS!"
    "shows Papyrus how Gaster was at the beginning. Half melted, somewhat deformed, but still with his smile plastered in his face"
    papyrus "I THINK THERE'S SOMETHING WE DIDN'T ACCOUNT FOR"
    gaster "OH... NO..."
    papyrus "IF YOU ASK ME..."
    papyrus "I THINK WE NEED TO LEARN MORE..." 
    papyrus "ABOUT..." 
    papyrus "WHAT..." 
    papyrus "IS BEYOND..." 
    papyrus "THE DARKNESS..."
    gaster "THERE'S NOTHING WE CAN COMPREHEND FROM THERE"
    papyrus "I REFUSE THAT STATEMENT!"
    gaster "IT DOESN'T HAVE TO BE YOU"
    "*steps*"
    gaster "THE SYSTEM SAYS THERE'S SOME DETERMINATION LEFT"
    gaster "WE CAN RESET TO TRY AGAIN!"
    papyrus "THAT'S NOT AN OPTION WE CAN TAKE"
    gaster "I KNOW..."
    gaster "BUT PLEASE, SHOW THEM THE MENU..."
    gaster "THEY MIGHT WANT TO TRY"
    menu:
        "Reset":
            gaster "OH, THANKS YOU!"
            gaster "WE WILL TALK IN THE PAST, MY DEAR PAPYRUS..."
            papyrus "..."
            $ resets = resets + 1
            jump day1
        "Continue":
            gaster "NO..."
            papyrus "DO NOT WORRY ABOUT ME!"
            papyrus "YOU..." 
            papyrus "WILL..." 
            papyrus "FIND..." 
            papyrus "A..."
            gaster "WHAT IF I DON'T?"
            gaster "WHAT IF I DIE AND YOU ARE STILL TRAPPED IN THE DARKNESS!?"
            papyrus "I KNOW YOU'LL DO YOUR BEST..."
            gaster "WHAT IS IT NOT GOOD ENOUGH?!"
            papyrus "..."
            papyrus "YOU WORRY TOO MUCH"
            papyrus "I'M NOT OK WITH THIS"
            papyrus "BUT I CAN HANDLE IT"
            papyrus "I WILL HANDLE IT!"
    
label resetOrEndingFirstTry:
    
label startEndingPapyrusFirstTry:
            

return 
