label freeMorning:
    
    papyrus "LOOKIE THAT!"
    papyrus "I HAVE FREE THE MORNING!"
    papyrus "WHAT SHALL I DO?"

    menu:
        "Go help Toriel at the School" if not helpedToriel:
            papyrus "LET'S SEE IF TORIEL HAVE SOMETHING TO DO!"
            papyrus "THEY ARE STILL MOVING THINGS FROM THE UNDERGROUND AFTER ALL"
            $ helpedToriel = True
            jump torielSchool

        "Go grocery shopping" if not metAsgore:
            papyrus "I'LL BETTER GO TO GET SOME GROCERIES"
            papyrus "MAYBE I CAN FIND SOME DISCOUNTS ON THE SPIDER BAKERY"
            papyrus "EVERYTHING IS ALWAYS SO EXPENSIVE"
            $ metAsgore = True
            jump groceryShopping
            
        "Go check Sans" if not visitSans:
            papyrus "MAYBE I SHOULD CHECK WHAT SANS IS DOING"
            $ visitSans = True
            jump checkSans

        "Go check with Undyne" if not visitUndyne:
            papyrus "I SHOULD CHECK OUT WITH UNDYNE"
            papyrus "I HAVE A SURPRISE FOR HER AND I DON'T WANT TO FORGET!"
            $ visitUndyne = True
            jump visitUndyne
        
        "Go visit Alphys at the New Lab" if not visitAlphys:
            papyrus "I HEARD DR ALPHYS IS WORKING ON SOMETHING NEW"
            papyrus "MAYBE IS A NEW KIND OF PUZZLE!"
            papyrus "OK, MAYBE NOT"
            papyrus "BUT SHOULD BE INTERESTING!"
            $ visitAlphys = True
            jump visitAlphys
        
        "Go check how Frisk is doing" if not visitFrisk:
            papyrus "FRISK IS NOT GOING TO SCHOOL"
            papyrus "POOR HUMAN IS RESTING AFTER EVERYTHING JUST HAPPENED"
            papyrus "MAYBE WE CAN DO THAT TOGETHER!"
            $ visitFrisk = True
            jump visitFrisk
            
label visitFrisk:
    papyrus "LOOK WHO'S THERE!"
    papyrus "IT'S THE GREAT PAPYRUS WHO'S VISITING YOU!"
    frisk "*smiles*"
    frisk "*i wanted to talk with you*"
    papyrus "ABOUT WHAT?"
    frisk "*it's a hunch i have*"
    papyrus "OH, THEN MUST BE IMPORTANT!"
    frisk "*have you feel something is deciding for you things?*"
    if resets < 1:
        papyrus "NO, NOT REALLY"
        frisk "..."
        papyrus "DON'T FEEL BAD!"
        papyrus "LET'S GO TO THE SPIDER BAKERY TO GET SOME POWER BRACELETS!"
        frisk ".."
        papyrus "YES, RIGHT, I FORGOT"
        papyrus "I'LL BRING THEM TO YOU THEN!"
        "WHOOOOSSSHHHHHH"
        papyrus "BACK!"
        papyrus "TAKE SOME GREAT BRECELETS!"
        frisk "..."
        papyrus "THOSE CAME BACK?"
        frisk "..."
        papyrus "THAT'RE REALLY COOL BRACELETS!"
        papyrus "..."
        frisk "..."
        papyrus "ISN'T IT WEIRD?"
        frisk "?!"
        papyrus "WE'RE ALL OUT"
        papyrus "I KNEW PEOPLE WHO LOST HOPE"
        papyrus "AND PEOPLE WHO DIED STILL HOPING"
        papyrus "BUT SOMEHOW, WE'RE OUT"
        papyrus "THANKS TO YOU"
        frisk "*pats Papyrus*"
        papyrus "I ONLY KNEW IF I HAD 1%% OF POWER ON GET IN US OUT, I WILL USE IT"
        papyrus "BUT I STILL DON'T KNOW IF I HAD SOMETHING TO DO ON THIS"
        frisk "??"
        papyrus "YEAH"
        papyrus "IT'S A WEIRD THING TO ASK"
        papyrus "SOMETIMES I FEEL POWERLESS OVER THINGS"
        papyrus "BUT AFTER THAT I FORGET ABOUT IT"
        papyrus "I DO WHAT I CAN, WITH THE AMOUNT OF POWER I HAVE"
        papyrus "I GUESS THAT'S THE IMPORTANT PART"
        frisk "..."
        frisk "sometimes, I feel i have none"
        papyrus "YES, ME TOO"
        papyrus "BUT NOT ALL THE TIME"
        frisk "now"
        papyrus "OH FRISK!"
        papyrus "YOU ARE MY FAVORITE HUMAN, ALWAYS REMEMBER THAT!"
        papyrus "AND CHOOSED THAT WITH MY OWN WILL!"
        "HUGS"
        
    jump morningGo
         
label visitAlphys:
    papyrus "DR ALPHYS!"
    alphys "Papyrus!"
    alphys "What"
    alphys "eh.."
    alphys "ehhh..."
    papyrus "YOU SAID SOMETHING IN OUR LAST TRAINING ABOUT A NEW EXPERIMENT OF YOURS"
    papyrus "I CAME TO CHECK IF YOU NEEDED SOME MORAL SUPPORT"
    alphys "ahhh..."
    papyrus "I´M YOUR PERSONAL TRAINER AFTER ALL"
    alphys "Now I need some quiet"
    papyrus "YOU MEAN WHITE NOISE"
    papyrus "OR ELSE YOU'LL END UP WATCHING THE NEW SEASON OF MEW MEW"
    alphys "Come on Papyrus"
    alphys "The first chapter was promising"
    alphys "But for the moment is as good as the second season"
    alphys "Which means is trash"
    alphys "While they admitted the second season ruined Mew Mew story arc"
    alphys "And they are trying to fix it"
    alphys "I don't see how that is fixing it"
    alphys "They should try another aproach if they want to keep the franchise alive"
    alphys "But the 1st season is a classic already"
    alphys "They can't fix that"
    papyrus "ISN'T THE MANGA STILL GOING?"
    alphys "Yes, yes"
    alphys "But that a manga based on the 1st season"
    alphys "Mew Mew is an original animation"
    alphys "It's not very good"
    alphys "But at least is better than this 2nd and 3rd season trash"
    papyrus "I SEE YOU HAVEN'T LOST IT!"
    papyrus "UNDYNE IS ALWAYS TELLING ME ABOUT HOW YOU RANT ABOUT WHEN THEY SEE AN EPISODE OF THE NEW SEASON"
    alphys "Yeah, she loves see me suffer and complain"
    papyrus "SHE DESCRIBE IT AS 'PASSIONATE AND FOCUSED'"
    alphys "Why we always end up talking about how much Undyne loves me?"
    papyrus "I DON'T KNOW"
    papyrus "YOU STILL SEEMS HAVE SOME ISSUES WHEN IS ABOUT LIKING ANIME"
    alphys "You know"
    alphys "I lied so much some times I feel I don't deserve Undyne's love"
    papyrus "SANS IS GETTING BETTER ABOUT HIS LAZYNESS, BUT VERY SLOWLY"
    papyrus "MAYBE YOU JUST NEED MORE TIME TO UNDERSTAND UNDYNE LOVES YOU FOR HOW YOU ARE"
    alphys "Maybe..."
    alphys "Well..."
    alphys "I'd better get back to programming"
    papyrus "PROGRAMMING?"
    alphys "Yes..."
    alphys "It's something very difficult, and you need time and effort to understand them"
    papyrus "HEY! THEN IS LIKE FIGHTING!"
    papyrus "OR COOKING SPAGUETTI!"
    papyrus "YOU NEED TIME AND EFFORT TO UNDERTAND IT AND GET GOOD AT IT!"
    alphys "Something like that"
    alphys "But in programming you tell the computer what to do"
    papyrus "REALLY?"
    alphys "Yes"
    alphys "But in a language the computer understand"
    alphys "Because the computer doesn't understand normal language"
    papyrus "WHAT KIND OF THINGS YOU CAN TELL TO THE COMPUTER"
    alphys "For a very simplificated example"
    alphys "You can tell them that..."
    alphys "That table is an object which can contain some other objects like cups"
    papyrus "SO THE OBJECT TABLE ATRIBUTTE IS CONTAIN OTHER OBJECTS?"
    alphys "Yes..."
    alphys "..."
    alphys "Papyrus.."
    alphys "What's a float?"
    papyrus "A TYPE OF NUMBER VARIABLE THAT CAN CONTAIN DECIMAL POINTS"
    alphys "What's a factory?"
    papyrus "AN OBJECT WHICH PRODUCES OTHER OBJECTS"
    alphys "A singleton?" 
    papyrus "AN OBJECT WHICH HAVE A SINGLE INSTANCE DURING RUN"
    alphys "And Script Oriented Programming?"
    papyrus "A SMALL PROGRAM WHICH RUNS ON SEQUENCIAL ORDER"
    alphys "And a stack?"
    papyrus "A DATA STRUCTURE OF OBJECTS IN WHICH CAN ONLY ACCESS THE LAST ONE AT A TIME"
    alphys "Papyrus"
    alphys "Since when you know Programming Theory and Data Structures?"
    papyrus "SINCE YOU SAID TABLE"
    papyrus "IT JUST CAME TO ME SUDDENLY"
    alphys "Whoa.. that's weird"
    papyrus "I KNOW"
    papyrus "I KNOW..."
    $ papyrusKnowsProgramming = True
    jump morningGo

label visitUndyne:
    papyrus "UNDYNE!"
    undyne "PAPYRUS! What are you doing here?!"
    papyrus "I THOUGHT YOU WERE IN YOUR FREE TIME"
    undyne "I am"
    undyne "I'm just kind of nervious"
    papyrus "I NOTICED THAT"
    undyne "It not just..."
    undyne "You know..."
    undyne "But also..."
    undyne "That stupid human tradition"
    papyrus "YES, I HEARD ABOUT THAT"
    undyne "And Alphys likes humans"
    undyne "I wanted to surprise her but..."
    undyne "It's useless"
    papyrus "NOT IF YOUR FAVORITE SKELETON JUST HAPPEN TO"
    undyne "You found it?!"
    papyrus "..."
    papyrus "YES"
    papyrus "YES I DID"
    undyne "NO WAY"
    papyrus "YES WAY!"
    papyrus "HERE IS!"
    undyne "It's the Kissy Cutie Mew Mew limited edition Wedding Ring!"
    papyrus "ISN'T THAT WEIRD?"
    papyrus "THE GUY WHO SOLD ME THE THING ON THE HUMAN INTERNET SAID IT WAS A REAL RING MADE WITH GOLD AND DIAMONDS"
    papyrus "AND I'M LIKE"
    papyrus "WHO MAKES THINGS OUT OF MONEY?"
    undyne "I don't know"
    undyne "There's things about humans which are weeeiiiirrrddddd"
    papyrus "YEAH"
    undyne "But from where did you get the human money?"
    papyrus "HALLOWEEN DELIVERY"
    undyne "What?!"
    papyrus "YOU KNOW, THAT WEIRD FESTIVITY THEY HAVE IN WHICH THEY CELEBRATE US"
    undyne "Alphys explain me once what about that thing"
    undyne "But 'candy' still feels too flimsy"
    papyrus "WELL, JUST HAPPENS THAT HUMANS DOESN'T MIND HAVE THEIR THINGS DELIVERED BY A SKELETON AROUND THAT TIME"
    undyne "Papyrus... I..."
    undyne "I don't know what to say"
    papyrus "JUST KEEP IT QUIET"
    papyrus "ALPHYS SHALL NEVER KNOW I WAS THE ONE WHO FOUND IT"
    undyne "Are you sure?"
    papyrus "YES"
    papyrus "JUST ASK HER WHEN YOU THINK THE TIME IS RIGHT"
    undyne "You are getting weirdly wise Papyrus"
    undyne "But Frisk is going to be the ring bearer"
    papyrus "THE WHAT NOW?"
    undyne "You didn't know?"
    undyne "The humans weddings are super complicated with tons of parts"
    undyne "And I'm sure Alphys will want a full scale human style wedding"
    undyne "AAARRRRrrrrRRGGGggHHHHHhhhhhh"
    papyrus "WELL"
    papyrus "I'M GOING TO BE ONE OF THE SPOUSES BEST FRIEND!"
    papyrus "THAT'S A COOL THING TO BE IN A WEDDING!"
    undyne "You are way too nice Papyrus"
    papyrus "YOU SAY THAT LIKE IS A BAD THING"
    undyne "Well, I'm going to wait a couple of months"
    undyne "I have been studying this thing of the human wedding"
    undyne "And I still can't wrap up my head around this concept of the 'best man'"
    papyrus "SOUNDS LIKE A KIND OF FISH"
    undyne "Yeah..."
    undyne "Maybe I should ask Onion-san"
    $ visitUndyne = True
    jump morningGo
label checkSans:
    if papersPapyrusCreation == True:
        papyrus "SANS IS NOT HERE"
        papyrus "WHY?!"
        papyrus "I GUESS HE WILL APPEAR TO MAKE JOKES AT MY EXPENSE IN ANY SECOND"
        papyrus "BUT WHERE'S HE IS?"
        sans "sup' bro"
        papyrus "SANS! I NEED TO TALK WITH YOU!"
        sans "but bro"
        sans "i has been doing a ton of work"
        papyrus "IT'S NOT ABOUT PUNS!"
        papyrus "LISTEN"
        papyrus "I FOUND THIS PAPERS AT THE SCHOOL BASEMENT WHICH ARE A WEIRD KIND OF DIARY AND SOMEONE CALLED LIKE YOURSELF APPEAR IN THEM AND THEY WERE TALKING ABOUT MAKING A BROTHER FOR THIS PERSON CALLED EXACTLY LIKE YOU AND I SAID MAYBE IS SANS AND MAYBE THEY'RE TALKING ABOUT ME SO I CAME TO SEE IF YOU CAN TELL ME IF IT'S TRUE AND IF YOU REMEMBER ANY OF THIS"
        sans ".."
        sans "you have been with alphys way too long"
        papyrus "I WAS THINKING THAT MAYBE YOU COULD SHED SOME LIGHT ABOUT THIS"
        sans "that's dangerous"
        papyrus "WHAT?"
        papyrus "THE PAPERS?"
        sans "think"
        papyrus "SANS!"
        sans "just give me those papers and"
        papyrus "NO!"
        papyrus "YOU ALWAYS ARE DOING THINGS WITHOUT TELLING ME!"
        papyrus "I WILL NOT GIVE YOU THIS PAPERS UNTIL YOU TELL ME WHAT'S GOING ON!"
        sans "catch the stick, catch the stick"
        papyrus "OH! A STICK!"
        "Sans throws the stick and Papyrus leave the papers behind so he can catch them"
        sans "sometimes i'm glad i used some atributes of a dog"
        papyrus "CURSES! HE GOT ME!"
        papyrus "BUT THIS IS NOT DONE YET!"
        papyrus "HOMEWORK GRABING ATTACK!!!"
        "CHOMP!"
        sans "uh?"
        papyrus "TALK SANS!"
        sans "but... i´m too sleepy right... now..."
        sans "zzzzZZZZzzzz"
        papyrus "GREAT, THE SPECIAL ABILITY OF MY BROTHER"
        papyrus "SLEEPING EVERYWHERE AND EVERY MOMENT"
        papyrus "I WILL NOT GET ANSWERS FROM HIM"
        papyrus "I GUESS I HAVE TO ASK GASTER"
        sans "gaster?"
        papyrus "NOW WE'RE TALKING!"
        papyrus "EXPLAIN"
        sans "...."
        sans "w. d. gaster is our dad"
        papyrus "HE NEVER TOLD ME THAT"
        sans "he doesn't like the term, because he created us in regeneration tubes"
        sans "those probable are notes from he decided to create either of us"
        papyrus "BUT WHY NOBODY ELSE REMEMBER HIM?"
        sans "you shouldn´t remember him, only me"
        sans "how do you remember him?"
        papyrus "GOTTA GO BYE"
        "*Papyrus leaves*"
        sans "i will never catch him"
        sans "but how he knows anything about gaster?"
        sans "something weird is happening"
        $ gasterPapyrusSansDad = True
    else:
        papyrus "HE'S GETTING BETTER THANKS TO TORIEL"
        papyrus "BUT HE'S STILL SLACKING OFF WAY TOO OFTEN!"
        "*change scene*"
        papyrus "SANS IS NO WHERE TO BE FOUND"
        papyrus "HE'S LUCKY THERE'S NO MONSTERS WANTING TO GO TO HIGH SNOWDIN"
        papyrus "BUT HE SHOULD BE HERE!"
        sans "sup' bro?"
        papyrus "SANS!"
        papyrus "WHERE HAVE YOU BEEN?"
        sans "just walking"
        papyrus "WALKING TO GRILLSBY'S I BET"
        sans "no"
        sans "just walking"
        sans "the forest is very nice this time of the day"
        papyrus "YOU DON'T FOOL ME"
        papyrus "YOU WERE DOING SOMETHING LAZY I'M SURE!"
        sans "i was technically slacking off though"
        papyrus "BUT THAT KIND OF SLACKING OFF..."
        papyrus "..."
        sans "what?"
        papyrus "I DO THAT AS WELL"
        sans "you? slacking off?"
        papyrus "IT'S JUST"
        papyrus "THE TREES ARE GREEN"
        papyrus "THE SKY IS BLUE"
        papyrus "THE AIR IS CLEAN"
        papyrus "THE OUTSIDE IS AMAZING"
        sans "just give you energy to continue"
        papyrus "YES!"
        papyrus "MAYBE IS PART OF THE REASON OF WHY YOU ARE GETTING LESS LAZY"
        sans "?!"
        sans "it seems i'm losing my edge"
        papyrus "MAYBE YOU SHOULD USE YOUR ACTUAL FREE TIME TO DO THAT THOUGH"
        sans "don't worry"
        sans "i have that machine over there i did"
        sans "it tell me when someone is close"
        papyrus "AND YOU ARE GETTING RESPONSIBLE!"
        papyrus "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        sans "i'm totally losing my edge"
        papyrus "TOOOOORRRRRIIIIIIIIEEEEEEEEEEEEEELLLLLLLLLLLL!!!!!!!!!!!!!!!"
    jump morningGo
    
label groceryShopping:
    papyrus "YES, EVERYTHING IS SO EXPENSIVE"
    papyrus "I THOUGHT YOU GUYS HAVE ALREADY MOVE ALL OF YOU FROM THE RUINS"
    muffet "It's called offer and demand deary"
    muffet "Monsters buy at this price anyways"
    papyrus "YES, MONSTERS LIKE ME"
    "Papyrus pays Muffet for the bread and some donuts"
    asgore "Excuse me, Do you have some spider muffins?"
    papyrus "YOUR MAJESTY!"
    asgore "Oh, howdy!"
    papyrus "WHAT ARE YOU DOING HERE?!"
    asgore "Buying some spider bread, like you do"
    asgore "I like grocery shopping"
    asgore "It help me to stay connected with everybody"
    papyrus "IF YOU SAY SO"
    asgore "Your head in the school yard got a severe case of bad eyebrows"
    asgore "I need to fix it before the afternoon or else"
    papyrus "MAYBE I NEED SOME EYEBROWS"
    papyrus "HOW I WILL LOOK WITH SOME EYEBROWS?"
    papyrus "INTERESTING I THINK"
    asgore "You are as great as you can be the way you are"
    papyrus "YES, I KNOW THAT"
    papyrus "I JUST THINK ON TRYING A NEW STYLE ONCE IN A WHILE"
    papyrus "YOU NEVER KNOW WHAT CAN YOU GET WITH A NEW HAIRSTYLE"
    asgore "I will personally not worry about it"
    asgore "Especially when you don't have any hair"
    papyrus "YOUR MAJESTY!"
    papyrus "I´M PRETTY SURE I CAN USE SOME EXTENSIONS"
    papyrus "LACK OF HAIR HAS NEVER BEEN A PROBLEM FOR ME"
    papyrus "WE SKELETONS ARE SMART!"
    asgore "There´s no way I can stop you, do I?"
    papyrus "OF COURSE NOT"
    asgore "I guess I´d better help then"
    asgore "Take some of my beard"
    papyrus "REALLY SIR??"
    papyrus "THANKS YOU!"
    "*Asgore gives Papyrus some of his hair, but inmediatly becomes ashes when he recieve it"
    papyrus "AHHHHWWWW...."
    asgore "I'm sorry Papyrus, real monster hair doesn't work like humans'"
    papyrus "THANKS AGAIN SIR"
    asgore "A pleasure"
    if resets < 3 and resets > 1:
        asgore "..."
        show papyrusImg worried flip at fade
        papyrus "?!"
        asgore "Uh, nothing... bye Papyrus"
    elif resets < 5 and resets > 3:
        asgore "You know"
        asgore "You suddenly remind me of... someone"
        papyrus "IT'S THEIR NAME W.D. GASTER?"
        asgore "Not sure"
    elif resets > 5:
        asgore ".."
        papyrus "IT´S THERE SOMETHING YOU WANT TO TELL ME?"
        asgore "Not exactly"
        asgore "I'm fine"
        $ asgoreKnows = True
    papyrus "STAY WELL YOUR MAJESTY"
    jump morningGo

label torielSchool:
    toriel "Papyrus!"
    papyrus "I CAME TO SEE IF YOU NEED HELP ON SOMETHING!"
    toriel "I don't know if I have something for you today Papyrus"
    toriel "The kids are running around the forest now"
    toriel "Maybe you can help us with the parts of the laboratory"
    papyrus "FROM THE LAB?"
    papyrus "MAYBE YOU SHOULD CALL SANS INSTEAD"
    papyrus "HE LOVES SCIENCE AFTER ALL!"
    toriel "It's just moving things around"
    toriel "Alphys is sorting the aparatus right now"
    toriel "She needs some muscle"
    toriel "And Undyne is with the kids right now"
    papyrus "BUT I DON'T HAVE A MUSCLE"
    toriel "..."
    toriel "Oh!"
    toriel "Don't worry, your bones are going to be a perfect replacement"
    papyrus "REALLY?!"
    papyrus "THEN THE GREAT PAPYRUS IS GOING TO HELP"
    papyrus "DOOOOCCCCTOOOOOORRRRR ALLLLLLLPHHYYYYYYSSSSSS!!!!!!"
    toriel "I'll better go to check as well"

##School Basement

    alphys "Yet another of this papers"
    alphys "I know that giant goat head is a determination extractor"
    alphys "But why it was built in the first place..."
    alphys "Why I never made that question before?"
    papyrus "DOCTOR ALPHYS!"
    alphys "Papyrus!"
    alphys "We already did our training this week!"
    papyrus "TORIEL TOLD ME YOU NEED HELP WITH MOVING AROUND SOME MACHINES"
    alphys "Oh"
    alphys "That"
    alphys "THAT"
    alphys "Ok..."
    toriel "What do you have there Alphys?"
    alphys "This?"
    alphys "It's nothing"
    alphys "It just some files with weird symbols"
    papyrus "WEIRD? DOESN'T LOOK WEIRD TO ME?"
    alphys "What are you talking about, Papyrus?"
    "Papyrus reads from the notes"
    papyrus "{font=fonts/NewAster.ttf} today i was supposed to make an annoucement to the king. {/font}"
    papyrus "{font=fonts/NewAster.ttf} but my assistant decided it was prank day or something. {/font}"
    papyrus "SOUNDS LIKE SANS TO ME, NYEHEHEH"
    alphys "You can read that?!"
    papyrus "IT'S JUST AN ACCENT"
    toriel "Like yours and Sans'?"
    papyrus "I GUESS?"
    alphys "I just this week I found tons and tons of papers with those symbols, everywhere!"
    alphys "And it's weird, because it's the first time I pay attention to them somehow"
    toriel "Maybe you just forgot!"
    alphys "That's kind of the only solution I have..."
    alphys "But how I'm going to forget piles of papers with..."
    alphys "symbols..."
    papyrus "LETTERS ARE SYMBOLS"
    alphys "You know what I'm talking about"
    papyrus "I'M NOT??"
    toriel "It's ok Alphys, you can sort this next week"
    toriel "Then we'll ask Papyrus and maybe Sans to help you out with those papers"
    alphys "I guess you right"
    "Toriel and Alphys leaves"
    papyrus "MMMMMM..."
    "Papyrus read the note again"
    papyrus "{font=fonts/NewAster.ttf} i decided that maybe he feels alone. {/font}"
    papyrus "{font=fonts/NewAster.ttf} maybe, he needs some company.{/font}"
    papyrus "{font=fonts/NewAster.ttf} i shall make him a brother, maybe.{/font}"
    papyrus "?!"
    papyrus "{font=fonts/NewAster.ttf} i'll analyse that in the morning.{/font}"
    papyrus "I THINK I JUST READ QUITE ENOUGH"

    if resets > 2 and not papersPapyrusCreation:
        papyrus "..."
        papyrus "{font=fonts/NewAster.ttf} i spoke to Sans about that idea this morning.{/font}"
        papyrus "I KNEW IT"
        papyrus "{font=fonts/NewAster.ttf} he seems stoked. i can hardly blame him.{/font}"
        papyrus "{font=fonts/NewAster.ttf} i never had a brother myself, and staying always with an old skeleton like me is not something a young lad must look forward everyday.{/font}" 
        papyrus "{font=fonts/NewAster.ttf} i also asked if he had a good name for him.{/font}"
        papyrus "{font=fonts/NewAster.ttf} he asks me why. i forgot i never told him.{/font}"
        papyrus "{font=fonts/NewAster.ttf} but after explain to him, i think he got a great name.{/font}"
        papyrus "..."
        papyrus "I NEED TO TALK ABOUT THIS WITH SANS"
        papyrus "BUT WHEN?"
        $ papersPapyrusCreation = True
    
label morningGo:
    if fromDay == 3:
        jump forest
