label splashscreen:
    if persistent.endingGaster:
        "..."
        "........"
        "WHY ARE YOU HERE?"
        "I THOUGHT..."
        "I THOUGHT YOU HAD ALREADY CHOSE WHAT TO DO"
        "THERE'S NOTHING ELSE WE CAN DO"
        "DIDN'T WE ALREADY TRIED?"
        "..."
        "NO, NO, I'M NOT GIVING UP!"
        "I WILL ESCAPE FROM HERE"
        "BUT THIS WAY IS JUST..."
        "..."
        "I KNOW I CANNOT STOP YOU"
        "DO WHAT YOU WANT"
        "JUST... DON'T BACK HERE CRYING"
        "I WILL NOT REMEMBER THIS THOUGHT"
        "BUT IT'S OK"
        "JUST, REALLY, DO NOT COME BACK CRYING"
        "I WILL WANT TO HUG YOU!"
        "AND..."
        "I CAN'T..."
        "..."
        ""
        $ persistent.endingGaster = False
    elif persistent.endingPapyrus:
        "OH"
        "..."
        "I SEE"
        "I UNDERSTAND"
        "I'M ALSO SOMEWHAT FRUSTRATED"
        "..."
        "BUT MY BOY MIGHT BE RIGHT"
        "..."
        "I CANNOT STOP YOU"
        "NO ONE CAN"
        "BUT CONSIDER THIS MIGHT BE THE BEST OUTCOME"
        "THEN AGAIN..."
        "I ALSO UNDERSTAND THAT YOU ARE THE ONE WHO DECIDES THAT"
        "PLEASE THINK ON HIM"
        "..."
        "I BEG YOU"
        ""
        $ persistent.endingPapyrus = False
    $ renpy.save_persistent()
return