label endingsFirstTry:
    papyrus "ARE THE WEKUFES GONE?"
    gaster "YES, THEY ARE"
    gaster "I CANNOT FIND ANY, MOST PROBABLY THEY ARE GONE"
    papyrus "IT'S TIME TO SET THIS ON!"
    "*Papyrus puts the pendrive in the Computer and fire it off*"
    papyrus "IT'S GOING TO TAKE A COUPLE OF MINUTES TO LOAD"
    papyrus "ARE YOU EXCITED?!"
    gaster "I CANNOT SHAKE THIS FEELING WE ARE FORGETING SOMETHING"
    papyrus "DO YOU WANT TO STOP THE PROCESS?"
    gaster "NO, NO"
    gaster "I MIGHT BE JUST PARANOID"
    papyrus "WHAT DO YOU THINK IS GOING TO HAPPEN WHEN YOU COME BACK?"
    papyrus "PEOPLE WILL REMEMBER YOU, LIKE YOU WERE NEVER GONE?"
    papyrus "I'LL REMEMBER EVERYTHING ABOUT SCIENCE?"
    gaster "I'LL BLOW UP IN MILLIONS OF SMALL PIECES AND I'LL COVER ALL THE BUILDINGS OF THE NEW MONSTERS KINGDOM IN A WHITE POWDER?"
    papyrus "GASTER!"
    gaster "IT'S BETWEEN THE REALM OF POSSIBILITY"
    papyrus "NOW I'M FINISHING DEALING WITH SANS'S LAZINESS, I'LL HAVE TO DEAL WITH YOUR NEGATIVENESS?"
    gaster "IS IT THAT A WORD?"
    gaster "..."
    gaster "WELL, I TOLD YOU, I'M A BIT PARANOID AT TIMES"
    papyrus "NYEH.."
    papyrus "I CANNOT WAIT FOR THAT!"
    gaster "MY DEAR PAPYRUS..."
    sans "this is the lab i told you about"
    papyrus "SANS?"
    gaster "LET'S ME SEE..."
    "* Scene changes to Sans and Frisk walking on the corridor of the Wekufes lab *"
    frisk "You sure they are here..."
    sans "i'm not sure if papyrus is with someone"
    sans "i just know papyrus came here"
    sans "and that i know that voice..."
    frisk "Someone you knew from before?"
    sans "a... friend..."
    frisk "Is it their name..."
    frisk "Gaster?"
    sans "how do you know that?"
    frisk "I found a monster"
    frisk "In greyscale"
    frisk "Who commented me about it"
    sans "oh..."
    frisk "I think it was a malfunction..."
    sans "on reality?"
    frisk "..."
    frisk "Yeah..."
    sans "well.."
    sans "we better found them"
    sans "papyrus has been very weird lately"
    frisk "Did you noticed?"
    sans "ehh..."
    sans "i thought it was just him been him"
    sans "he always does weird stuff..."
    frisk "I don't think so.."
    sans "wait..."
    sans "frisk..."
    "* Scene goes back to Gaster and Papyrus *"
    gaster "THEY ARE SANS AND THE FALLEN HUMAN"
    papyrus "THEIR NAME IS FRISK"
    papyrus "WAIT"
    papyrus "WHY AM I GETTING UPSET AT YOU CALLING FRISK FALLEN HUMAN?"
    papyrus "AND WHY DO YOU NOT CALL THEM BY THEIR NAME?"
    gaster "YOU ARE ALREADY GETTING SOME OF YOUR MEMORY BACK"
    gaster "IT'S NOT CONVENIENT FOR ME, BUT MEMORY IS MEMORY"
    papyrus "IT HAS FINISHED LOADING!"
    gaster "WE MUST DECIDE IF WE CONTINUE"
    gaster "DO WE?"
    jump endingMenuFirstTry

label endingMenuFirstTry: 
    menu:
        "Of Course!":
            $ firstTry = False
            jump startEndingGasterFirstTry
        "I have 2nd thoughts":
            jump resetOrEndingFirstTry

label startEndingGasterFirstTry:
    papyrus "OF COURSE!"
    papyrus "LET'S DO THIS!"
    gaster "smiles"
    papyrus "I PRESS ENTER!"
    gaster "AND NOW WE..."
    "fades to white"
    "shows Gaster back to normal, AKA, not half melting. He's as tall as papyrus, with a black suit and a white turtle neck"
    "he still has the cracks in his skull, cannot emote in one of his eyes and has missing the ring finger in both of his hands"
    gaster "IT WORKED"
    gaster "IT WORKED PAPYRUS!"
    gaster "..."
    gaster "PAPYRUS!"
    "shows Papyrus how Gaster was at the beginning. Half melted, somewhat deformed, but still with his smile plastered in his face"
    papyrus "I THINK THERE'S SOMETHING WE DIDN'T ACCOUNT FOR"
    gaster "OH... NO..."
    papyrus "IF YOU ASK ME..."
    papyrus "I THINK WE NEED TO LEARN MORE..." 
    papyrus "ABOUT..." 
    papyrus "WHAT..." 
    papyrus "IS BEYOND..." 
    papyrus "THE DARKNESS..."
    gaster "THERE'S NOTHING WE CAN COMPREHEND FROM THERE"
    papyrus "I REFUSE THAT STATEMENT!"
    gaster "IT DOESN'T HAVE TO BE YOU"
    "*steps*"
    gaster "THE SYSTEM SAYS THERE'S SOME DETERMINATION LEFT"
    gaster "WE CAN RESET TO TRY AGAIN!"
    papyrus "THAT'S NOT AN OPTION WE CAN TAKE"
    gaster "I KNOW..."
    gaster "BUT PLEASE, SHOW THEM THE MENU..."
    gaster "THEY MIGHT WANT TO TRY"
    menu:
        "Reset":
            gaster "OH, THANKS YOU!"
            gaster "WE WILL TALK IN THE PAST, MY DEAR PAPYRUS..."
            papyrus "..."
            $ resets = resets + 1
            jump day1
        "Continue":
            gaster "NO..."
            papyrus "DO NOT WORRY ABOUT ME!"
            papyrus "YOU..." 
            papyrus "WILL..." 
            papyrus "FIND..." 
            papyrus "A..."
            gaster "WHAT IF I DON'T?"
            gaster "WHAT IF I DIE AND YOU ARE STILL TRAPPED IN THE DARKNESS!?"
            papyrus "I KNOW YOU'LL DO YOUR BEST..."
            gaster "WHAT IS IT NOT GOOD ENOUGH?!"
            papyrus "..."
            papyrus "YOU WORRY TOO MUCH"
            papyrus "I'M NOT OK WITH THIS"
            papyrus "BUT I..." 
            papyrus "CAN HANDLE IT"
            papyrus "I WILL HANDLE IT!"
            gaster "I KNOW YOU ARE STRONG PAPYRUS"
            gaster "WHAT I DON'T KNOW IF I AM AS STRONG AS YOU ARE"
            papyrus "YOU HAVE ALREADY DONE THIS!"
            papyrus "WHY ARE YOU ASKING?!"
            frisk "Papyrus!?"
            " * Frisk and Sans appear in front of them. Frisk looks at Papyrus concerned and runs to him. Sans is paralyzed. *"
            frisk "What's happened to you?"
            frisk "What you did to him!?"
            papyrus "HE WAS TRAPPED IN THE DARKNESS"
            papyrus "WE GOT HIM..."
            papyrus "OUT.."
            gaster "BUT IT SEEMS IT NEEDS A MONSTER FOR SOME REASON"
            gaster "SO, PAPYRUS HAS TOOK MY PLACE"
            gaster "BY ACCIDENT"
            dtSans "That's why you are here?"
            dtSans "That what you were doing?"
            papyrus "YES, I DIDN'T TELL YOU..."
            papyrus "I THOUGHT WOULD BE..."
            papyrus "USELESS..."
            papyrus "I GUESS..."
            gaster "THE LOOP WAS TOO SHORT"
            gaster "IT WASN'T FEASIBLE"
            sans "But... at least..."
            papyrus "NOT FOR LONG"
            papyrus "FRISK!"
            papyrus "PLEASE TAKE CARE OF THIS BONEHEADS"
            frisk "Why are you saying that?"
            gaster "THE COMPUTER!"
            gaster "I FORGOT THE COMPUTER!"
            papyrus "PLEASE, MAKE SURE SANS DOES NOT LAZY AROUND TOO MUCH"
            papyrus "AND TAKE THE W.D. IN A TRIP BEFORE ANYTHING"
            papyrus "HE NEEDS TO SEE THE SURFACE BEFORE LOCKING HIMSELF IN A LAB"
            frisk "Sure"
            frisk "And then we will get you out of there, right?"
            papyrus "EXACTLY"
            papyrus "YOU ALWAYS GET..."
            "* Papyrus dissapear out of thin air*"
            frisk "What happened?"
            gaster "THE COMPUTER WAS PROGRAMMED TO FRY ITSELF"
            gaster "WITHOUT THIS COMPUTER, THERE'S NO WAY WE CAN COMMUNICATE WITH PAPYRUS ANY LONGER"
            dtSans "That... means..."
            dtSans "..."
            dtSans "..."
            gaster "SANS... MY DEAR BOY..."
            gaster "LET'S GO BACK"
            gaster "WE HAVE A LOT TO THINK AND CRY BEFORE ANYTHING"
            jump neutralEndingGaster
            
    
label resetOrEndingFirstTry:
    papyrus "WHY IS THAT OPTION THERE?"
    gaster "DO YOU NOT HAVE 2ND THOUGHTS?"
    papyrus "I MEAN..."
    papyrus "I SHOULD TRUST EVERYTHING IS GOING TO BE ALRIGHT"
    papyrus "RIGHT?"
    gaster "I DON'T KNOW"
    papyrus "HOW YOU DO IT?"
    gaster "I ALWAYS HAVE 2ND THOUGHTS"
    gaster "I MOSTLY IGNORE THEM OR ELSE I WILL GET NOTHING DONE"
    papyrus "SO..."
    papyrus "IT SEEMS WE CANNOT TRUST ANY OF OUR METAPHORICAL GUTS"
    gaster "I KNOW IT JUST GOING TO DEPEND ON WHAT IS BEYOND OUR COMPREHENSION"
    papyrus "YOU MEAN"
    gaster "EXACTLY"
    gaster "THEY ARE ALL POWERFULL AND ALL CURIOUS AFTER ALL"
    menu:
        "Reset":
            papyrus "THEY WANT TO STILL POKE AROUND?"
            gaster "I SHALL NOT DELAY THIS ANY MORE"
            $ resetWithoutMeaning = True
            $ resets = resets + 1
            jump day1
        "Use the Program Anyway":
            papyrus "I DO NOT UNDERSTAND"
            gaster "NEITHER DO I BUT OK"
            gaster "FIRE THE PROGRAM AWAY!"
            jump startEndingGasterFirstTry
        "Do not use the Program":
            papyrus "..."
            papyrus "..."
            papyrus "..."
            papyrus "..."
            papyrus "..."
            papyrus "..."
            papyrus "WHO'S STOPING ME?"
            gaster "PAPYRUS?"
            gaster "WHAT ARE YOU DOING?"
            papyrus "I'M GOING TO FIRE THE PROGRAM!"
            gaster "THERE'S NO NEED PAPYRUS.."
            papyrus "SCREW THEIR CURIOSITY!"
            papyrus "I WILL NOT LET THEM KNOW WHAT'S GOING TO HAPPEN IF I CAN MANAGE IT"
            papyrus "NOW I HAVE THE POWER TO CHANGE SOMETHING FOR THE BETTER"
            papyrus "I WILL NOT LET AN ENTITLED"
            papyrus "BEING..." 
            papyrus "BEYOND..." 
            papyrus "THAT TO TOY WITH US!"
            gaster "I GUESS THERE'S NO WAY TO STOP YOU NOW"
            pause(1)
            gaster "FIRE THE PROGRAM AWAY!"
            jump startEndingGasterFirstTry
return 
