label neutralEndingPapyrus:
  "* Scene changes to near the Skelebros house. Monster Kid and his Dog friend are waiting for Papyrus *"
  kid "Where's he?"
  "Student" "* Maybe the teacher finally found him"
  kid "NO SENSE!"
  kid "Something terrible must have happened"
  "Student" "* He might be in trouble"
  kid "He..."
  kid "He might..."
  undyne "Here you are"
  undyne "Papyrus is not coming today"
  undyne "He called to tell me"
  kid "Is he in tr..."
  undyne "No..."
  undyne "He has... something else to do"
  "* Scene changes to the Wekufes Lab *"
  alphys "This place is big..."
  toriel "How did you found all of this?"
  papyrus "I WAS... RUNNING..."
  papyrus "WHEN I FOUND THIS PLACE"
  papyrus "ALL THE HILLS AROUND HERE HAVE, LIKE, OLD MONSTERS BUILDING"
  papyrus "SO I DECIDED TO EXPLORE... AND I FOUND THIS"
  alphys "Why didn't you tell us sooner?"
  papyrus "..."
  papyrus "I LITERALLY FOUND THIS YESTERDAY"
  alphys "Oh, I'm sorry!"
  alphys "I got confused"
  toriel "This is an old monsters building from the war"
  sans "But this technology is humans'"
return
