label neutralEndingPapyrus:
  "* Scene changes to near the Skelebros house. Monster Kid and his Dog friend are waiting for Papyrus *"
  monsterKid "Where's he?"
  "Student" "* Maybe the teacher finally found him"
  monsterKid "NO SENSE!"
  monsterKid "Something terrible must have happened"
  "Student" "* He might be in trouble"
  monsterKid "He..."
  monsterKid "He might..."
  undyne "Here you are"
  undyne "Papyrus is not coming today"
  undyne "He called to tell me"
  monsterKid "Is he in tr..."
  undyne "No..."
  undyne "He has... something else to do"
  "* Scene changes to the Wekufes Lab *"
  alphys "This place is big..."
  toriel "How did you found all of this?"
  papyrus "I WAS... RUNNING..."
  papyrus "WHEN I FOUND THIS PLACE"
  papyrus "ALL THE HILLS AROUND HERE HAVE, LIKE, OLD MONSTERS BUILDING"
  papyrus "SO I DECIDED TO EXPLORE... AND I FOUND THIS"
  alphys "Why didn't you tell us sooner?"
  papyrus "..."
  papyrus "I LITERALLY FOUND THIS YESTERDAY"
  alphys "Oh, I'm sorry!"
  alphys "I got confused"
  toriel "This is an old monsters building from the war"
  sans "but this technology is humans'"
  papyrus "IS IT?"
  alphys "It looks like some of our stuff, mostly because most of them are scraps from human garbage"
  toriel "I'm assuming most of this... machines were made by humans..."
  toriel "But I wonder if some of them have something to do with..."
  alphys "Oh..."
  alphys "Oh!"
  sans "it might..."
  sans "but all of this... looks..."
  alphys "Familiar, i know"
  alphys "But... it's a different way to do it..."
  toriel "What are you two trying to suggest?"
  sans "this looks just like a determination extractor"
  toriel "What?!"
  sans "in fact they have the extractor way over there"
  alphys "This tanks are massive though"
  alphys "They must have been extracting a lot of determination"
  toriel "So that why there kidnapped so many kids?"
  papyrus "EXCUSE ME?"
  toriel "The Dogs found a kid in the forest"
  toriel "The kid guided them to other kids in a cave"
  toriel "They did everything on their own, we just figure out what happened when they came back with a lot of humans kids"
  alphys "But why humans would need other humans to extract determination?"
  alphys "They have an unlimited amount of it, they could have extracted from themselves!"
  sans "and, if they were monsters instead..."
  sans "this was a very risky plan"
  sans "just one kid decides to fight back"
  sans "and all of them would be dead"
  papyrus "THEN THE WEKUFES WEREN'T HUMANS NEITHER MONSTERS!"
  "..."
  papyrus "..."
  toriel "Papyrus... can you come with me outside??"
  toriel "We... need to talk..."
  toriel "things..."
  papyrus "THIS WAS A TRAP, WASN'T IT?"
  toriel "That doesn't matter, just come with me"
  papyrus "AAAHHHHH..."
  "* Papyrus and Toriel step outside *"
  toriel "I'm assuming this is very important for you"
  toriel "But if this it's going to help us figure out what's going on here"
  toriel "I would like to know"
  "..."
  papyrus "I HAVE BEEN..."
  papyrus "TRAVELING IN TIME?"
  toriel "..."
  toriel "That sounds difficult to believe"
  toriel "But it's you"
  toriel "It's must be true"
  papyrus "REALLY?!"
  toriel "Of course!"
  toriel "I really want to know how that happened"
  papyrus "..."
  papyrus "OF COURSE"
  papyrus "I'LL TELL YOU"
  "* Fade to Black *"
  narrator ""
  narrator "THIS IS ALL I CAN SHOW YOU"
  narrator "THE DETERMINATION IS RUNNING LOW, IS BASICALLY GONE BY NOW"
  narrator "I HOPE THIS HAS BEEN SUFFICIENT FOR YOU"
  narrator "BECAUSE I DON'T KNOW HOW WE CAN..."
  narrator "WELL"
  narrator "THIS IS ALL I CAN DO NOW"
  narrator "FAREWELL"
  narrator ""
  stop music fadeout(1)
  pause(1.5)
  # $ renpy.set_return_stack([])
  $ renpy.quit()
return
