label neutralEndingGaster:
    frisk "Sans? SANS!"
    sans "oh, hello..."
    frisk "Have you been" 
    extend " crying?"
    sans "i did this a lot some years ago"
    sans "YAWN"
    sans "you? shouldn't you been at school?"
    frisk "You haven't go out of your room the last 2 weeks!"
    sans "great! nice to meet you"
    sans "now i'm going back to my hole"
    frisk "No, you are not doing that!"
    sans "you are not ok"
    frisk "..."
    frisk "I spoke to Undyne before coming here"
    sans "you shouldn't be doing that"
    frisk "It's like she got 3 times the mean spirit back"
    sans "it's seems her relationship with papyrus soften her a little"
    sans "at least has not affected her relationship with alphys"
    sans "papyrus would kick himself if that happened"
    frisk "Mom and Dad at least are been considerate, even if they don't know why you guys are so..."
    extend " away"
    sans "you shouldn't worry about us"
    sans "no matter what papyrus make you promise to him"
    frisk "I would be worried anyway"
    sans "fair point"
    sans "..."
    sans "ok then"
    sans "just let me take a pill for this headache and i will help you"
    frisk "I cannot get Gaster out of the basement!"
    sans "nobody can help you with that"
    sans "i can explain though why he is looking at you like he want to kill you"
    sans "because he really wants to"
    frisk "Mom sent a pie"
    sans "great. let's do that with some tea"
    "* Time Skip *"
    sans "well, since we skeletons are not born, but created, gaster was created for been part of the army at the tail end of the war against humans"
    sans "it was a couple of weeks after the last skeleton of the original tribe was erradicated"
    sans "but he was too weak to be of any use, so he was pulled back"
    frisk "He has survivor guilt"
    sans "you can call it that"
    frisk "He wants to kill me"
    sans "yes"
    "* sip *"
    sans "but he's not going to do that"
    sans "you are papyrus best friend, he knows that"
    frisk "How I get him out of the basement?"
    sans "i know i will never convince you it's impossible but at least let me finish my pie"
    "* Inside the Basement, Gaster was at the desk, papers and blueprints everywhere with him reading very carefully*"
    "* Sans and Frisk go in *"
    gaster "HOW YOU.."
    gaster "..."
    gaster "YOU TOOK A SHORTCUT"
    sans "nice to see you are still capable of critical thinking"
    gaster "I TOLD YOU SANS"
    gaster "1. YOU ARE NOT ALLOWED HERE UNLESS YOU FEEL ABLE TO COOPERATE WITH THE INVESTIGATION"
    gaster "AND 2. DON'T TAKE THE FALLEN HUMAN HERE"
    gaster "MAKE ME NERVIOUS"
    sans "their name is frisk"
    frisk "And you should be going out"
    gaster "I DON'T HAVE TIME FOR PLATITUDES"
    gaster "THERE'S NO RECORDS OF HOW LONG A SKELETON CAN LIVE, AND I HAVE BEEN ALIVE FOR MORE THAN 100 YEARS"
    gaster "I CAN PERFECTLY BECOME DUST TOMORROW AND NOT GET ANY CLOSER TO GET PAPYRUS OUT OF THE DARKNESS"
    frisk "You are not going to get any closer unless you clear your mind!"
    frisk "You need to... mourn"
    gaster "UH?"
    frisk "I asked my mom about it"
    frisk "That people need time to feel sad and accept that the world is never going to go back"
    frisk "She knows a thing or two about it"
    gaster "SHE DOES"
    frisk "She told me that I shouldn't worry about Sans and you too much"
    frisk "You were doing that..."
    gaster "YOU ALSO SHOULD BE DOING THAT"
    gaster "OK"
    gaster "BUT JUST A STROLL IN THE FOREST"
    frisk "Picnic time!"
    frisk "Mom sent a pie!"
    "* Frisk go out *"
    gaster "IS IT FOR PUTTING UNDER A BENCH?"
    sans "come on w.d."
    sans "you know you leave quiches under a bench"
    gaster "SANS"
    gaster "I HAVE NO IDEA IF WE CAN GET PAPYRUS OUT"
    gaster "I DON'T KNOW WHAT'S MISSING ON THE DARKNESS THAT NEEDS A MONSTER THERE, EVEN LESS HOW TO REPLACE IT"
    gaster "IT WASN'T THE DETERMINATION AT THE END"
    dtSans "Gaster"
    sans "let's try to live a good life while trying to get him out"
    sans "because if we don't and we get papyrus out"
    sans "he's going to get *REALLY* mad"
    sans "and that's something i don't wanna meet"
    sans "ever"
    gaster "IF YOU PUT IT THAT WAY"
    gaster "I GUESS THERE'S NOTHING ELSE I CAN DO, BUT COMPLY"
    scene black with dissolve
    nvl clear
    narrator "THIS IS AS FAR AS I CAN SHOW YOU"
    narrator "I KNOW IT'S NOT A HAPPY ENDING, BUT THEY ARE NOT LOSING HOPE YET!"
    narrator "AND KEEPING HOPE IS THE MOST DIFFICULT THING TO DO!"
    nvl clear
    narrator "I KNOW IT'S NOT A GREAT ENDING"
    nvl clear
    narrator "WE NEED TO MOVE ON"
    nvl clear
    narrator "I'M SORRY I CANNOT SHOW YOU EVEN MORE"
    narrator "THE DETERMINATION IS RUNNING OUT AND..."
    nvl clear
    narrator "I'M GOING TO BE OK"
    narrator "THANKS YOU FOR BEEN HERE"
    narrator "GO TO YOUR LIFE WITHOUT REGRETS!"
    narrator "YOU DID WHAT YOU COULD"
    narrator "AND THAT'S MORE THAN FINE"
    nvl clear
    narrator "THANK YOU"
    nvl clear
    ""
    return
