label weddingGaster:
  "* Knock knock *"
  frisk "..."
  frisk "Open the door up!"
  sans "..."
  frisk "Sans!"
  sans "frisk..."
  sans "i already told toriel, i'm not going to the wedding"
  frisk "No, Sans..."
  sans "i'm going to be more of an asshole than i'm already are, i don't wanna ruin it"
  frisk "No Sans, it's not about that"
  frisk "Alphys wants to talk with you"
  frisk "About the ring"
  sans "which ring?"
  alphys "The ring Undyne gave me for the wedding"
  alphys "I asked her from where she got it"
  alphys "And she said she didn't remember"
  alphys "I told that to Frisk and..."
  frisk "It was Papyrus!"
  sans "Of course it was Papyrus"
  sans "He probably half heard Undyne about it and used his savings in human money to get it"
  alphys "You have savings in human money"
  sans "that doesn't matter..."
  frisk "There's still some Papyrus around!"
  frisk "I remember him, you remember him, the ring it here!"
  sans "that's good news"
  sans "because his room is completely empty"
  alphys "How that happened?"
  sans "for a moment i thought it was just the ripple effect from him somehow dissapearing from existence"
  sans "but if the ring is there..."
  "..."
  "Sans goes to Papyrus room, but just find a note in at the floor"
  frisk "???"
  sans "it's a letter"
  sans "i guess from the people who somehow stole everything from his room"
  alphys "Why do you assume that?"
  sans "this is not papyrus' handwritting"
  "..."
  text "MY DEAR SANS"
  sans "..."
  sans "gaster?"
  alphys "Is it from Dr. Gaster?"
  alphys "He took the stuff that was supposed to be there?"
  frisk "How do you..."
  sans "..."
  sans "i guess i can tell to you two"
  frisk "Seriously?!"
  alphys "About what?"
  sans "but you have to promise me you are going to believe me"
  frisk "Of course!"
  alphys "..."
  alphys "Fine..."
  sans "well..."
  scene black with dissolve
  nvl clear
  narrator "THAT'S ALL I CAN SHOW YOU"
  narrator "REALLY! THERE'S NO MORE I CAN SHOW YOU"
  narrator "I HAD SOME DETERMINATION LEFT, BUT I JUST USED UP ALMOST EVERYTHING"
  narrator "..."
  narrator "I'M SORRY ABOUT THIS"
  narrator "BUT I DON'T KNOW HOW TO CONTINUE DIFFERENTLY!"
  narrator "I KNOW THEY WILL BE ALRIGHT"
  narrator "I'M JUST..."
  narrator "..."
  narrator "EVERYTHING IS GOING TO BE OK!"
  narrator "JUST HANG IN THERE!"
  narrator "I'LL BE... TOO..."
  nvl clear
  ""
  stop music fadeout(1)
  pause(1.5)
  # $ renpy.set_return_stack([])
  $ renpy.quit()
return