label weddingPapyrus:
  "Papyrus appears at the altar after the ceremony, dressed for the moment"
  papyrus "THIS WAS GREAT!"
  undyne "Yes, despite everything we couldn't put in"
  papyrus "IT WAS REALLY GREAT!"
  undyne "..."
  undyne "Yes, you right..."
  undyne "I was about to forget my vows though..."
  papyrus "YOU HANDLE IT LIKE A PRO"
  undyne "..."
  undyne "Talk with you make me feel better"
  papyrus "NO TIME FOR THAT"
  papyrus "NOW IT'S TIME FOR THROWING THE BRIDAL BOUQUET!"
  undyne "Oh, right!"
  undyne "I'm going to throw it directly to Sans!"
  "* THUMP! *"
  papyrus "THAT'S NOT HOW THAT SHOULD BE"
  frisk "It's her wedding"
  papyrus "THAT'S AN EXCELENT POINT"
  sans "which was the idea behind this?"
  papyrus "THAT YOU ARE GOING TO BE THE NEXT TO BE MARRIED!"
  alphys "I tried to explain her that's not how it works, but she doesn't listen!"
  sans "nah.."
  sans "i'm going to let her have this one"
  "..."
  sans "wanna go?"
  papyrus "I GUESS SO..."
  papyrus "..."
  papyrus "YEAH, WE SHOULD REALLY GO"
  alphys "Are you sure you wanna do this alone you guys?"
  papyrus "YOU STILL DO NOT HAVE YOUR SCIENCE LICENSE BACK!"
  alphys "Oh... come on!"
  papyrus "BUT PROBABLY WE'RE GOING TO SEND YOU STUFF FOR A 2ND OPINION ANYWAY, BECAUSE I'M JUST LEARNING"
  sans "plus, something will blow up"
  sans "i assure you"
  undyne "Good"
  undyne "I'll remember to visit you when I hear an explosion in the distance"
  metatton "What?!"
  metatton "Are you moving away?"
  metatton "Why?"
  papyrus "WE HAVE... FAMILY TRAPPED IN THE MIDDLE OF REALITY, SO TO SPEAK"
  sans "i don't have much faith honestly"
  sans "but there's something new papyrus discovered and..."
  sans "we're going to try out..."
  metatton "What?!"
  metatton "But are you staying for the waltz, right?"
  papyrus "I FORGOT THE WALTZ!"
  "Papyrus run away"
  frisk "It's not that far away"
  frisk "We can go visit them"
  metatton "That's a marvelous idea"
  "Papyrus comes back"
  papyrus "THE WALTZ!"
  "Everybody goes away"
  scene black with dissolve
  nvl clear
  narrator "THEY SEEM TO BE FINE"
  narrator "THEY ARE GOING FORWARD, DESPITE THE FACT WE FAILED"
  narrator "I HOPE IT'S ENOUGH FOR YOU"
  narrator "BECAUSE THERE'S NOT ENOUGH DETERMINATION NOW"
  narrator "OUR CONNECTION WILL STOP"
  narrator "BUT THEY ARE MOVING FORWARD AND..."
  narrator "..."
  narrator "I WOULD LIKE TO STAY THAT WAY"
  narrator "PLEASE..."
  nvl clear
  ""
  stop music fadeout(1)
  pause(1.5)
  # $ renpy.set_return_stack([])
  $ renpy.quit()
return