label wekufeEndingGaster:
  "* Gaster is in the lab, Cuero appears behind him *"
  cuero "You were the anomaly"
  cuero "And you used that monster to get out"
  gaster "THAT WASN'T INTENTIONAL"
  cuero "It is difficult for me to believe that"
  cuero "But I guess, for a monster, me believing you is not one of your concerns"
  gaster "ACTUALLY"
  gaster "IT IS"
  gaster "BECAUSE I NEED TO GET HIM OUT"
  cuero "Then go with your people"
  cuero "You have your own soul and your own body"
  cuero "I'm sure you are going to be fine"
  gaster "I MIGHT"
  gaster "BUT THEY WILL JUST SLOW ANY PROGRESS I CAN MAKE"
  gaster "I WANT TO OFFER YOU A DEAL"
  gaster "I HAVE VAST KNOWLEDGE OF 'DETERMINATION'"
  gaster "EVERYTHING WE COULD SAVE FROM CENTURIES OF MONSTER SCIENCE"
  gaster "THAT MIGHT BE OF INTEREST FOR YOU"
  cuero "What do you want from us?"
  gaster "WELL..."
  "* Scene changes to outside the Skelebros house, where Sans is meeting Frisk *"
  frisk "Do you remember him, right?"
  sans "who?"
  frisk "Papyrus!"
  frisk "I was trying to call him, but it's not in my contacts anymore"
  frisk "I asked my mom, and she said she doesn't know any Papyrus"
  sans "what?"
  sans "but..."
  "* Sans decides to call Undyne *"
  undyne "Hello?"
  sans "it's me sans"
  sans "quick question: is papyrus around there? anywhere?"
  undyne "Who's Papyrus?"
  frisk "You taught him how to cook!"
  frisk "He jumps out of the windows every single time he's nervious"
  undyne "Never heard of him"
  "..."
  undyne "Sans? Are you still there?"
  undyne "Alphys is asking if Dr. Gaster is around there, she has a question for him"
  "..."
  undyne "Sans?"
  "* Sans hangs the phone *"
  frisk "Sans?"
  sans "how they know about the old bones?"
  sans "this makes no sense... unless..."
  frisk "What it's happening Sans?"
  "* Coo appears next to them with a letter *"
  coo "I have a letter for you"
  sans "who are you?"
  coo "It's from your father"
  "..."
  frisk "Sans'... dad?"
  coo "With this my job is done"
  sans "wait!"
  frisk "They's gone"
  text "MY DEAR SANS:"
  frisk "What with those symbols?"
  sans "it's just an accent"
  text "I'M SURE YOU ARE ASKING YOURSELF WHAT IT'S HAPPENING"
  text "AND WHILE I DON'T KNOW IF YOU ARE ABLE TO REMEMBER YOUR YOUNGER BROTHER PAPYRUS"
  text "MY STAMP IN THE WORLD AND THE MEMORIES ABOUT MYSELF SHOULD BE COMING BACK"
  text "SADLY, I WILL NOT"
  text "IF IT WERE JUST FOR ME, I WOULD PROBABLY NEVER SEND YOU A LETTER"
  text "BUT I'M SURE YOUR BROTHER BELIEVES YOU DESERVE AT LEAST TO KNOW WHAT HAPPENED TO HIM"
  text "HE..."
  text "HE HAS SACRIFICED HIMSELF SO I COULD COME BACK TO THIS DIMENSION"
  text "AND THAT'S WHY I CANNOT GO BACK"
  text "HE ALSO SAID, PLEASE, LIVE THE BEST LIFE YOU CAN"
  text "I'LL DO THE WORK TO BRING HIM BACK"
  "..."
  frisk "Sans?"
  frisk "We need to do something..."
  frisk "Right?"
  frisk "Sans?"
  sans "i..."
  sans "i didn't realize that something was happening..."
  sans "this..."
  sans "this went out of my radar..."
  sans "how?"
  sans "i..."
  sans "i..."
  dtSans "I should have known..."
  frisk "Sans, that doesn't matter anymore!"
  frisk "We need to do something now!"
  frisk "Sans?"
  toriel "Here you are"
  toriel "Sans?"
  toriel "Are you... ok?"
  frisk "He's not"
  frisk "Ah..."
  frisk "Can I..."
  sans "oh..."
  sans "sure..."
  toriel "Oh..."
  toriel "This is Gaster terrible handwritting"
  toriel "I barely can make up what it's written"
  frisk "It says he's leaving"
  frisk "That he needs to get Papyrus"
  toriel "Do you mean the friend you were asking about this morning?"
  toriel "The one I don't know"
  sans "tori..."
  sans "he's my brother"
  toriel "uh?"
  toriel "There's something here I... "
  extend "haven't been inform?"
  sans "i have something to tell you..."
  sans "both of you..."
  scene black with dissolve
  nvl clear
  pause(3)
  narrator "THIS IS AS FAR AS I CAN SHOW YOU"
  narrator "..."
  narrator "YES... I DON'T LIKE THIS EITHER"
  nvl clear
  narrator "BUT"
  narrator "THERE'S SOMETHING POSITIVE TO SAY!"
  narrator "I KNOW!"
  nvl clear
  narrator "WE NEED TO MOVE ON"
  nvl clear
  narrator "I'M SORRY I CANNOT SHOW YOU EVEN MORE"
  narrator "THE DETERMINATION IS RUNNING OUT AND..."
  nvl clear
  narrator "I'M GOING TO BE OK"
  narrator "ANYTHING THAT CAN HAPPENS FROM THIS POINT FORWARD"
  narrator "WE CAN'T DO ANYTHING ABOUT IT"
  narrator "I HOPE YOU CAN COMPREHEND"
  nvl clear
  narrator "THANK YOU"
  nvl clear
  ""
  stop music fadeout(1)
  pause(1.5)
  # $ renpy.set_return_stack([])
  $ renpy.quit()
return
