label wekufeEndingGaster:
  "* Gaster is in the lab, Cuero appears behind him *"
  "Monster 1" "* You were the anomaly"
  "Monster 1" "* And you used that monster to get out"
  gaster "THAT WASN'T INTENTIONAL"
  "Monster 1" "* It is difficult for me to believe that"
  "Monster 1" "* But I guess, for a monster, me believing you is not one of your concerns"
  gaster "ACTUALLY"
  gaster "IT IS"
  gaster "BECAUSE I NEED TO GET HIM OUT"
  "Monster 1" "* Then go with your people"
  "Monster 1" "* You have your own soul and your own body"
  "Monster 1" "* I'm sure you are going to be fine"
  gaster "I MIGHT"
  gaster "BUT THEY WILL JUST SLOW ANY PROGRESS I CAN MAKE"
  gaster "I WANT TO OFFER YOU A DEAL"
  gaster "I HAVE VAST KNOWLEDGE OF 'DETERMINATION'"
  gaster "EVERYTHING WE COULD SAVE FROM CENTURIES OF MONSTER SCIENCE"
  gaster "THAT MIGHT BE OF INTEREST FOR YOU"
  "Monster 1" "* What do you want from us?"
  gaster "WELL..."
  "* Scene changes to outside the Skelebros house, where Sans is meeting Frisk *"
  frisk "Do you remember him, right?"
  sans "who?"
  frisk "Papyrus!"
  frisk "I was trying to call you, but it's not in my contacts anymore"
  frisk "I asked my mom, and she said she doesn't know any Papyrus"
  sans "what?"
  sans "but..."
  "* Sans decides to call Undyne *"
  undyne "Hello?"
  sans "it's me sans"
  sans "quick question: is papyrus around there? anywhere?"
  undyne "Who's Papyrus?"
  frisk "You taught him how to cook!"
  frisk "He jumps out of the windows every single time he's nervious"
  undyne "Never heard of him"
  "..."
  undyne "Sans? Are you still there?"
  undyne "Alphys is asking if Dr. Gaster is around there, she has a question for him"
  "..."
  undyne "Sans?"
  "* Sans hangs the phone *"
  frisk "Sans?"
  sans "how they know about the old bones?"
return
