label afternoonToriel:
  papyrus "I WANT TO TALK TORIEL ABOUT SOMETHING..."
  papyrus "..."
  papyrus "HEY, GASTER... CAN YOU... NOT HEAR WHAT I WANT TO TALK WITH HER?"
  gaster "IT'S ABOUT ME?"
  papyrus "MAYBE??"
  gaster "THAT'S A TRICKY SITUATION YOU ARE PUTTING ME THERE, PAPYRUS"
  papyrus "COME ON, REALLY, I NEED SOME PRIVACY ON THIS ONE"
  gaster "THEN GO"
  papyrus "OK"
  papyrus "BUT DO NOT PEEK!"
  "* Papyrus leaves *"
  gaster "MY SWEET CHILD"
  "* Scene changes to Toriel's house *"
  toriel "Papyrus!"
  toriel "Nice to meet you"
  papyrus "HOW'S EVERYTHING GOING?"
  papyrus "HOW'S FRISK HANDLING EVERYTHING?"
  toriel "They are fine"
  if day == 2:
    toriel "They are sleeping after what happened yesterday"
  else:
    toriel "They are sleeping after what happened that day"
  toriel "But I think they'll be fine"
  papyrus "GREAT!"
  papyrus "..."
  papyrus "OH!"
  papyrus "I NEED TO ASK YOU SOMETHING"
  toriel "Oh?"
  toriel "And what it could be?"
  papyrus "I WAS THINKING YOU COULD GIVE ME A CLUE ABOUT..."
  papyrus "WELL..."
  toriel "Ahh..."
  toriel "Come on, tell me"
  papyrus "WHY SANS AND I ARE THE ONLY SKELETONS AROUND?"
  toriel "Oh!"
  toriel "Oh...."
  pause(3)
  papyrus "ARE YOU OK?"
  toriel "It's just..."
  toriel "I should know..."
  toriel "But..."
  toriel "I'm having trouble recolecting memories..."
  toriel "How odd..."
  papyrus "I REALLY DON'T WANNA BOTHER YOU..."
  toriel "It's not a bother..."
  toriel "..."
  toriel "You stay with Frisk, I'm going to the library to pick up the complete version of the History Encyclopedia written by Gerson"
  papyrus "DON'T YOU HAVE A VERSION RIGHT HERE?"
  toriel "I have the abridged version because is smaller"
  toriel "But I need to read everything now, because it seems I'm losing my memory"
  toriel "I'm getting too old"
  papyrus "I DON'T THINK IS THAT"
  toriel "You are so nice"
  papyrus "PLUS, I THINK THEY DIGITIZED THE BOOK LIKE 1 YEAR AGO?"
  toriel "Really?"
  "* Toriel and Papyrus are in front of a computer checking out the Monster's History Wiki *"
  toriel "This is not the book, it's just a transcript"
  papyrus "OH, YES, YES"
  papyrus "BUT IT'S SEARCHEABLE"
  toriel "Oh, I see"
  toriel "Let's search 'Skeleton Tribe History'"
  "..."
  "..."
  "..."
  toriel "You knew that, correct?"
  papyrus "OH? YES... YES..."
  papyrus "I WANTED TO KNOW IF YOU KNEW SOMETHING ELSE..."
  toriel "I told everything I knew about everything to Gerson all those times ago"
  toriel "Why should you think I know something is not written there?"
  papyrus "WEELL....."
  toriel "Papyrus..."
  papyrus "..."
  toriel "Look, when we got trapped in the underground, some of us decided to get busy and write everything we could remember about Monsters Culture"
  toriel "History, Science, everything inbetween"
  toriel "And everything that happened while we were trapped"
  toriel "If something as important as a new skeleton created by another kind monster happened, it must be there"
  papyrus "IS IT REALLY THAT IMPORTANT?"
  toriel "Of course Papyrus"
  toriel "But..."
  toriel "The only thing we are sure is that you guys aren't the first"
  toriel "So..."
  toriel "Why I cannot remember..."
  toriel "You stay with Frisk, I'm going to the library"
  papyrus "OH, OF..."
  "*SLAM*"
  papyrus "SHE'S GONE"
  "*SCENE FADE TO BLACK*"
  pause(5)
  "*Scene fade to Toriel's house, Frisk and Papyrus are playing video games*"
  toriel "I'm back"
  frisk "Good"
  frisk "Because Papyrus is kicking my ass in Smash"
  papyrus "IT IS UNDYNE FAULT"
  papyrus "IT WAS THAT OR A FIGHT IN THE FOREST ONCE A MONTH"
  papyrus "AND I HAVE TO BE GOOD, OR ELSE SHE WILL TOTALLY AMBUSH ME"
  toriel "I'm going to talk with Undyne about this tomorrow"
  papyrus "..."
  papyrus "HOW WAS THE TRIP TO THE LIBRARY"
  toriel "Terrible"
  toriel "The original draft of the encyclopedia got almost all the content about skeletons after the genocide of the original skeleton tribe vandalized"
  toriel "And nobody realized until now"
  frisk "Genocide?"
  toriel "It's something that happened during the War against humans"
  toriel "All the skeletons were erradicated because..."
  toriel "Bad battle tactics"
  toriel "But my issue goes that everything between that and, Sans and Papyrus should be written on the original draft of Gerson's encyclopedia"
  toriel "But somebody went and erased everything"
  toriel "And the complete science encyclopedia"
  papyrus "WHAT?"
  toriel "I asked if they could checkout the science encyclopedia that should exist"
  toriel "But the documents that should be the science encyclopedia are blank papers"
  toriel "And there's almost no books about science in the library"
  papyrus "AND NOBODY REALIZED UNTIL NOW?"
  toriel "Exactly"
  frisk "Then how Alphys or Sans know anything about science?"
  toriel "I'm guessing this happened fairly recently, but the fact we're realizing just now is really suspicious"
  toriel "In any case, next week we're going to have a meeting in the library to see what we're going to do"
  toriel "I'm sorry Papyrus I don't have answers for your question"
  papyrus "IT'S OK"
  $ gasterScienceEncyclopedia = True
return
