label afternoonToriel
  papyrus "I WANT TO TALK TORIEL ABOUT SOMETHING..."
  papyrus "..."
  papyrus "HEY, GASTER... CAN YOU... NOT HEAR WHAT I WANT TO TALK WITH HER?"
  gaster "IT'S ABOUT ME?"
  papyrus "MAYBE??"
  gaster "THAT'S A TRICKY SITUATION YOU ARE PUTTING ME THERE, PAPYRUS"
  papyrus "COME ON, REALLY, I NEED SOME PRIVACY ON THIS ONE"
  gaster "THEN GO"
  papyrus "OK"
  papyrus "BUT DO NOT PEEK!"
  "* Papyrus leaves *"
  gaster "MY SWEET CHILD"
  "* Scene changes to Toriel's house *"
  toriel "Papyrus!"
  toriel "Nice to meet you"
  papyrus "HOW'S EVERYTHING GOING?"
  papyrus "HOW'S FRISK HANDLING EVERYTHING?"
  toriel "They are fine"
  $ if day == 2:
    toriel "They are sleeping after what happened yesterday"
  $ else:
    toriel "They are sleeping after what happened that day"
  toriel "But I think they'll be fine"
  papyrus "GREAT!"
  papyrus "..."
  papyrus "OH!"
  papyrus "I NEED TO ASK YOU SOMETHING"
  toriel "Oh?"
  toriel "And what it could be?"
  papyrus "I WAS THINKING YOU COULD GIVE ME A CLUE ABOUT..."
  papyrus "WELL..."
  toriel "Ahh..."
  toriel "Come on, tell me"
  papyrus "WHY SANS AND I ARE THE ONLY SKELETONS AROUND?"
  toriel "Oh!"
  toriel "Oh...."
  pause(3)
  papyrus "ARE YOU OK?"
  toriel "It's just..."
  toriel "I should know..."
  toriel "But..."
  toriel "I'm having trouble recolecting memories..."
  toriel "How odd..."
  papyrus "I REALLY DON'T WANNA BOTHER YOU..."
  toriel "It's not a bother..."
  toriel "..."
  toriel "You stay with Frisk, I'm going to the library to pick up the complete version of the History Encyclopedia written by Gerson"
  papyrus "DON'T YOU HAVE A VERSION RIGHT HERE?"
  toriel "I have the abridged version because is smaller"
  toriel "But I need to read everything now, because it seems I'm losing my memory"
  toriel "I'm getting too old"
  papyrus "I DON'T THINK IS THAT"
  toriel "You are so nice"
  papyrus "PLUS, I THINK THEY DIGITIZED THE BOOK LIKE 1 YEAR AGO?"
  toriel "Really?"
  "* Toriel and Papyrus are in front of a computer checking out the Monster's History Wiki *"
  toriel "This is not the book, it's just a transcript"
  papyrus "OH, YES, YES"
  papyrus "BUT IT'S SEARCHEABLE"
  toriel "Oh, I see"
  toriel "Let's search 'Skeleton Tribe History'"
  "..."
  "..."
  "..."
  toriel "You knew that, correct?"
  papyrus "OH? YES... YES..."
  papyrus "I WANTED TO KNOW IF YOU KNEW SOMETHING ELSE..."
  toriel "I told everything I knew about everything to Gerson all those times ago"
  toriel "Why should you think I know something is not written there?"

return
