label afternoonToriel
  papyrus "I WANT TO TALK TORIEL ABOUT SOMETHING..."
  papyrus "..."
  papyrus "HEY, GASTER... CAN YOU... NOT HEAR WHAT I WANT TO TALK WITH HER?"
  gaster "IT'S ABOUT ME?"
  papyrus "MAYBE??"
  gaster "THAT'S A TRICKY SITUATION YOU ARE PUTTING ME THERE, PAPYRUS"
  papyrus "COME ON, REALLY, I NEED SOME PRIVACY ON THIS ONE"
  gaster "THEN GO"
  papyrus "OK"
  papyrus "BUT DO NOT PEEK!"
  "* Papyrus leaves *"
  gaster "MY SWEET CHILD"
  "* Scene changes to Toriel's house *"
  toriel "Papyrus!"
  toriel "Nice to meet you"
  papyrus "HOW'S EVERYTHING GOING?"
  papyrus "HOW'S FRISK HANDLING EVERYTHING?"
  toriel "They are fine"
  $ if day == 2:
    toriel "They are sleeping after what happened yesterday"
  $ else:
    toriel "They are sleeping after what happened that day"
  toriel "But I think they'll be fine"
  papyrus "GREAT!"
  papyrus "..."
  papyrus "OH!"
  papyrus "I NEED TO ASK YOU SOMETHING"
  toriel "Oh?"
  toriel "And what it could be?"
  
return
