label afternoonUndyne:
  papyrus "I THINK IT SHOULD BE A GOOD IDEA TO VISIT UNDY..."
  papyrus "!?"
  gaster "I THINK SHE'S COMING ALREADY"
  papyrus "OH MY GOD"
  "AAAAAHHHHHHHHHH"
  "* trample trample trample *"
  "* undyne crash with papyrus *"
  undyne "Papyrus! hey, come out punk!"
  papyrus "WHAT?! UNDYNE, PLEASE!"
  undyne "Excelent"
  undyne "Come on!"
  "* undyne and papyrus retires. Gaster appears *"
  gaster "I WONDER IF I SHOULD FOLLOW THEM"
  gaster "..."
  gaster "IT'S SEEMS THEY HAVE ARRIVED"
  "* scene changes, Papyrus and Undyne are in the school yard *"
  undyne "PAPYRUS"
  papyrus "WHAT?"
  undyne "I know you know how to drive"
  papyrus "SORTA"
  undyne "Sorta?"
  papyrus "LIKE, I DRIVED THE CAR LIKE ONCE AND THEN I REALIZED THAT RUN AND JUMP IS MORE CONVENIENT FOR ME"
  undyne "But you have a licence"
  papyrus "YES, I THINK I'M ONE OF THE 5 MONSTERS WITH A DRIVING LICENCE"
  undyne "Great!"
  undyne "I need you to drive a bus with the kids"
  undyne "We're doing a school trip"
  papyrus "I DON'T HAVE THAT KIND OF LICENCE"
  undyne "Which kind of licence?"
  papyrus "THE BUS KIND OF LICENCE"
  undyne "You need a special licence to drive buses?!"
  undyne "But you know how to drive cars, isn't like... the same... but bigger?"
  papyrus "I THINK YOU NEED TO CERTIFY YOU ARE BETTER AT IT..."
  papyrus "I DON'T REMEMBER, BUT I THINK THERE'S A LICENCE FOR BUSES AND A LICENCE FOR BIG TRUCKS..."
  papyrus "AND THE BUSES LICENCE LET'S YOU DRIVE TRUCKS AND CARS.."
  papyrus "BUT THE TRUCK LICENCE DO NOT LET YOU DRIVE BUSES..."
  papyrus "THEN THE CAR LICENCE DO NOT LET YOU DRIVE TRUCKS AND BUSES..."
  papyrus "AND I HAVE THE CAR LICENCE..."
  undyne "WHY THIS HAVE TO BE SO COMPLICATED?!"
  undyne "It's just a bigger car"
  papyrus "WHY DO YOU NEED ME DRIVE A BUS?"
  undyne "I.. "
  extend "don't... "
  extend "wanna... "
  extend "hire... "
  extend "a human... "
  extend "driver..."
  undyne "After what happened to Frisk, I don't feel confortable with a human there"
  undyne "It's going to make the kids nervious"
  
  
return
