label afternoonAlphys
  if tryWithAlphys:
     call alphysAlt
  else:
    papyrus "I WANT TO VISIT DR ALPHYS NOW..."
    gaster "YOU WANT VISIT HER?"
    papyrus "WE HAVE THE MORNINGS FOR OUR TRAININGS, SO I HOPEFULLY ASSUME SHE BELIEVES I'M THERE BY MISTAKE"
    papyrus "BUT IN THE AFTERNOONS I DON'T HAVE THAT EXCUSE"
    papyrus "AND SHE ALWAYS LOOKS SO NERVIOUS WITH ME AROUND AND I DON'T KNOW WHAT ELSE TO DO"
    gaster "WELL, YOU ARE DIFFICULT TO READ"
    gaster "BUT THAT JUST COMES WITH BEEN A SKELETON"
    gaster "WE'RE ALWAYS SMILING AND THAT'S COMPLICATED FOR OTHER MONSTERS"
    papyrus "I GUESS I WILL WAIT UNTIL TOMORROW"
    gaster "IF YOU DON'T LIKE TO DO THIS, WHY DO YOU WANT TO DO IT?"
    papyrus "WELL, IF I CAN TRICK DR ALPHYS TO TELLING ME ANYTHING ABOUT SCIENCE, MAYBE THAT WILL JOG MY MEMORY ABOUT YOU!"
    gaster "OH, I SEE!"
    gaster "..."
    gaster "SOUNDS LIKE A GOOD PLAN"
    papyrus "OF COURSE IS A GOOD PLAN"
    gaster "THEN YOU SHOULD GO TO SEE HER"
    papyrus "BUT WHAT IF I MAKE HER NERVIOUS?"
    gaster "THEN IS NOT A GOOD PLAN BECAUSE YOU HAVE THAT PROBLEM"
    papyrus "..."
    papyrus "I GUESS..."
    gaster "IF IT'S JUST 'JOG YOUR MEMORY', JUST GO TO THE LIBRARY AND READ SOME PROGRAMMING THEORY"
    gaster "MAYBE ALSO SOME MAGIC THEORY"
    gaster "THERMODYNAMICS"
    extend ", MECHANICS"
    extend ", FLUID MECHANICS"
    extend ", MAYBE ALSO SOME QUANTUM MECHANICS"
    papyrus "I KNEW ALL THAT?"
    gaster "YOU WEREN'T AN EXPERT, BUT YOU KNEW ENOUGH TO PROGRAM COMPLICATED DATA ANALISYS SYSTEMS, AND SOME ADMINISTRATIVE SYSTEMS AS WELL"
    papyrus "MMMM..."
    gaster "PAPYRUS?"
    papyrus "MAYBE I SHOULD START SINCE THE BEGINNING"
    papyrus "AFTER ALL, I READ 'Puzzle Design' BEFORE READING 'Advanced Puzzle Design'"
    papyrus "MAYBE DR. ALPHYS KNOWS AN INTRODUCTORY BOOK"
    gaster "DIDN'T YOU SAID YOU WISHED TO NOT BOTHER HER?"
    papyrus "I'M GOING TO SENT HER A TEXT"
    papyrus "..."
    papyrus "OH, SHE TEXTED BACK"
    papyrus "THERE'S LOTS OF RESOURCES"
    papyrus "AND THE MESSAGES KEEP COMING"
    papyrus "EVENTUALLY IS GOING TO END, I GUESS..."
    gaster "LET'S TALK AFTER YOU FINISH TO READ ALL THAT MATERIAL"
    papyrus "SURE!"
    "..."
    papyrus "SHE'S STILL SENDING STUFF"
    papyrus "OH NO..."
    papyrus "OH NO"
    papyrus "OH"
    papyrus "..."
    papyrus "..."
    papyrus "..."
    papyrus "........"
    papyrus "............................................"
    papyrus "I HAVE MADE A TERRIBLE MISTAKE"

 return
