label afternoonAsgore
    papyrus "I WANNA TALK WITH THE KING ABOUT..."
    papyrus "STUFF"
    gaster "DO YOU TALK WITH THE KING?"
    papyrus "THAT'S A MOKING TONE I'M HEARING THERE?"
    gaster "NAH, ASGORE IS UNABLE TO ACTUALLY MAKE DESICIONS"
    gaster "IT GETS FRUSTRATING AT TIMES"
    papyrus "TO BE HONEST I NEVER GO TO TALK WITH THE KING BECAUSE I HAVE THIS FEELING HE'S ALWAYS WITH UNDYNE AND..."
    papyrus "I MIGHT GET A NOGGIE"
    papyrus "THAT HURTS"
    gaster "IF YOU WANT I CAN CHECKOUT IF YOUR FRIEND IS WITH HIM RIGHT NOW"
    papyrus "NO, NO IT'S OK"
    papyrus "I JUST WANT TO TALK WITH HIM"
    papyrus "ALONE"
    papyrus "SO, WELL, DON'T PEEK"
    "* Papyrus leaves *"
    gaster "OH, MY SWEET SUMMER CHILD..."
    gaster "YOU'RE WAY TO MUCH LIKE ME...
    "* Papyrus appears at the front of the School, were he assumes the king must be *"
    papyrus "YOUR MAJESTY?"
    asgore "I'm going down right now"
    asgore "Just stay put so I don't crush you"
    "* Asgore lands next to Papyrus, Papyrus tremble with Asgore's landing *"
    asgore "There's something you need Papyrus?"
    papyrus "I SEE WHERE UNDYNE LEARNT THAT!"
    asgore "She's way more nimble that I'll ever be"
    papyrus "UNDYNE NEVER TAUGHT ME THAT"
    asgore "Seriously?"
    asgore "What did she taught you?"
    papyrus "HOW TO MAKE SPAGETTI"
    asgore "That's kinda explains a lot"
    asgore "And at the same nothing at all"
    papyrus "I DON'T KNOW, I KNEW HOW TO KINDA FIGHT BEFORE MEETING HER"
    papyrus "IN WAY, I GUESS I ASSUMED SHE BELIEVED I JUST NEEDED TO LEARN TO COOK"
    asgore "Well, you are a skeleton"
    asgore "Who created you must have really good fighting skills"
    papyrus "SERIOUSLY?"
    gaster "..."
    asgore "Magic levels is actually what differs between skeletons the most"
    asgore "If they really make an effort while doing the spell their bodies can be like 4 times more resistant than a normal monster's"
    papyrus "YOU SEEM TO KNOW A LOT ABOUT SKELETONS"
    asgore "I just figure out is part of my work as the king..."
    asgore "Know about the history of my people"
    asgore "What happened during the war, and then when you guys have to be created again and..."
    asgore "Wait."
    papyrus "YEAH"
    papyrus "ABOUT THE PLOTHOLE YOU JUST FIGURE OUT"
    asgore "Who created you?"
    papyrus "YES, I CAME TO ASK YOU THAT"
    asgore "You don't remember..."
    papyrus "DO YOU?"
    asgore "I find that weird..."
    asgore "I know and learn about and with my people, is part of the description of my job..."
    papyrus "IF YOU DON'T KNOW IT'S OK YOUR MAJESTY..."
    asgore "Maybe Sans did"
    papyrus "NO, THAT'S IMPOSSIBLE"
    asgore "We should ask him"
    papyrus "NO WAIT!"
    "* Scene changes to the forest *"
    asgore "After all, skeletons do not have established family structures"
    papyrus "YOU MAJESTY PLEASE"
    "* Scene changes to outside the Font Family House *"
    asgore "He might have decided to create himself a brother and did the best one"
    papyrus "I KNOW I'M GREAT YOUR MAJESTY, BUT PLEASE STOP"
    "* Scene changes to outside the Elevator to High Snowdin *"
    asgore "We'll never know if we don't ask!"
    papyrus "I KNOW ALREADY HE'S NOT SO PLEASE DON'T DO THIS TO ME"
    asgore "Do you know already?"
    sans "oh, papyrus, your majesty"
    asgore "hello sans"
    asgore "I have a question for you"
    sans "oh"
    sans "what it could be"
    asgore "Did you created him?"
    papyrus "WHY?!"
    sans "no"
    sans "we follow family structures at our house"
    asgore "Oh"
    asgore "You didn't tell me that Papyrus"
    asgore "Well, I need to go"
    asgore "I have to finish with the eyebrows of the other Papyrus' head"
    asgore "Bye bye!"
    "..."
    papyrus "THAT WAS LESS TRAUMATIC THAN I THOUGHT IT WILL BE"
    sans "what are you doing bro?"
    papyrus "I DON'T KNOW"
    papyrus "I HAVE NO IDEA..."
    $ endingSans = True
return