label afternoonUndyne:
  papyrus "I THINK IT SHOULD BE A GOOD IDEA TO VISIT UNDY..."
  papyrus "!?"
  gaster "I THINK SHE'S COMING ALREADY"
  papyrus "OH MY GOD"
  "AAAAAHHHHHHHHHH"
  "* trample trample trample *"
  "* undyne crash with papyrus *"
  undyne "Papyrus! hey, come out punk!"
  papyrus "WHAT?! UNDYNE, PLEASE!"
  undyne "Excelent"
  undyne "Come on!"
  "* undyne and papyrus retires. Gaster appears *"
  gaster "I WONDER IF I SHOULD FOLLOW THEM"
  gaster "..."
  gaster "IT'S SEEMS THEY HAVE ARRIVED"
  "* scene changes, Papyrus and Undyne are in the school yard *"
  undyne "PAPYRUS"
  papyrus "WHAT?"
  undyne "I know you know how to drive"
  papyrus "SORTA"
  undyne "Sorta?"
  papyrus "LIKE, I DRIVED THE CAR LIKE ONCE AND THEN I REALIZED THAT RUN AND JUMP IS MORE CONVENIENT FOR ME"
  undyne "But you have a licence"
  papyrus "YES, I THINK I'M ONE OF THE 5 MONSTERS WITH A DRIVING LICENCE"
  undyne "Great!"
  undyne "I need you to drive a bus with the kids"
  undyne "We're doing a school trip"
  papyrus "I DON'T HAVE THAT KIND OF LICENCE"
  undyne "Which kind of licence?"
  papyrus "THE BUS KIND OF LICENCE"
  undyne "You need a special licence to drive buses?!"
  undyne "But you know how to drive cars, isn't like... the same... but bigger?"
  papyrus "I THINK YOU NEED TO CERTIFY YOU ARE BETTER AT IT..."
  papyrus "I DON'T REMEMBER, BUT I THINK THERE'S A LICENCE FOR BUSES AND A LICENCE FOR BIG TRUCKS..."
  papyrus "AND THE BUSES LICENCE LET'S YOU DRIVE TRUCKS AND CARS.."
  papyrus "BUT THE TRUCK LICENCE DO NOT LET YOU DRIVE BUSES..."
  papyrus "THEN THE CAR LICENCE DO NOT LET YOU DRIVE TRUCKS AND BUSES..."
  papyrus "AND I HAVE THE CAR LICENCE..."
  undyne "WHY THIS HAVE TO BE SO COMPLICATED?!"
  undyne "It's just a bigger car"
  papyrus "WHY DO YOU NEED ME DRIVE A BUS?"
  undyne "I.. "
  extend "don't... "
  extend "wanna... "
  extend "hire... "
  extend "a human... "
  extend "driver..."
  undyne "After what happened to Frisk, I don't feel confortable with a human there"
  undyne "It's going to make the kids nervious"
  papyrus "YES, THE KIDS"
  undyne "I thought in asking you because you always know a lot about something that interest you"
  papyrus "IN FACT, I THINK I'M THE ONLY MONSTER WITH A DRIVING LICENCE STILL LIVING IN THE KINGDOM"
  undyne "WHAT?!"
  papyrus "EVERYBODY ELSE GOT A DRIVER LICENCE SO THEY COULD TRAVEL AROUND THE WORLD"
  papyrus "I... DIDN'T"
  undyne "Papyrus"
  undyne "You will have to get the Bus driver licence"
  undyne "It's important"
  papyrus "SERIOUSLY"
  papyrus "OF COURSE, THE GREAT PAPYRUS WILL DO HIS BEST!"
  papyrus "WHILE I'M ACTUALLY MORE SURPRISED THAT THE SCHOOL HAS A BUS"
  undyne "Ah...."
  undyne "AAAAHHHHHHHHHHHHHH"
  "* Undyne dissappears to smash rocks off screen *"
  gaster "WHAT EXACTLY IS HAPPENING?"
  papyrus "I THINK UNDYNE BELIEVED THE DRIVER LICENSE CAME WITH THE VEHICLE"
  gaster "CAN YOU START SINCE THE BEGINNING?"
  papyrus "OH, SORRY, I FORGOT"
  papyrus "SO, HUMANS HAVE THIS MAGIC VEHICLE CALLED CAR"
  papyrus "WELL, IT'S NOT MAGIC, BUT USES HUMAN TECHNOLOGY"
  gaster "I KNEW IT"
  papyrus "AND THEY HAVE THIS LONG ROADS WHERE TO DRIVE THEM AND GO BETWEEN TOWNS"
  papyrus "BUT TO DRIVE ONE OF THOSE, YOU NEED TO HAVE A DRIVERS LICENCE"
  papyrus "THE NEW KINGDOM OF MONSTERS DOES NOT HAVE THAT LICENCE, BUT WE GOT AN AGREEMENT WITH THE HUMAN CITY NEARBY"
  papyrus "AND THEY ALLOWED US TO GET OUR LICENSES FROM THEM"
  undyne "WHAT ARE YOU TALKING ABOUT!?"
  papyrus "SORRY, SORRY, DID YOU SAY?"
  undyne "ARGH..."
  undyne "..."
  undyne "Are you saying that you need a bus to get the license"
  papyrus "I NEED TO PROVE I KNOW HOW TO DRIVE A BUS TO GET THE LICENSE"
  undyne "BUT HOW YOU LEARN TO DRIVE A BUS IF YOU CANNOT DRIVE A BUS?!"
  papyrus "WELL..."
  undyne "ARGH!"
  undyne "EXPLAIN THAT TO ME NEXT WEEK!"
  undyne "Humans..."
  undyne "They lie in their documentaries and now this"
  "..."
  gaster "I THINK I LIKE HER"
  "..."
  papyrus "YOU STAY AS FAR AWAY FROM HER AS POSSIBLE"
  gaster "I THINK YOU ARE UNDERSTIMATING HER"
  papyrus "YOU HAVE A POINT ON THAT ONE"
  
return
