label afternoonSans:
  if tryWithSans:
        call freeSansAlt
  else:
    papyrus "I GUESS IS GOING TO BE A GOOD IDEA CHECKOUT IF SANS IS DOING OK"
    gaster "YOU GUESS?"
    papyrus "I MEAN, HE WORKS ALL THE HOURS HE HAS TO, AND SOMETIMES GO TO JOKES WORKSHOP WITH TORIEL"
    gaster "JOKES WORKSHOP?"
    papyrus "THEY DRINK TEA AND EAT PIE AND WORKSHOP NEW PUNS AND JOKES"
    gaster "I SHALL NOT RECOMMEND THAT"
    gaster "THE QUEEN ONLY LIKES TERRIBLE PUNS AS FAR AS I REMEMBER"
    papyrus "I HATE TERRIBLE PUNS"
    gaster "SO, IT'S EXACTLY WHAT HE'S LOOKING FOR, GOOD GRIEF"
    papyrus "IT'S OK"
    papyrus "WELL, LET'S GO SEE"
    "* Scene changes to the elevator so Higher Snowdin *"
    papyrus "THE ELEVATOR IS CLOSED RIGHT NOW"
    gaster "THAT IS NOT GOOD PERHAPS?"
    sans "whats up bro?"
    papyrus "SANS!"
    sans "do you need to go to higher snowdin?"
    papyrus "YOU KNOW I JUMP THERE WHEN I NEED TO GO"
    sans "that's why i was asking"
    sans "you came to see your dear big bro, uh?"
    papyrus "I REALLY DON'T KNOW WHAT I KEEP DOING IT"
    sans "uh?"
    papyrus "YOU ARE RESPONSIBLE NOW"
    papyrus "BUT I KEPT COMING TO SEE YOU DESPITE KNOWING THIS"
    sans "you want to go to grillby's"
    papyrus "NO, WHY I SHOULD EVER WANT TO DO THAT?"
    papyrus "IT'S GREASY, AND THAT FEELS GROSS"
    sans "come on papyrus, i'll invite"
    papyrus "NO, NO, WAIT WAIT"
    "* Scene changes to Grillsby's bar *"
    gaster "I SUPPOSE THIS PLACE DOES NOT BRING GOOD MEMORIES"
    papyrus "YOU SUPPOSE CORRECTLY"
    sans "all the dogs are gone, but we can talk with grillsby while we're at it"
    papyrus "OK..."
    grillsby "..."
    papyrus "HELLO GRILLSBY"
    grillsby "..."
    "* Grillsby serves to Papyrus a glass of milk *"
    papyrus "I JUST FEEL THINGS DIFFERENTLY"
    papyrus "LIKE I FEEL GREASY 3 TIMES MORE POWERFUL THAN YOU FEEL GREASE"
    grillsby "..."
    papyrus "LIKE I TOLD YOU"
    papyrus "I CAN FEEL IT BETTER THAN ANYONE ELSE"
    grillsby "..."
    papyrus "NO, NO, WHY I SHOULD EVER THINK THAT"
    sans "they always thought you didn't like the food"
    papyrus "IT'S NOT ABOUT THE FOOD"
    papyrus "IT'S ABOUT THE GREASE FLOATING AROUND BECAUSE THE FOOD YOU COOK"
    papyrus "PLUS, YOU SHOULDN'T BE EATING JUNK FOOD EVERYDAY"
    papyrus "IT'S FOR SPECIAL MOMENTS"
    sans "i like to make all my dinners a special moment"
    papyrus "THEN IT'S NOT SPECIAL ANYMORE"
    grillsby "..."
    sans "don't do this to me grillsby"
    grillsby "..."
    sans "fair enough"
    papyrus "HAVE YOU TRIED TO INVITE TORIEL HERE?"
    sans "what?"
    grillsby "..."
    papyrus "YEAH!"
    sans "no.."
    sans "she's.. well..."
    papyrus "SHE'S A BOSS MONSTER, WHO KNOWS WHAT SHE THINKS ABOUT GREASE"
    grillsby "..."
    papyrus "EXACTLY!"
    papyrus "PLUS GRILLSBY IS GREAT AT CONVERSATIONS"
    grillsby "..."
    papyrus "SEE! THAT'S WHY YOU ARE GREAT AT IT!"
    sans "i..."
    sans "i don't feel that comfortable with that"
    grillsby "..."
    sans "and why are you dissapointed"
    papyrus "AT LEAST HE'S HONEST"
    papyrus "I'M OUT!"
    papyrus "THE GREASE IS GETTING UNDER MY BONES"
    papyrus "THANKS FOR THE MILK!"
    sans "i know why he keeps doing it, but i wish he could stop"
    grillsby "..."
    sans "you too?!"
    sans "..."
    sans "nah..."
    sans "relationships are too much work"
    sans "it would not be a good idea start a relationship and not been able to do my part"
    grillsby "..."
    sans "i don't know for how long skeletons can live... i think more than 100 years"
    sans "but she's going to be alive forever"
    grillsby "..."
    sans "i just don't feel ready man"
    grillsby "..."
    sans "i don't know"
    sans "maybe the day i don't feel sad and tired when i go out of my room"
    grillsby "..."
    sans "yeah..."
    sans "maybe we have time on our side..."
return
