label afternoonUndyne:
  papyrus "I THINK IT SHOULD BE A GOOD IDEA TO VISIT UNDY..."
  papyrus "!?"
  gaster "I THINK SHE'S COMING ALREADY"
  papyrus "OH MY GOD"
  "AAAAAHHHHHHHHHH"
  "* trample trample trample *"
  "* undyne crash with papyrus *"
  undyne "Papyrus! hey, come out punk!"
  papyrus "WHAT?! UNDYNE, PLEASE!"
  undyne "Excelent"
  undyne "Come on!"
  "* undyne and papyrus retires. Gaster appears *"
  gaster "I WONDER IF I SHOULD FOLLOW THEM"
  gaster "..."
  gaster "IT'S SEEMS THEY HAVE ARRIVED"
  "* scene changes, Papyrus and Undyne are in the school yard *"
  undyne "PAPYRUS"
  papyrus "WHAT?"
  undyne "I know you know how to drive"
  papyrus "SORTA"
  undyne "Sorta?"
  papyrus "LIKE, I DRIVED THE CAR LIKE ONCE AND THEN I REALIZED THAT RUN AND JUMP IS MORE CONVENIENT FOR ME"
return
