label decisions:
  papyrus "SINCE WE'RE DOING A TIME LOOP"
  papyrus "CAN I TRY AND DO SOMETHING DIFFERENT THAN THE LAST TIME?"
  gaster "YES"
  gaster "AND NO"
  papyrus "WHAT?!"
  gaster "THERE'S CERTAIN MOMENTS YOU CAN MAKE DECISIONS, BUT AFTER THOSE MOMENTS"
  gaster "YOU WILL RUN ON AUTO-PILOT UNTIL THE NEXT MOMENT YOU CAN MAKE A DECISION"
  papyrus "BUT AT LEAST I CAN DECIDE SOMETHING ELSE..."
  gaster "SOMETIMES THERE'S NOTHING ELSE TO DECIDE"
  gaster "AND OTHER TIMES, IF SOMETHING SEEMS SUSPICIOUS TO YOU CAN GO THERE AND TRY TO SEE IF YOU REACT DIFFERENTLY"
  gaster "SADLY THERE'S NOT MUCH ELSE YOU CAN DO"
  gaster "BUT IF YOU FIND SOMETHING SUSPICIOUS, YOU MIGHT HAVE SOMETHING TO ASK ME"
  gaster "AND, IF YOU ASK ME SOMETHING, YOU MIGHT HAVE ANOTHER THING TO DO DURING THOSE MOMENTS"
  gaster "LIKE I SAID, YOU WILL BE ON AUTO-PILOT MOST OF THE TIME, UNLESS SOMETHING DRASTIC HAPPENS"
  papyrus "THIS DOES NOT PLEASE ME"
  gaster "NEITHER DOES PLEASE ME, MY DEAR PAPYRUS"
  if howToTree == 0:
    $ howToTree = howToTree + 1
  return
