label pendriveBrainStorm:
    papyrus "WHAT DO I DO WITH THIS THING?"
    gaster "WELL, THAT'S A FLASH STORAGE UNIT, PEOPLE CALL IT PENDRIVE MOSTLY FOR ITS FORM"
    gaster "I THINK IS SOMEWHAT OLD, SO IT CAN HOLD AROUND 1GB, MAYBE A BIT MORE"
    gaster "YOU CAN USE IT TO SAVE DIFFERENT KIND OF COMPUTER FILES, LIKE EXECUTABLES, TEXT FILES, IMAGE FI.."
    papyrus "NO"
    extend ", NO "
    extend ", NO NO NO NO NO "
    extend ", NOOOOOOO... "
    papyrus "WHAT I AM ASKING IS WHAT DO I DO WITH THE FILES YOU PUT ALREADY HERE.."
    gaster "OH "
    extend "I UNDERSTAND"
    gaster "WHAT I DID PUT ON THAT PENDRIVE WERE THE SOFTWARE THEY USED FOR THE DETERMINATION TANKS"
    gaster "THE BLUEPRINTS OF THE TANKS, THE SOURCE CODE OF THE SOFTWARE"
    gaster "AND THE SERVER IN WHICH THAT SOFTWARE RUNS"
    gaster "IT ALSO HAD SOME DOCUMENTATION BUT I DON'T KNOW IF ITS RELIABLE ENOUGH"
    gaster "I DISCOVERED THAT THE SOFTWARE THEY USE TO CONTROL THE TANKS HAS AN API, SO IT SHOULD BE SOMEWHAT PAINLESS TO USE WITHOUT DESTROYING EVERYTHING"
    gaster "SO, WE JUST NEED SOMEONE WHO KNOWS A LOT ABOUT MONSTERS SCIENCE, DETERMINATION AND PROGRAMMING"
    papyrus "I HAVE 2 ANSWERS FOR THAT QUESTION AND I DON'T LIKE EITHER OF THOSE TWO"
    gaster "YOU HAVE 2 ANSWERS?"
    if pendriveTree < 1:
        $ pendriveTree += 1
    return

label pendriveSans:
    gaster "HAVE YOU THOUGHT ABOUT ASKING YOUR BROTHER?"
    papyrus "DOES HE REMEMBER YOU?"
    gaster "WHAT THAT HAS TO DO WITH THIS?"
    gaster "DIDN'T YOU SAID SEVERAL TIMES THAT HE LIKES SCIENCE, ESPECIALLY WHEN IS REAL?"
    gaster "HE MIGHT BE INTERESTED IF YOU ASK HIM"
    gaster "THIS IS, IN FACT, REAL SCIENCE"
    pause(1.0)
    gaster "PAPYRUS?"
    gaster "IT'S THERE SOMETHING WRONG?"
    papyrus "..."
    if pendriveTreeSans < 1:
        $ pendriveTreeSans += 1
    return

label pendriveSansTwo:
    gaster "PAPYRUS?"
    gaster "PLEASE CAN YOU TELL ME WHAT THE PROBLEM WITH YOUR BROTHER?"
    papyrus "I DON'T W{cps=*0.2}AAAAAAA{/cps}NNN{cps=*0.2}AAAAAAAAA{/cps}"
    gaster "WHY?"
    gaster "HE'S YOUR BROTHER"
    gaster "HE LOVES YOU"
    papyrus "I KN{cps=*0.2}OOOWWW...{cps=*0.2}"
    papyrus "IT'S JUST"
    papyrus "IF HE DOES REMEMBER YOU, HE WILL BE TOO SUSPICIOUS TO BE OF ANY HELP"
    papyrus "IF HE DOES NOT REMEMBER YOU, HE WILL NOT BELIEVE ME NO MATTER WHICH PROOF I HAVE AND WILL TRY TO CONVINCE ME YOU ARE A SOME SORT OF IMAGINARY FRIEND"
    papyrus "IT'S NOT GOING TO BE THE FIRST TIME"
    gaster "I STILL DON'T SEE WHY YOU SHOULDN'T TRY"
    gaster "IF IT DOESN'T WORK WE CAN LOOP BACK AND IT WILL LIKE NEVER HAPPENED"
    papyrus "I DON'T LIKE THAT EITHER"
    gaster "..."
    gaster "PAPYRUS..."
    gaster "PLEASE..."
    papyrus "{cps=*1.5}OK FINE I'LL ASK HIM{/cps}"
    gaster "THANKS YOU"
    papyrus "IT'S NOT GOING TO WORK THOUGH"
    gaster "BUT WE'RE GOING TO TRY AND THAT'S IMPORTANT"
    papyrus "YEAH... YOU RIGHT..."
    if pendriveTreeSans < 2:
        $ tryWithSans = True
        $ pendriveTreeSans += 1
    return