label wallBreakingStuff:
    papyrus "LOOK, I SHOULDN'T KNOW THIS"
    papyrus "AND I KNOW THIS IS KIND OF WAY TOO 4TH WALL BREAKING-ITY"
    papyrus "BUUUTTT..."
    gaster "?!"
    papyrus "WHY ARE YOU NOT TALKING ON... WINGDINGS?"
    gaster "OH!"
    gaster "WELL..."
    gaster "LET'S ASSUME THERE'S NO 4TH WALL JUST FOR THIS QUESTION"
    gaster "WELL..."
    gaster "JUST HAPPENED THAT THE GAME ENGINE DOES NOT SUPPORT THAT KIND OF TYPOGRAPHY"
    papyrus "SERIOUSLY?!"
    gaster "AND... SINCE THE DEVELOPER WAS PLANNING FROM THE BEGINNING REPLACE MY SPEECH FONT WITH NEW ASTER..."
    gaster "SHE DECIDED TO WRITE THIS INSTEAD OF... FIXING IT"
    papyrus "WELL, IT'S MUST BE QUITE DIFFICULT TO FIX AND NOT WORTH THE EFFO..."
    gaster "SHE DIDN'T LOOK AT IT"
    papyrus "SHE'S WORST THAN SANS!"
    gaster "I KNOW..."
    if wallBreakingStuff < 1:
        $ wallBreakingStuff = wallBreakingStuff + 1 
    return

label moreWallBreakingStuff:
    papyrus "OK, I HAVE ANOTHER 4TH WALL BREAKING ONE"
    gaster "SHOOT"
    papyrus "WHY DO YOU TALK IN NEW ASTER THEN?"
    gaster "IT'S JUST A THEORY"
    gaster "YOU KNOW, SINCE I'M CALLED 'W.D. GASTER'"
    gaster "SO THAT CAN MEAN"
    gaster "WIND DIN G - ASTER"
    papyrus "OHHHHHHHHHHHHHHHH"
    gaster "SHE FOUND THAT QUITE CLEVER"
    papyrus "I SEE..."
    if wallBreakingStuff < 2:
        $ wallBreakingStuff = wallBreakingStuff + 1 
    return

label wallBreakingStuff2:
    papyrus "I HAVE ANOTHER QUESTION THAT MAAAYYYBEEE I SHOULDN'T REALLY HAVE"
    gaster "I DON'T UNDERSTAND WHY SHE WRITES THIS KIND OF STUFF"
    papyrus "WHY DO WE USE THE SAME TERMINOLOGY AS HUMANS FOR PROGRAMMING?"
    gaster "ARE YOU WORRIED I SAID YOU CREATED YOUR OWN VERSION OF MONGODB?"
    papyrus "I JUST FIND THAT KIND OF ABSURD!"
    gaster "WELL, THIS ARE COMPLEX DEFINITIONS AND, MAYBE, CREATE HER OWN WAY TO EXPLAIN THIS DEFINITIONS WAS NOT WORTH THE EFFORT"
    gaster "ESPECIALLY THE VISUAL NOVEL IS TECHNICALLY NOT ABOUT WORLD BUILDING OR PROGRAMMING ITSELF"
    papyrus "STILL IT MAKES NO SENSE"
    papyrus "ESPECIALLY WHEN THE AREAS OF INFORMATICS AND COMPUTER SCIENCE WERE BORN ON DIFFERENT PLACES"
    papyrus "AND BOTH WERE ABOUT DIFFERENT THINGS"
    papyrus "BUT FOR SOME REASON NOW ARE KINDA..."
    papyrus "..."
    gaster "MY DEAR PAPYRUS?"
    papyrus "I JUST REALIZED SHE'S WRITTING THIS TO BRAG"
    gaster "THAT'S A GOOD EXPLANATION AS ANY"
    if wallBreakingStuff < 3:
        $ wallBreakingStuff = wallBreakingStuff + 1 
    return
