
#Frisk
image friskImg worried = im.FactorScale("frisk/worried.png", 0.7)
image friskImg worried flip = im.Flip(im.FactorScale("frisk/worried.png", 0.7), horizontal=True)
image friskImg explaining = im.FactorScale("frisk/explaining.png", 0.7)
image friskImg explaining flip  = im.Flip(im.FactorScale("frisk/explaining.png", 0.7), horizontal=True)
image friskImg unsure = im.FactorScale("frisk/unsure.png", 0.7)
image friskImg unsure flip = im.Flip(im.FactorScale("frisk/unsure.png", 0.7), horizontal=True)
image friskImg angry mild = im.FactorScale("frisk/angry.png", 0.7)
image friskImg angry mild flip = im.Flip(im.FactorScale("frisk/angry.png", 0.7), horizontal=True)
image friskImg affirmation = im.FactorScale("frisk/affirmation.png", 0.7)
image friskImg affirmation flip = im.Flip(im.FactorScale("frisk/affirmation.png", 0.7), horizontal=True)
image friskImg happy = im.FactorScale("frisk/happy.png", 0.7)
image friskImg happy flip = im.Flip(im.FactorScale("frisk/happy.png", 0.7), horizontal=True)
image friskImg scared = im.FactorScale("frisk/scared.png", 0.7)
image friskImg scared flip = im.Flip(im.FactorScale("frisk/scared.png", 0.7), horizontal=True)
image friskImg surprised = im.FactorScale("frisk/surprised.png", 0.7)
image friskImg surprised flip = im.Flip(im.FactorScale("frisk/surprised.png", 0.7), horizontal=True)
image friskImg scarf = im.FactorScale("frisk/scarf.png", 0.7)
image friskImg scarf flip = im.Flip(im.FactorScale("frisk/scarf.png", 0.7), horizontal=True)

##Future 
image friskImg future happy = im.FactorScale("frisk/future/happy.png", 0.7)
image friskImg future happy flip = im.Flip(im.FactorScale("frisk/future/happy.png", 0.7), horizontal=True)
image friskImg future angry = im.FactorScale("frisk/future/angry.png", 0.7)
image friskImg future angry flip = im.Flip(im.FactorScale("frisk/future/angry.png", 0.7), horizontal=True)