label torielWekufeQuestion:
    papyrus "OK"
    papyrus "I NEED TO DO THIS..."
    papyrus "BUT I DON'T WANNA"
    sans "do you not want to do what?"
    papyrus "ARGH!"
    papyrus "GOODBYESANSINEEDTOSPEAKWITHTORIEL"
    sans "..."
    $ endingSans = True
    "Smash cut to toriel's house"
    toriel "I hope everything is ok at the school"
    toriel "I had to leave early but..."
    papyrus "TORIEL!"
    toriel "Oh!"
    toriel "I'll call you later I have visitors"
    toriel "Well, what are you two doing around here?"
    papyrus "TWO?"
    sans "i don't either"
    sans "papyrus? care to explain us?"
    papyrus "........................"
    gaster "YES, THIS IS WAY MORE UNCONFORTABLE THAN USUAL"
    papyrus "........................"
    gaster "MAYBE YOU CAN SPIN THIS SOMEHOW..."
    papyrus "!!!"
    papyrus "I WAS..."
    papyrus "THINKING..."
    papyrus "ABOUT..."
    papyrus "THE KIDNAPPERS..."
    toriel "Oh, Papyrus...."
    toriel "Do not worry about that, we'll take care of everything..."
    papyrus "I WAS JUST... WELL... THINKING THAT THEY WERE WEIRDLY... REALLY STIFF..."
    if not altRoute:
        papyrus "AND WEIRDLY WEAK?"
        papyrus "LIKE, I KNOW I'M GREAT AND ALL BUT..."
        papyrus "DON'T YOU FIND THAT KIND OF SUSPICIOUS?"
        gaster "OH NO... OH NO..."
        papyrus "YOU SHUT UP"
        $ gasterDreamsShattered = True
    else: 
        papyrus "NOT REALLY EXPRESSIVE AT ALL???"
        toriel "Well... there are humans which are not really expressive..."
        sans "also monsters..."
        papyrus "...."
        papyrus "I DON'T NOW WHY... BUT..."
        papyrus "THEY KINDA FELT DIFFERENT ANYWAY..."
    papyrus "SO..."
    papyrus "FOR... RESEARCH..."
    papyrus "I WAS WONDERING... IF IT'S THERE MORE BEINGS BEYOND HUMANS AND MONSTERS????"
    toriel "Mmmm"
    sans "i don't see why not"
    sans "but if they weren't humans according to you"
    sans "why did they look so much like humans?"
    papyrus "I WAS THINKING..."
    papyrus "IT'S THERE SOMETHING THAT... KINDA GLUES SOUL AND BODY TOGETHER?"
    toriel "Spirit"
    "!"
    toriel "I think that the name..."
    papyrus "IS IT THERE SOMETHING LIKE THAT?"
    toriel "Well, I don't think we as monsters have any surviving investigation about it"
    toriel "Specially because, even if it's there something, monster magic have no way to destroy or change that union"
    toriel "The only way we as monsters have to destroy the union between soul and body is by destroying either the soul or the body"
    sans "are you saying there's a kind of being that can destroy the spirit of another being and then basically possess its soul and body?"
    papyrus "YES! EXACTLY"
    "...."
    toriel "Why I feel there some investigation I'm missing?"
    papyrus "..................."
    sans "There's some investigation we're missing"
    toriel "Papyrus, what do you know?"
    papyrus "I WAS READING THE HUMAN INTERNET AND I FOUND SOMETHING SIMILAR AND APARENTLY ARE CALLED WEKUFE"
    toriel "I haven't heard that word in my life"
    toriel "And Gerson could barely preserve the most important parts of our history after the war..."
    toriel "If I don't think I had heard the word, most probably there's not surviving records of those beings from the monsters perspective"
    toriel "I guess we'll have to check the human internet"
    papyrus "NOW?"
    sans "you asked"
    papyrus "FINE..."
    "They sat down on the computer"
    sans "according to this, they seem to be spirits without souls or body"
    sans "we shouldn't be able to even see them"
    toriel "Unless they possesed a body and a soul"
    sans "well..."
    sans "according to some humans they can possess a kind of soul which are..."
    sans "about to go to a higher plane..."
    papyrus "BEFORE THEY GET BROKEN UP"
    pause(2)
    toriel "I don't get it"
    toriel "It cannot exist a being without a soul or a body, right?"
    sans "not in this dimension... i guess"
    toriel "Dimension?"
    papyrus "IS IT THERE SOMETHING ABOUT THE..."
    papyrus "CHINCHE MAPU???"
    sans "miñche mapu..."
    toriel "What's a Mapu?"
    sans "those seems to be like... lands?"
    sans "but i think it's more like dimensions..."
    sans "and our dimension is called... nag mapu???"
    "..."
    sans "it's a cosmology we're not familiar with, it's impossible for us to understand it fully just by reading humans' webpages"
    sans "but i think that's the gist of it"
    toriel "So, to recap"
    toriel "We're talking about beings from another dimension without a soul or a body"
    toriel "Which can separate soul and body"
    toriel "possess it" 
    toriel "use it to roam the earth"
    toriel "and Papyrus is suggesting a group of those beings kidnapped Frisk"
    sans "yes, i understand"
    sans "we better go back to our work"
    toriel "Why that makes so much sense?"
    papyrus "UH?"
    toriel "We need to go to the forest"
    if not altRoute:
        toriel "I'll call the humans and move our visit"
        toriel "If this is true, we have nothing to talk with them"
    toriel "I'm going to find them and they are going to get an earful about kidnapping my child!"
    gaster "THIS IS BAD"
    gaster "THE WEKUFES SEEM REALLY SCARED OF US MONSTERS FOR SOME REASON"
    gaster "I DO NOT THINK HAVING THE QUEEN OF ALL MONSTERS GOING AFTER THEM IS GOING TO HELP OUR CAUSE"
    gaster "I WOULD SUGGEST RESTART IF YOU LIKE"
    papyrus "YOU RIGHT"
    papyrus "I GOTTA TELL THEM"
    gaster "NO.. I.. I..."
    gaster "OH WELL..."

    "* Papyrus runs directly to the laboratory at Mount Anemi"
   
    if not altRoute:
        "* Inside the Fortress *"
        ivunche "Hey, Boss..."
        trauco "What?!"
        ivunche "It seems a... very thin human is running up here..."
        trauco "Wait"
        trauco "That's not one of the monsters?"
        ivunche "Which ones?"
        trauco "The ones who saved our last kid this week"
        ivunche "Ohhh..."
        trauco "Hey!"
        voladora "What's up boss?"
        trauco "Go tell them what's going on"
        trauco "We'll try to keep them busy"
        ivunche "No, I will definitly not"
        cuero "There's no need"
        cuero "I will talk with him"
        trauco "But..."
    
    "* Papyrus enters the lab *"

    papyrus "I MADE IT IN TIME!"
    gaster "I REALLY DON'T KNOW WHAT ARE YOU HERE"
    coo "You better have a good explanation of why are you here"
    papyrus "GOOD CHUNK OF THE NEW MONSTER KINGDOM MONSTERS IS SEARCHING FOR YOU AT THE FOREST"
    papyrus "I CAME TO TELL YOU NOT GO THERE"
    coo "But, how do you know this place?"
    papyrus "AHHH...."
    papyrus "CAN I TALK WITH THE CUERO PERSON PLEASE???"
    coo "No"
    cuero "Yes, of course you can"
    papyrus "I CAN HEAR THE ANOMALY"
    papyrus "HE'S NAME IS GASTER!"
    sans "what?!"
    cuero "And I see you also have an unwanted companion"
    papyrus "WHAT ARE YOU..."
    papyrus "OH, RIGHT"
    cuero "So, they follow you around because they don't trust you enough, I see"
    papyrus "HEY!"
    papyrus "WE HAVE... FAMILY ISSUES..."
    papyrus "WE'RE... WORKING ON THEM"
    cuero "If this make you feel ok, I can barely recall our last conversation"
    cuero "But you haven't used your magic against us twice"
    papyrus "EH..."
    cuero "I hope you can keep your... family from doing that as well"
    sans "this are the wekufe?"
    sans "from where you know them?"
    cuero "We're collecting determination from human children"
    cuero "That collected determination has caused an anomaly"
    sans "why are you telling us that?"
    cuero "Because that determination seems to be something your family member needs to communicate with someone important"
    sans "uh? papyrus?"
    papyrus "THAT DETERMINATION IS THE REASON I CAN HEAR AND SEE GASTER FROM WHEREVER HE IS"
    papyrus "I COULD ALSO RELIVE 2 DAYS AND A HALF THANKS TO HIM"
    sans "then why you didn't..."
    sans "..."
    sans "right"
    papyrus "IF IT MAKES YOU FEEL BETTER"
    papyrus "THE THEORY WAS YOU WILL NEVER BELIEVE ME IN LESS THAN 3 DAYS"
    sans "thanks, i guess"
    papyrus "THE..."
    papyrus  "WHOLE POINT OF ALL OF THIS IS..."
    papyrus  "MAYBE..." 
    papyrus "WE COULD USE THAT DETERMINATION TO GET GASTER BACK!"
    papyrus "THIS IS PROBABLY THE ONLY OPPORTUNITY WE HAVE WITH THIS MUCH DETERMINATION!"
    gaster "WITHOUT BREAKING SOME LAWS THE QUEEN SURELY PUT ON THE BOOKS"
    papyrus "YOU SHUT UP"
    sans "i..."
    sans "i don't know i would like that..."
    papyrus "UH?"
    papyrus "WHAT?"
    sans "i tried to get him back so many times and..."
    sans "i just have to give up..."
    sans "and i was finally feeling confortable moving away..."
    papyrus "I SEE"
    papyrus "I UNDERSTAND"
    papyrus "YOU DON'T HAVE TO DO IT"
    papyrus "I'LL DO IT MYSELF"
    sans "uh?"
    papyrus "CUERO, THAT'S THE NAME?"
    cuero "If you want it to be"
    papyrus "I'M GUESSING THIS WHOLE ANOMALY IS MESSING WITH YOUR EXPERIMENTS WITH DETERMINATION"
    cuero "You guessed correctly"
    cuero "The first thing I remember have tried was the only thing which has work so far"
    cuero "Which was to reverse the flow of the determination"
    if program:
        cuero "I'm guessing that program you have been using does the same thing"
    cuero "I don't know why exactly, but the 4th dimension of the Nag Mapu went out of shape"
    gaster "THAT WAS THE 1ST RESET"
    gaster "THE MOMENT I ACTUALLY FIGURE OUT IT WASN'T THE SAME SITUATION AS BEFORE"
    cuero "I assume your friend connected with the determination on the tanks"
    cuero "Because it was the only way to keep the equilibrium"
    if program:
        cuero "Using the same method again, must cause another monster to connect with the determination of the tanks"
        cuero "Since that determination is too much for the monster in question"
        cuero "Goes where the other monster is"
        cuero "But an imbalance occours"
        cuero "And the other monster is sent where the new monster was"
    papyrus "THAT THE ONLY THING YOU SAY IT WORKS"
    cuero "I have tried diferent ways to change how the determination flows"
    cuero "If your friend haven't felt them, then they were unsuccesful"
    gaster "THAT'S CORRECT. I NEVER FELT ANYTHING"
    papyrus "ARE YOU SAYING THERE'S NO WAY TO TAKE HIM OUT?"
    if program:
        papyrus "WITHOUT... YOU KNOW..."
    cuero "Not by my efforts, no"
    papyrus "I... HAVE BAD NEWS..."
    cuero "I suspected that"
    papyrus "???"
    cuero "You are a being from the Nag Mapu and your spirit is trying to handle the weirdness of everything"
    papyrus "..."
    papyrus "I'M AWARE I'M TRAVELING IN TIME"
    papyrus "BUT I FORGET ALMOST EVERYTHING"
    papyrus "I CANNOT LEARN NEW THINGS"
    papyrus "IT TAKES TONS OF EFFORT TO REMEMBER I HAVE TO DO SOMETHING DIFFERENT"
    papyrus "AND MOST OF THE TIME I'M NOT THE ONE WHO DECIDES THAT"
    sans "are you..."
    papyrus "YES..."
    sans "mmm..."
    gaster "THAT'S PRECIOUS"
    gaster "IT MEANS YOUR FRIEND DOESN'T REMEMBER WHAT THEY DID... THAT TIME"
    gaster "BECAUSE US, AS BEINGS FROM THIS DIMENSION"
    gaster "CANNOT REALLY HANDLE TIME TRAVEL"
    sans "why are you trying to help him?"
    cuero "It just not convenient for us wekufes to have monsters on our bad side, that's all"
    sans "yes, i will believe that"
    cuero "Also, I guess, it is because you might have some knowledge which can help us with our next experiment"
    cuero "But, mostly, because I really want to get over with this loop"
    sans "i see"
    sans "unlike us you are perfectly aware this is a repeat from days before"
    cuero "And anyway cannot avoid doing almost the same thing over and over again"
    cuero "My spirit might be from the Miñche Mapu"
    cuero "But the body and soul I'm using is from here"
    papyrus "YOU WANT TO ESCAPE THE LOOP AND GET MONSTERS' SCIENCE KNOWLEDGE"
    cuero "That's correct"
    papyrus "I CAN FOR SURE, ONLY GIVE YOU ONE THING OF WHAT ARE YOU ASKING"
    papyrus "THE OTHER, WELL"
    papyrus "OTHER PEOPLE CAN GET ACCESS TO IT"
    papyrus "IT WOULD DEPEND OF THEM TO GIVE YOU ACCESS OR NOT"
    papyrus "THAT THE ONLY THING I CAN PROMISE YOU"
    cuero "In exchange to get you out"
    papyrus "IN EXCHANGE TO GET ME OUT"
    "* Fade to white *"
return