label groceryShopping:
    papyrus "YES, EVERYTHING IS SO EXPENSIVE"
    papyrus "I THOUGHT YOU GUYS HAVE ALREADY MOVE ALL OF YOU FROM THE RUINS"
    muffet "It's called offer and demand deary"
    muffet "Monsters buy at this price anyways"
    papyrus "YES, MONSTERS LIKE ME"
    "Papyrus pays Muffet for the bread and some donuts"
    asgore "Excuse me, Do you have some spider muffins?"
    papyrus "YOUR MAJESTY!"
    asgore "Oh, howdy!"
    papyrus "WHAT ARE YOU DOING HERE?!"
    asgore "Buying some spider bread, like you do"
    asgore "I like grocery shopping"
    asgore "It help me to stay connected with everybody"
    papyrus "IF YOU SAY SO"
    asgore "Your head in the school yard got a severe case of bad eyebrows"
    asgore "I need to fix it before the afternoon or else"
    papyrus "MAYBE I NEED SOME EYEBROWS"
    papyrus "HOW I WILL LOOK WITH SOME EYEBROWS?"
    papyrus "INTERESTING I THINK"
    asgore "You are as great as you can be the way you are"
    papyrus "YES, I KNOW THAT"
    papyrus "I JUST THINK ON TRYING A NEW STYLE ONCE IN A WHILE"
    papyrus "YOU NEVER KNOW WHAT CAN YOU GET WITH A NEW HAIRSTYLE"
    asgore "I will personally not worry about it"
    asgore "Especially when you don't have any hair"
    papyrus "YOUR MAJESTY!"
    papyrus "I´M PRETTY SURE I CAN USE SOME EXTENSIONS"
    papyrus "LACK OF HAIR HAS NEVER BEEN A PROBLEM FOR ME"
    papyrus "WE SKELETONS ARE SMART!"
    asgore "There´s no way I can stop you, do I?"
    papyrus "OF COURSE NOT"
    asgore "I guess I´d better help then"
    asgore "Take some of my beard"
    papyrus "REALLY SIR??"
    papyrus "THANKS YOU!"
    "*Asgore gives Papyrus some of his hair, but inmediatly becomes ashes when he recieve it"
    papyrus "AHHHHWWWW...."
    asgore "I'm sorry Papyrus, real monster hair doesn't work like humans'"
    papyrus "THANKS AGAIN SIR"
    asgore "A pleasure"
    if resets < 3 and resets > 1:
        asgore "..."
        show papyrusImg worried flip at fade
        papyrus "?!"
        asgore "Uh, nothing... bye Papyrus"
    elif resets < 5 and resets > 3:
        asgore "You know"
        asgore "You suddenly remind me of... someone"
        papyrus "IT'S THEIR NAME W.D. GASTER?"
        asgore "Not sure"
    elif resets > 5:
        asgore ".."
        papyrus "IT´S THERE SOMETHING YOU WANT TO TELL ME?"
        asgore "Not exactly"
        asgore "I'm fine"
        $ asgoreKnows = True
    papyrus "STAY WELL YOUR MAJESTY"
    
return
