label visitAlphys:
    papyrus "DR ALPHYS!"
    alphys "Papyrus!"
    alphys "What"
    alphys "eh.."
    alphys "ehhh..."
    papyrus "YOU SAID SOMETHING IN OUR LAST TRAINING ABOUT A NEW EXPERIMENT OF YOURS"
    papyrus "I CAME TO CHECK IF YOU NEEDED SOME MORAL SUPPORT"
    alphys "ahhh..."
    papyrus "I´M YOUR PERSONAL TRAINER AFTER ALL"
    alphys "Now I need some quiet"
    papyrus "YOU MEAN WHITE NOISE"
    papyrus "OR ELSE YOU'LL END UP WATCHING THE NEW SEASON OF MEW MEW"
    alphys "Come on Papyrus"
    alphys "The first chapter was promising"
    alphys "But for the moment is as good as the second season"
    alphys "Which means is trash"
    alphys "While they admitted the second season ruined Mew Mew story arc"
    alphys "And they are trying to fix it"
    alphys "I don't see how that is fixing it"
    alphys "They should try another aproach if they want to keep the franchise alive"
    alphys "But the 1st season is a classic already"
    alphys "They can't fix that"
    papyrus "ISN'T THE MANGA STILL GOING?"
    alphys "Yes, yes"
    alphys "But that a manga based on the 1st season"
    alphys "Mew Mew is an original animation"
    alphys "It's not very good"
    alphys "But at least is better than this 2nd and 3rd season trash"
    papyrus "I SEE YOU HAVEN'T LOST IT!"
    papyrus "UNDYNE IS ALWAYS TELLING ME ABOUT HOW YOU RANT ABOUT WHEN THEY SEE AN EPISODE OF THE NEW SEASON"
    alphys "Yeah, she loves see me suffer and complain"
    papyrus "SHE DESCRIBE IT AS 'PASSIONATE AND FOCUSED'"
    alphys "Why we always end up talking about how much Undyne loves me?"
    papyrus "I DON'T KNOW"
    papyrus "YOU STILL SEEMS HAVE SOME ISSUES WHEN IS ABOUT LIKING ANIME"
    alphys "You know"
    alphys "I lied so much some times I feel I don't deserve Undyne's love"
    papyrus "SANS IS GETTING BETTER ABOUT HIS LAZYNESS, BUT VERY SLOWLY"
    papyrus "MAYBE YOU JUST NEED MORE TIME TO UNDERSTAND UNDYNE LOVES YOU FOR HOW YOU ARE"
    alphys "Maybe..."
    alphys "Well..."
    alphys "I'd better get back to programming"
    papyrus "PROGRAMMING?"
    alphys "Yes..."
    alphys "It's something very difficult, and you need time and effort to understand them"
    papyrus "HEY! THEN IS LIKE FIGHTING!"
    papyrus "OR COOKING SPAGUETTI!"
    papyrus "YOU NEED TIME AND EFFORT TO UNDERTAND IT AND GET GOOD AT IT!"
    alphys "Something like that"
    alphys "But in programming you tell the computer what to do"
    papyrus "REALLY?"
    alphys "Yes"
    alphys "But in a language the computer understand"
    alphys "Because the computer doesn't understand normal language"
    papyrus "WHAT KIND OF THINGS YOU CAN TELL TO THE COMPUTER"
    alphys "For a very simplificated example"
    alphys "You can tell them that..."
    alphys "That table is an object which can contain some other objects like cups"
    papyrus "SO THE OBJECT TABLE ATRIBUTTE IS CONTAIN OTHER OBJECTS?"
    alphys "Yes..."
    alphys "..."
    alphys "Papyrus.."
    alphys "What's a float?"
    papyrus "A TYPE OF NUMBER VARIABLE THAT CAN CONTAIN DECIMAL POINTS"
    alphys "What's a factory?"
    papyrus "AN OBJECT WHICH PRODUCES OTHER OBJECTS"
    alphys "A singleton?" 
    papyrus "AN OBJECT WHICH HAVE A SINGLE INSTANCE DURING RUN"
    alphys "And Script Oriented Programming?"
    papyrus "A SMALL PROGRAM WHICH RUNS ON SEQUENCIAL ORDER"
    alphys "And a stack?"
    papyrus "A DATA STRUCTURE OF OBJECTS IN WHICH CAN ONLY ACCESS THE LAST ONE AT A TIME"
    alphys "Papyrus"
    alphys "Since when you know Programming Theory and Data Structures?"
    papyrus "SINCE YOU SAID TABLE"
    papyrus "IT JUST CAME TO ME SUDDENLY"
    alphys "Whoa.. that's weird"
    papyrus "I KNOW"
    papyrus "I KNOW..."
    $ papyrusKnowsProgramming = True
return 
