label visitMettaton:
    papyrus "LET'S CALL METTATON!"
    gaster "PLEASE DON'T"
    gaster "FOR THE LOVE OF EVERYTHING DON'T"
    "Phone" "* click *"
    phone "Hello, you have arrived to Mettaton's phone message machine"
    phone "Please leave your message and Mettaton will decide eventually if he will call you back"
    "Phone" "* click *"
    papyrus "AHHHHH"
    papyrus "HELLO?"
    papyrus "I MA AHHHH...."
    papyrus "PAPYRUS?"
    "Phone" "* click *"
    papyrus "AH?"
    phone "You have given access to Mettaton sound channel. Please hold"
    papyrus "WHA?"
    gaster "IT'S SEEMS TO ME HE HAS BEEN USING TOO MANY FAVORS FROM THE ROYAL SCIENTIST"
    papyrus "CAN YOU HEAR?"
    gaster "IT'S ONE OF THE PERKS OF BEEN STUCK AT THE BORDERS OF REALITY"
    papyrus "GOOD TO KNOW"
    "Phone" "* click *"
    metatton "Papyrus?"
    papyrus "METTATON?"
    metatton "I'm so happy you called! How did you get my number?! Alphys gave it to you finally?"
    papyrus "AHHHH"
    papyrus "IT WAS IN MY PHONE"
    metatton "mmmm"
    metatton "Probably I put it in there myself the last time we saw each other"
    metatton "In my defense you were at the party for around 10 minutes"
    papyrus "I DON'T LIKE LOUD MUSIC AND THAT MANY PEOPLE"
    metatton "Ok, maybe we could do something more intimate"
    gaster "I DON'T LIKE THAT WORD"
    metatton "Wanna get some coffee at the coffee shop?"
    papyrus "I DON'T DRINK COFFEE"
    metatton "Me neither, but I love their chia latte"
    papyrus "OK..."
    papyrus "I HOPE THEY HAVE MILK IN THERE"
    metatton "Sure they have!"
    metatton "See you later!"
    "Phone" "* click *"
    gaster "ISN'T THE COFFEE SHOP THAT FANCY RESTAURANT WITH THE VIEW TO THE SEA?"
    papyrus "WELL "
    "* Scene change to the restaurant with the sea view *"
    papyrus "YES, YES IT IS"
    papyrus "I TOTALLY FORGOT ABOUT THAT"
    gaster "YOU HAVE TO STOP THIS PAPYRUS, THAT MONSTER IS JUST A CULT LEADER WHICH IS USING HUMAN TECHNIQUES TO CONTROL THE MONSTERS INTO DOING HIS YOU AREN'T LISTENING, DO YOU?"
    papyrus "I NEED TO CONCENTRATE"
    papyrus "I ONLY HAVE PARASOCIAL RELATIONSHIPS WITH HIM"
    papyrus "IF I DON'T KEEP IT UNDER CONTROL I'LL CAME OUT AS REALLY CREEPY"
    gaster "YOU ARE UNABLE TO OUT CREEP HIM"
    gaster "YOU ARE SKELETON, SKELETONS ARE ADORABLE AND BEST HUGGERS"
    gaster "MEANWHILE HE'S A GHOST WITH A GOD COMPLEX WHICH USES HUMAN MANIPULATION TECHNIQUES, WHICH SHOULD BE ILLEGAL"
    gaster "BUT CONSIDERING HOW THE KING IS, I'M NOT SURPRISED HE WAS PERMITED TO THRIVE"
    metatton "Papyruuusssss"
    papyrus "ARGH"
    metatton "Did you get a coffee?"
    papyrus "THIS IS WARMED MILK..."
    papyrus "THEY PUT SOME SUGAR IN IT, BUT IT'S ALRIGHT"
    metatton "I always wanted to talk with you"
    papyrus "REALLY?"
    metatton "I mean..."
    metatton "You were sometimes there when I went to visit Alphys and Undyne, but never seem to stay long enough so we could, you know, talk"
    metatton "Then Undyne explains me you get nervous because you are a fan, which I'm very thankful"
    metatton "But I was thinking that, you know, we should know each other better if we are going to, coincide so many times"
    metatton "Plus, everybody says so many nice stuff about you"
    papyrus "REALLY?"
    metatton "Undyne is always telling you are way too nice sometimes"
    metatton "And Alphys is always trying to remember your drills"
    metatton "Or Frisk tell me about your hang outs"
    metatton "Or Sans"
    papyrus "ARRRGGGHHHHHHHHHHH"
    "* window crash *"
    metatton "Always comments how cool you are"
    "* Scene to the forest *"
    gaster "I HOPE WE HAVE LEARNT A LESSON HERE"
    papyrus "WELL...."
    "Phone" "* Ring Ring!"
    papyrus "YES?"
    metatton "Another coffee after the tour?"
    papyrus "..."
    papyrus "YES, OF COURSE!"
return