label checkSans:
    if papersPapyrusCreation == True:
        papyrus "SANS IS NOT HERE"
        papyrus "WHY?!"
        papyrus "I GUESS HE WILL APPEAR TO MAKE JOKES AT MY EXPENSE IN ANY SECOND"
        papyrus "BUT WHERE'S HE IS?"
        sans "sup' bro"
        papyrus "SANS! I NEED TO TALK WITH YOU!"
        sans "but bro"
        sans "i has been doing a ton of work"
        papyrus "IT'S NOT ABOUT PUNS!"
        papyrus "LISTEN"
        papyrus "I FOUND THIS PAPERS AT THE SCHOOL BASEMENT WHICH ARE A WEIRD KIND OF DIARY AND SOMEONE CALLED LIKE YOURSELF APPEAR IN THEM AND THEY WERE TALKING ABOUT MAKING A BROTHER FOR THIS PERSON CALLED EXACTLY LIKE YOU AND I SAID MAYBE IS SANS AND MAYBE THEY'RE TALKING ABOUT ME SO I CAME TO SEE IF YOU CAN TELL ME IF IT'S TRUE AND IF YOU REMEMBER ANY OF THIS"
        sans ".."
        sans "you have been with alphys way too long"
        papyrus "I WAS THINKING THAT MAYBE YOU COULD SHED SOME LIGHT ABOUT THIS"
        sans "that's dangerous"
        papyrus "WHAT?"
        papyrus "THE PAPERS?"
        sans "think"
        papyrus "SANS!"
        sans "just give me those papers and"
        papyrus "NO!"
        papyrus "YOU ALWAYS ARE DOING THINGS WITHOUT TELLING ME!"
        papyrus "I WILL NOT GIVE YOU THIS PAPERS UNTIL YOU TELL ME WHAT'S GOING ON!"
        sans "catch the stick, catch the stick"
        papyrus "OH! A STICK!"
        "Sans throws the stick and Papyrus leave the papers behind so he can catch them"
        sans "sometimes i'm glad i used some atributes of a dog"
        papyrus "CURSES! HE GOT ME!"
        papyrus "BUT THIS IS NOT DONE YET!"
        papyrus "HOMEWORK GRABING ATTACK!!!"
        "CHOMP!"
        sans "uh?"
        papyrus "TALK SANS!"
        sans "but... i´m too sleepy right... now..."
        sans "zzzzZZZZzzzz"
        papyrus "GREAT, THE SPECIAL ABILITY OF MY BROTHER"
        papyrus "SLEEPING EVERYWHERE AND EVERY MOMENT"
        papyrus "I WILL NOT GET ANSWERS FROM HIM"
        papyrus "I GUESS I HAVE TO ASK GASTER"
        sans "gaster?"
        papyrus "NOW WE'RE TALKING!"
        papyrus "EXPLAIN"
        sans "...."
        sans "w. d. gaster is our dad"
        papyrus "HE NEVER TOLD ME THAT"
        sans "he doesn't like the term, because he created us in regeneration tubes"
        sans "those probable are notes from he decided to create either of us"
        papyrus "BUT WHY NOBODY ELSE REMEMBER HIM?"
        sans "you shouldn´t remember him, only me"
        sans "how do you remember him?"
        papyrus "GOTTA GO BYE"
        "*Papyrus leaves*"
        sans "i will never catch him"
        sans "but how he knows anything about gaster?"
        sans "something weird is happening"
        $ gasterPapyrusSansDad = True
    else:
        papyrus "HE'S GETTING BETTER THANKS TO TORIEL"
        papyrus "BUT HE'S STILL SLACKING OFF WAY TOO OFTEN!"
        "*change scene*"
        papyrus "SANS IS NO WHERE TO BE FOUND"
        papyrus "HE'S LUCKY THERE'S NO MONSTERS WANTING TO GO TO HIGH SNOWDIN"
        papyrus "BUT HE SHOULD BE HERE!"
        sans "sup' bro?"
        papyrus "SANS!"
        papyrus "WHERE HAVE YOU BEEN?"
        sans "just walking"
        papyrus "WALKING TO GRILLSBY'S I BET"
        sans "no"
        sans "just walking"
        sans "the forest is very nice this time of the day"
        papyrus "YOU DON'T FOOL ME"
        papyrus "YOU WERE DOING SOMETHING LAZY I'M SURE!"
        sans "i was technically slacking off though"
        papyrus "BUT THAT KIND OF SLACKING OFF..."
        papyrus "..."
        sans "what?"
        papyrus "I DO THAT AS WELL"
        sans "you? slacking off?"
        papyrus "IT'S JUST"
        papyrus "THE TREES ARE GREEN"
        papyrus "THE SKY IS BLUE"
        papyrus "THE AIR IS CLEAN"
        papyrus "THE OUTSIDE IS AMAZING"
        sans "just give you energy to continue"
        papyrus "YES!"
        papyrus "MAYBE IS PART OF THE REASON OF WHY YOU ARE GETTING LESS LAZY"
        sans "?!"
        sans "it seems i'm losing my edge"
        papyrus "MAYBE YOU SHOULD USE YOUR ACTUAL FREE TIME TO DO THAT THOUGH"
        sans "don't worry"
        sans "i have that machine over there i did"
        sans "it tell me when someone is close"
        papyrus "AND YOU ARE GETTING RESPONSIBLE!"
        papyrus "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        sans "i'm totally losing my edge"
        papyrus "TOOOOORRRRRIIIIIIIIEEEEEEEEEEEEEELLLLLLLLLLLL!!!!!!!!!!!!!!!"
return
  