label visitUndyne:
    papyrus "UNDYNE!"
    undyne "PAPYRUS! What are you doing here?!"
    papyrus "I THOUGHT YOU WERE IN YOUR FREE TIME"
    undyne "I am"
    undyne "I'm just kind of nervious"
    papyrus "I NOTICED THAT"
    undyne "It not just..."
    undyne "You know..."
    undyne "But also..."
    undyne "That stupid human tradition"
    papyrus "YES, I HEARD ABOUT THAT"
    undyne "And Alphys likes humans"
    undyne "I wanted to surprise her but..."
    undyne "It's useless"
    papyrus "NOT IF YOUR FAVORITE SKELETON JUST HAPPEN TO"
    undyne "You found it?!"
    papyrus "..."
    papyrus "YES"
    papyrus "YES I DID"
    undyne "NO WAY"
    papyrus "YES WAY!"
    papyrus "HERE IS!"
    undyne "It's the Kissy Cutie Mew Mew limited edition Wedding Ring!"
    papyrus "ISN'T THAT WEIRD?"
    papyrus "THE GUY WHO SOLD ME THE THING ON THE HUMAN INTERNET SAID IT WAS A REAL RING MADE WITH GOLD AND DIAMONDS"
    papyrus "AND I'M LIKE"
    papyrus "WHO MAKES THINGS OUT OF MONEY?"
    undyne "I don't know"
    undyne "There's things about humans which are weeeiiiirrrddddd"
    papyrus "YEAH"
    undyne "But from where did you get the human money?"
    papyrus "HALLOWEEN DELIVERY"
    undyne "What?!"
    papyrus "YOU KNOW, THAT WEIRD FESTIVITY THEY HAVE IN WHICH THEY CELEBRATE US"
    undyne "Alphys explain me once what about that thing"
    undyne "But 'candy' still feels too flimsy"
    papyrus "WELL, JUST HAPPENS THAT HUMANS DOESN'T MIND HAVE THEIR THINGS DELIVERED BY A SKELETON AROUND THAT TIME"
    undyne "Papyrus... I..."
    undyne "I don't know what to say"
    papyrus "JUST KEEP IT QUIET"
    papyrus "ALPHYS SHALL NEVER KNOW I WAS THE ONE WHO FOUND IT"
    undyne "Are you sure?"
    papyrus "YES"
    papyrus "JUST ASK HER WHEN YOU THINK THE TIME IS RIGHT"
    undyne "You are getting weirdly wise Papyrus"
    undyne "But Frisk is going to be the ring bearer"
    papyrus "THE WHAT NOW?"
    undyne "You didn't know?"
    undyne "The humans weddings are super complicated with tons of parts"
    undyne "And I'm sure Alphys will want a full scale human style wedding"
    undyne "AAARRRRrrrrRRGGGggHHHHHhhhhhh"
    papyrus "WELL"
    papyrus "I'M GOING TO BE ONE OF THE SPOUSES BEST FRIEND!"
    papyrus "THAT'S A COOL THING TO BE IN A WEDDING!"
    undyne "You are way too nice Papyrus"
    papyrus "YOU SAY THAT LIKE IS A BAD THING"
    undyne "Well, I'm going to wait a couple of months"
    undyne "I have been studying this thing of the human wedding"
    undyne "And I still can't wrap up my head around this concept of the 'best man'"
    papyrus "SOUNDS LIKE A KIND OF FISH"
    undyne "Yeah..."
    undyne "Maybe I should ask Onion-san"
    $ visitUndyne = True
    
return
