label afterAfternoon:
  papyrus "WHAT WAS THAT?"
  gaster "WHAT WAS WHAT?"
  papyrus "THEY WERE TALKING ABOUT... WEDDINGS?"
  gaster "UH? WHAT'S THAT?"
  papyrus "WEDDING"
  papyrus "A CEREMONY IN WHICH HUMANS GET MARRIED"
  gaster "THEY HAVE A CEREMONY FOR THAT?"
  papyrus "YEAH"
  papyrus "I HAVE NEVER FOUND THE USEFULNESS BEHIND THAT BUT IT SEEMS SOMETHING FUN TO DO IF YOU CAN"
  gaster "IT SOUND LIKE THE WORST IDEA EVER"
  gaster "ESTABLISHING FAMILY UNITS IS A WEIRD IDEA IN GENERAL, BUT THE HUMANS HAVE TO MADE IT WEIRDER"
  papyrus "YES, I HAVE SOME HUMAN FRIENDS IN THEIR INTERNET NOT LIKING THE IDEA EITHER"
  gaster "DO YOU HAVE WHAT WITH HUMANS IN THEIR INTERNET?"
  papyrus "BUT THEY SHOULD NOT KNOW ABOUT THE WEDDING!"
  gaster "WHICH WEDDING?"
  papyrus "UNDYNE AND ALPHYS'! SHOULD BE A SECRET AND A SURPRISE!"
  gaster "TO WHOM?"
  papyrus "TO EVERYBODY! EVEN ME!"
  gaster "THEN HOW TO DO YOU KNOW?"
  papyrus "I PEAKED OVER UNDYNE DOING HER INVESTIGATION ABOUT WEDDINGS IN HER COMPUTER AND I ASKED HER"
  gaster "THAT ANSWER THAT QUESTION"
  papyrus "BUT WHY EVERYBODY ELSE KNOWS???"
  
return 

label afterMorning:
  $ resetFromQuestionMenu = True
return 
