label weddingFinal:
  "* Papyrus goes to Alphys' and Undyne's house"
  papyrus "DR ALPHYS! DR ALPHYS!"
  mettaton "Oh..."
  mettaton "Papyrus, what are you doing here?"
  papyrus "METTATON!!!"
  papyrus "OH. MY. GOD."
  papyrus "HE KNOWS MY NAME!"
  papyrus "IT'S NOT TIME FOR FANBOYISM PAPYRUS, GET SERIOUS"
  papyrus "HAVE... YOU... .................... SEEN......"
  mettaton "Alphys?" 
  mettaton "We have something to discuss before I start my tour"
  mettaton "But she isn't here!"
  mettaton "OH! The Calamity"
  papyrus "SO... YOU HAVE NO IDEA?"
  mettaton "I have a theory where she might be"
  papyrus "THEN LET'S GO!"
  "* Papyrus retires *"
  mettaton "Did Frisk told me something about what to do on this cases?"
  "* Papyrus comes back *"
  papyrus "WHERE DO YOU THINK SHE IS?"
  mettaton "Come with me"
  mettaton "It's where Alphys always plans to have her wedding"
  papyrus "HER WEDDING WHAT?"
  papyrus "NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO"
  "* Change scene to the Elevator to Higher Snowdin *"
  sans "oh, that's a surprise right there"
  papyrus "SANS!!"
  papyrus "WHAT ARE YOU DOING HERE?!"
  sans "..."
  sans "this is where i work"
  papyrus "!!"
  papyrus "I'M SORRY!"
  papyrus "I'M... JUST..."
  papyrus "SO NERVIOUS FOR SOME REASON"
  papyrus "I'M NOT THINKING STRAIGHT"
  gaster "THAT'S WHY I'M TELLING YOU NOT TO CONTINUE WITH THIS FOOLISHNESS"
  papyrus "YOU SHUT UP!"
  "* Papyrus retires *"
  mettaton "I do not believe Frisk told me about that"
  sans "oh, that?"
  sans "that's quite weird"
  mettaton "Ohhhhhhh..."
  mettaton "I need to spend more time with him"
  sans "i can arrange that"
  
return
