label weddingFinal:
  "* Papyrus goes to Alphys' and Undyne's house"
  papyrus "DR ALPHYS! DR ALPHYS!"
  metatton "Oh..."
  metatton "Papyrus, what are you doing here?"
  papyrus "METTATON!!!"
  papyrus "OH. MY. GOD."
  papyrus "HE KNOWS MY NAME!"
  papyrus "IT'S NOT TIME FOR FANBOYISM PAPYRUS, GET SERIOUS"
  papyrus "HAVE... YOU... .................... SEEN......"
  metatton "Alphys?" 
  metatton "We have something to discuss before I start my tour"
  metatton "But she isn't here!"
  metatton "OH! The Calamity"
  papyrus "SO... YOU HAVE NO IDEA?"
  metatton "I have a theory where she might be"
  papyrus "THEN LET'S GO!"
  "* Papyrus retires *"
  metatton "Did Frisk told me something about what to do on this cases?"
  "* Papyrus comes back *"
  papyrus "WHERE DO YOU THINK SHE IS?"
  metatton "Come with me"
  metatton "It's where Alphys always plans to have her wedding"
  papyrus "HER WEDDING WHAT?"
  papyrus "NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO NO"
  "* Change scene to the Elevator to Higher Snowdin *"
  sans "oh, that's a surprise right there"
  papyrus "SANS!!"
  papyrus "WHAT ARE YOU DOING HERE?!"
  sans "..."
  sans "this is where i work"
  papyrus "!!"
  papyrus "I'M SORRY!"
  papyrus "I'M... JUST..."
  papyrus "SO NERVIOUS FOR SOME REASON"
  papyrus "I'M NOT THINKING STRAIGHT"
  gaster "THAT'S WHY I'M TELLING YOU NOT TO CONTINUE WITH THIS FOOLISHNESS"
  papyrus "YOU SHUT UP!"
  "* Papyrus retires *"
  metatton "I do not believe Frisk told me about that"
  sans "oh, that?"
  sans "that's quite weird"
  metatton "Ohhhhhhh..."
  metatton "I need to spend more time with him"
  sans "i can arrange that"
  gaster "YOU WILL NOT ARRANGE ANYTHING..."
  gaster "..."
  gaster "RIGHT YOU CANNOT HEAR ME"
  "* Papyrus appears behind Alphys. A shot of the view of the area, pointing to the sea, while Alphys is looking to the distance, sighting *"
  papyrus "WHOOOOOIEEEEEEE"
  papyrus "THE VIEW FROM HERE IS REALLY NICE!"
  alphys "You can see the whole sea from here!"
  papyrus "..."
  alphys "I still remember the first time we saw it..."
  alphys "I never thought that the water could be this blue and extend for some long"
  papyrus "..."
  alphys "And... I will have my wedding here! I..."
  papyrus "DO YOU KNOW ABOUT THE WEDDING RING?!"
  alphys "Wedding Ring?"
  papyrus "AHH..."
  alphys "!!!"
  alphys "Undyne brought me a wedding ring?"
  papyrus "NOOOOO......"
  alphys "Undyne brought me a wedding ring!"
  papyrus "..."
  gaster "SHE DIDN'T KNEW"
  papyrus "..."
  gaster "YOU BLEW IT"
  papyrus "I BLEW IT!"
  gaster "YES, YOU DID THAT"
  papyrus "AND NOW WHAT WE WILL DO!?"
  sans "uh..."
  metatton "Call the only monster who can fix this of course!"
  papyrus "UH?"
  undyne "What just happened?"
  papyrus "I'M SORRY, I'M SOOOORRYYYY"
  metatton "How to say this..."
  metatton "Papyrus just... well..."
  metatton "'Spoiled' Alphys with the surprise of the wedding"
  undyne "I still don't understand the order of all the things!"
  undyne "..."
  undyne "Oh..."
  undyne "You mean Papyrus just slipped about the ring"
  undyne "Papyrus! Don't do this to me!"
  papyrus "I'M SOOOOO SOOOOOOORRRRRRRRYYYYYYYY"
  undyne "Ok, fine"
  undyne "I get it, I get it"
  papyrus "???"
  "* Undyne gets in front of Alphys, really nervious and somewhat frustrated *"
  undyne "Uh..."
  undyne "Alphys..."
  alphys "Undyne?"
  undyne "Well..."
  undyne "I..."
  undyne "I...."
  undyne "...."
  undyne "WHAT DO YOU DO FIRST AGAIN?!"
  metatton "You knell in front of her a.."
  undyne "Oh!"
  undyne "Now I remember it!"
  "* Undyne knell in front of Alphys *"
  undyne "Will you"
  undyne "..."
  undyne "do this human marriage ceremony with me?"
  alphys "..."
  alphys "..."
  alphys "..."
  alphys "..."
  metatton "Now you say yes!"
  alphys "Yes! Yes! Of course!"
  papyrus "AREN'T THEY ADORABLE?"
  sans "yes, yes they are"
  metatton "And I we have to organize a wedding!"
  metatton "Isn't that exciting!?"
  papyrus "METTATON?"
  sans "right, right"
  sans "you must know a lot about weddings"
  metatton "Of course!"
  metatton "Who do you think am I?"
  papyrus "METTATON?"
  metatton "Exactly!"
  metatton "And here the 2 best men are going to help make it glorious!"
  papyrus "WHO?!"
  metatton "You are Undyne's best friend!"
  papyrus "AM I?"
  metatton "Exactly my dear!"
  metatton "I got your contact, I got my contact in your phone, and as soon I'm back from my 3 weeks Mini tour..."
  papyrus "AAAAAAAAHHHHHHHHHHHHHHHHHHH"
  "* Glass window crash *"
  metatton "He jumped thru a window"
  sans "yes"
  metatton "Outside with no windows"
  sans "yes"
  metatton "Oh my!"
  sans "i know he's too cool for words"
  "* Papyrus stops running at the forest. Gaster appears *"
  gaster "ENOUGH FOOLISHNESS I SUPPOSE"
  papyrus "ARE YOU SAYING IF I HAD STOOD QUIET, NOTHING WOULD HAVE HAPPENED?"
  gaster "YES, I'M SAYING THAT"
  gaster "..."
  gaster "LOOK, I'M NOT GOOD AT TRYING, I DON'T KNOW WHEN TO TRY"
  papyrus "BUT"
  papyrus "YOU * HAVE * TO TRY!"
  gaster "BUT BY TRYING YOU MAKE IT WORSE"
  papyrus "I NEED TO LEARN WHEN, NOT! TO TRY!"
  gaster "YOU NEED TO LEARN WHEN TO TRY"
  papyrus "WHEN, NOT! TO TRY!"
  gaster "I THINK YOU CAN GO TO SLEEP NOW"
  $ weddingEnding = True
return
