label weddingFriskAsgore:
    if weddingFrom == 'frisk':
        papyrus "I'M GOING TO VISIT FRISK!"
        papyrus "THE HUMAN HAD A DIFFICULT WEEK NOT MATTER HOW MUCH I TRIED NOT TO"
        gaster "LIKE I SAID, I CANNOT MANAGE TO WHERE I CAN JUMP BACK IN TIME"
        papyrus "I KNOW, I KNOW, RELAX"
        papyrus "I JUST NEED TO UP MY GAME AS A SUPORTIVE FRIEND!"
        papyrus "HERE WE GOOOO"
        gaster "..."
        gaster "WHAT KIND OF GAME IS THAT?!"
    else: 
        papyrus "MAYBE I COULD ASK SOMETHING TO THE KING"
        gaster "REALLY?"
        gaster "LIKE WHAT?"
        papyrus "WHAT DO YOU THINK?"
        gaster "I WAS ASSUMING YOU WERE TALKING ABOUT THAT"
        gaster "STILL, I DON'T THINK THIS IS GOING TO BE PRODUCTIVE"
        papyrus "I KNOW YOU DON'T HAVE A HIGH OPINION OF THE KING"
        gaster "HE HAD STOPPED SOME OF MY EXPERIMENTS FOR MORAL CONCERNS MULTIPLE TIMES"
        gaster "WHAT DO YOU THINK I WOULD THINK ABOUT IT?"
        papyrus "MORAL CONCERNS?"
        gaster "..."
        gaster "I WOULD NOT TELL YOU WHERE THE KING IS"
        papyrus "I'LL ASK MY INFORMANT THEN"
        papyrus "AND THE KING DOES NOT REMEMEBER ANYTHING SO WHY ARE YOU SCARED?"
        gaster "I'M NOT SCARED!"
    asgore "You... you..."
    asgore "Has never gone to one of those?"
    frisk "No..."
    frisk "I'm too young for that..."
    asgore "I was hoping you could clarify me some... "
    extend "misconceptions I must have"
    frisk "I can help you with the internet"
    asgore "Oh..."
    asgore "That's actually a good idea"
    if weddingFrom == 'frisk':
        papyrus "I HAVE ARRIVED!"
        papyrus "IT'S ME!"
        papyrus "THE GREAT..."
        papyrus "!!"
        papyrus "YOUR MAJESTY!"
        papyrus "WHAT ARE YOU DOING HERE?!"
    else: 
        papyrus "HEY!"
        papyrus "FRISK!"
        papyrus "I'M SORRY IF I'M ASKING YOU..."
        papyrus "OH, YOUR MAJESTY"
    asgore "Oh, howdy!"
    asgore "I'm here with Frisk because"
    asgore "I need to figure out some things and... well, I thought they could help me"
    papyrus "OHHHHHH"
    papyrus "WHAT'S THAT?"
    papyrus "MAYBE I CAN HELP FRISK HELP YOU ABOUT THAT PROBLEM"
    asgore "You sure?"
    papyrus "YOUR MAJESTY PLEASE..."
    papyrus "MORAL SUPPORT IS ALSO HELP"
    asgore "Oh, you right!"
    asgore "Ok..."
    asgore "Ehem..."
    asgore "Do you know what 'deliver the bride' is?"
    papyrus "..."
    papyrus "............"
    papyrus "YES?"
    asgore "You do?"
    asgore "That's great"
    asgore "Did you heard Frisk? He knows what that is!"
    frisk "I imagined that"
    frisk "How many books do you have about it?"
    papyrus "AH..."
    papyrus "I FOUND SOME BOOKS ON THE HUMAN INTERNET ABOUT IT..."
    papyrus "I MADE A FRIEND ON A BOOKS STORE WHO SENT ME THE BOOKS FOR GOLD..."
    papyrus "I HAVE LIKE 10 COPIES IF SOMEONE NEED THEM..."
    asgore "I'm going to need a copy"
    papyrus "..."
    asgore "Papyrus?"
    papyrus "I'M SORRY YOUR MAJESTY BUT..."
    papyrus "WHY DO YOU NEED TO KNOW ABOUT WEDDINGS?"
    asgore "Didn't Undyne told you?"
    frisk "..."
    asgore "It's for her wedding with Alphys!"
    papyrus "!"
    frisk "?"
    papyrus "AAAAAAAAAHHHHHHHHHHHHHHHHHHHHHH"
    "* Runs away *"
    "* sound of glass breaking *"
    asgore "He... just... jumped out of the window?"
    frisk "Yes, he does that sometimes..."
    asgore "He has already learnt the stylish exit"
    asgore "That's really impressive"
return
