label weddingFriskAsgore
    asgore "You... you..."
    asgore "Has never gone to one of those?"
    frisk "No..."
    frisk "I'm too young for that..."
    asgore "I was hoping you could clarify me some... "
    extend "misconceptions I must have"
    frisk "I can help you with the internet"
    asgore "Oh..."
    asgore "That's actually a good idea"
    if weddingFrom == 'frisk':
        papyrus "I HAVE ARRIVED!"
        papyrus "IT'S ME!"
        papyrus "THE GREAT..."
        papyrus "!!"
        papyrus "YOUR MAJESTY!"
        papyrus "WHAT ARE YOU DOING HERE?!"
    else: 
        papyrus "HEY!"
        papyrus "FRISK!"
        papyrus "I'M SORRY IF I'M ASKING YOU..."
        papyrus "OH, YOUR MAJESTY"
    asgore "Oh, howdy!"
    asgore "I'm here with Frisk because"
    asgore "I need to figure out some things and... well, I thought they could help me"
    papyrus "OHHHHHH"
    papyrus "WHAT'S THAT?"
    papyrus "MAYBE I CAN HELP FRISK HELP YOU ABOUT THAT PROBLEM"
    asgore "You sure?"
    papyrus "YOUR MAJESTY PLEASE..."
    papyrus "MORAL SUPPORT IS ALSO HELP"
    asgore "Oh, you right!"
    asgore "Ok..."
    asgore "Ehem..."
    asgore "Do you know what 'deliver the bride' is?"
    papyrus "..."
    papyrus "............"
    papyrus "YES?"
    asgore "You do?"
    asgore "That's great"
    asgore "Did you heard Frisk? He knows what that is!"
    frisk "I imagined that"
    frisk "How many books do you have about it?"
    papyrus "AH..."
    papyrus "I FOUND SOME BOOKS ON THE HUMAN INTERNET ABOUT IT..."
    papyrus "I MADE A FRIEND ON A BOOKS STORE WHO SENT ME THE BOOKS FOR GOLD..."
    papyrus "I HAVE LIKE 10 COPIES IF SOMEONE NEED THEM..."
    asgore "I'm going to need a copy"
    papyrus "..."
    asgore "Papyrus?"
    papyrus "I'M SORRY YOUR MAJESTY BUT..."
    papyrus "WHY DO YOU NEED TO KNOW ABOUT WEDDINGS?"
    asgore "Didn't Undyne told you?"
    frisk "..."
    asgore "It's for her wedding with Alphys!"
    papyrus "!"
    frisk "?"
    papyrus "AAAAAAAAAHHHHHHHHHHHHHHHHHHHHHH"
    "* Runs away *"
    "* sound of glass breaking *"
    asgore "He... just... jumped out of the window?"
return
