label weddingTorielSans:
    if weddingFrom == 'sans':
        papyrus "I DON'T KNOW HOW BUT MY RESPONSIBLE BROTHER INSTINCT IS TELLING ME SANS IS NOT AT HIS POST"
        papyrus "I BETTER GO FIGURE OUT WHAT'S GOING ON"
        "* He leaves *"
        "* He back *"
        papyrus "BUT HE MAYBE HAS SOMETHING ELSE TO DO AND IT'S NOT LIKE HE HAS TO BE ALWAYS THERE..."
        papyrus "..."
        papyrus "BUT THIS ITCH..."
        papyrus "..."
        papyrus "I'D GO ANYWAY"
        "* He leaves *"
        gaster "BE NICE WITH YOUR BROTHER!"
        papyrus "I KNOW I KNOW"
    else:
        papyrus "MAYBE NOW I CAN ASK TORIEL A GOOD QUESTION"
        papyrus "SINCE GASTER IS {cps=0.5} NOT GOING TO HEAR! {/cps}"
        gaster "..."
        papyrus "WELL, SHE SHOULDN'T REMEMBER ANYTHING..."
        papyrus "BUT I'M STILL NOT THAT CONVINCED"
        "* He leaves *"
        papyrus "MAYBE I CAN HELP HER JOG HER MEMORY!"
        gaster "..."
        gaster "HE TRULY BELIEVES I'M NOT THERE IF I'M NOT TALKING TO HIM"
        gaster "IT'S UNSETTLING" 
        extend " IN A WAY"
    toriel "And..." 
    toriel "that happened"
    sans "ok..."
    sans "and you need help in that because"
    toriel "I'm not very good at writing speeches"
    sans "i'm not going to even ask"
    sans "so... ah..."
    sans "it's there something... do you want to do..."
    toriel "I don't know"
    toriel "I just prepared a list with..."
    toriel "suggestions..."
    sans "..."
    sans "we're totally doing this"
    toriel "I'm glad"
    toriel "Now"
    if weddingFrom == 'sans':
        papyrus "I KNEW YOU WERE SLA..."
        papyrus "..."
        papyrus "TORIEL?"
    else:
        papyrus "TORIEL!"
        papyrus "AT THE SCHOOL THEY SAID YOU..."
        papyrus "SANS?"
    papyrus "I WASN'T INFORMED OF THIS"
    papyrus "..."
    papyrus "I'M NOT SAYING THAT YOU HAVE TO TELL ME WHEN YOU HAVE A DATE"
    sans "..."
    sans "this is not a date"
    papyrus "THIS IS THE TEXTBOOK DEFINITION OF A DATE, YOU CANNOT FOOL ME!"
    papyrus "I READ THE MANUAL 10 TIMES BEFORE MY DATE WITH FRISK"
    toriel "There's a manual?"
    toriel "..."
    toriel "No, no, Sans is going to help me with some... writing I have to do"
    papyrus "IS THERE PUNS INVOLVED?"
    papyrus "..."
    sans "..."
    papyrus "OF COURSE THERE PUNS INVOLVED"
    sans "oh papyrus, cod you know us?"
    papyrus "COD?"
    toriel "That was *eely* bad"
    sans "salmon had to say it"
    papyrus "WHY THOSE ARE FISH PUNS?"
    sans "oh"
    sans "well, we fermi use some science puns as well"
    toriel "You right!"
    toriel "I *newton* prepare for that!"
    papyrus "WHY THOSE ARE SCIENCE AND FISH PUNS?"
    toriel "Uh?"
    toriel "You didn't knew?"
    sans "i'm pretty sure undyne already told him"
    papyrus "ABOUT WHAT?"
    toriel "About the wedding"
    papyrus "WHICH WEDDING?"
    toriel "He doesn't know about the wedding"
    sans "i knew about her intentions because of him, i'm sure he knows"
    papyrus "WHAT ARE YOU TALKING ABOUT?"
    toriel "Asgore called me because he has been  reading about humans' weddings and he told me he needed help with the official part of it"
    toriel "Because someone has to {cps=*0.2}deliver the bride{/cps} it seems"
    papyrus "..."
    papyrus "WHA..."
    papyrus "WHAT?!"
    toriel "For Undyne and Alphys' wedding of course"
    papyrus "AH"
    papyrus "AHHH"
    papyrus "AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
    "* Papyrus retires *"
    "* Glass crash *"
    toriel "He jumped tru the window"
    sans "he always does that"
    toriel "Oh!"
    toriel "He has already mastered the art of the stylish exit"
    sans "yes"
    sans "he just has to do it not only when he's nervious"
    toriel "He's cooler than you described"
    sans "i know words aren't enough"
return